### ISSUE TITLE
[Feature]Be able to load the config file from a remote location

### ISSUE THREAD

**Issue by soaErikNord** [Axway-API-Management-Plus/apim-cli#10]
**User story**
Would like to be able to store the Swagger-Promote config json in a source repository with the API definition.  Swagger-Promote would then provide the remote address to the config file when passing in the -c option.  So, would like our command to look like `./scripts/run-swagger-import.sh -a https://bitbucket/repository/service-swagger.json -c https://bitbucket/repository/service-config.json’.  

**Additional context**
This would allow us to NOT store the config files locally to our CI/CD process that Jenkins is running to accomplish these promotes.

**Comment by cwiechmann** [comment]
@soaErikNord, reading from a remote location is prepared - as the new CLI is now using distinct Adapters for different formats & sources. One source, could be the use-case you raised internally. 

Is this use-case described in this issue still valid and important to you?
