### ISSUE TITLE
running apim-cli.sh | apim-cli.bat from inside another script

### ISSUE THREAD

**Issue by themikebe** [Axway-API-Management-Plus/apim-cli#100]
**apim-cli version :** 1.2.3

Hello, 
I am attempting to use the apim.sh (at location : `src/lib/apim-cli/script/apim.sh`) from inside another script i'm writing. (location: `src/main/scripts/myScript.sh`)

When I do this, CP for apim-cli is not set correctly, because `$programDir` in apim.sh (and I assume the logic is the same in apim.bat) is referencing the directory from where I run `myScript.sh`and not `apim-cli/scripts/apim.sh`
 
Could the the logic to setup the classpath be adapted to be agnostic from the location the script is run from ?

Kind regards,
Michael

**additional context**
I found a work-around by using the following:
`programDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"`
the script could revert to the current behavior if `programDir` is still not set.

**Comment by cwiechmann** [comment]
I would propose to make use of the environment variable: [AXWAY_APIM_CLI_HOME](https://github.com/Axway-API-Management-Plus/apim-cli/wiki/8.2.-Environment-property-files#setup-axway_apim_cli_home), which has been introduced later for other reasons, but is a good candidate to support your use-case. 
Both scripts could be changed to verify the environment variable is set and if, it would be used to set the programDir. 

What do you think @themikebe?

**Comment by themikebe** [comment]
Hi Chris,

It seems I missed that bit in the docs :-)
Your solution would be a great way to do it, as I'm not sure my workaround works on all bash and sh versions.

Kind regards,
Michael

**Comment by cwiechmann** [comment]
Yes, the docs are not highlighting that option enough. I plan to update the getting started page with some instructions for that.

**Comment by cwiechmann** [comment]
@themikebe, I have changed the scripts as discussed to use the environment variable: `AXWAY_APIM_CLI_HOME` with preference to build the classpath. 
If you like you can download the scripts from GitHub directly:
https://github.com/Axway-API-Management-Plus/apim-cli/blob/develop/modules/apim-cli/assembly/scripts/apim.sh
https://github.com/Axway-API-Management-Plus/apim-cli/blob/develop/modules/apim-cli/assembly/scripts/apim.bat

They will be delivered like so with the next version 1.3.0 planned for Mid of November. I'm going to close this issue now. If it is not working for you, feel free to re-open this issue.
