### ISSUE TITLE
Small QoL Bug: command line options not arbitrary interchangeable

### ISSUE THREAD

**Issue by niklasbeck** [Axway-API-Management-Plus/apim-cli#102]
**API-Mgr. CLI version**  
APIM-CLI 1.2.3
**API-Manager and Service-Pack Version**  
7.7 July

**Expected behavior**  
According to the usage message, it should not matter in which order the arguments are entered

**Actual behavior**  
Apim cli prints out the standard usage help message and complains about a missing argument option

**Log-Output in Debug**  
ERROR: Missing argument for option: o

**Test case sample**  
The command "apim api get -wide -o csv" throws an error, but "apim api get -o csv -wide" works fine.
This is just a small quality of life change, so nothing too serious.

**Comment by cwiechmann** [comment]
Thanks for reporting @niklasbeck! The fix will be delivered with the next release.
