### ISSUE TITLE
Add API filter to apim app get command

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#104]
**User story**
As an organization admin I want to get all apps (from my organization) for a specific added API.
As an API Manager administrator I want to get all apps (from all orgs) for a specific added API.

**Additional context**

**Comment by jschaefer77** [comment]
Will close this issue. The apim api get command is already able to list subscribed apps for an API.

**Comment by cwiechmann** [comment]
I think this requirements makes sense anyway: Getting a list of apps (not APIs) that are subscribed to an API brings some value. 

This is some kind of a different view and easy to implement as the Application-Model internally also knows the subscribed APIs. It's a matter of using that information in a filter.

**Comment by cwiechmann** [comment]
Added a new option to the `apim app get` command:
`apim app get -s api-env -api "*HIPAA*"`

This is new option:
`-api <*MyAPI*>                        Filter applications having access to this API. You may use wildcards at the end or beginning.`
