### ISSUE TITLE
Staging for Application doesn't work

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apim-cli#107]
**API-Mgr. CLI version**
> Please make sure to use the latest available version before reporting a bug.
v1.2.3

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
override "name" and "credential oauth" with the value in the staging configuration file

**Actual behavior**
it seems ignoring the staging configuration file

**Log-Output in Debug**

**Test case sample**
> Please describe the steps you have done to replicate the issue
having a configuration file : appli_test.json : 
{
  "name": "appliTEST",
  "description": "appliTEST from DEV",
  "state" : "approved",
  "enabled" : true,
  "organization" : "API development",
  "credentials" : [ {
    "credentialType" : "oauth",
    "enabled" : true,
    "secret" : "0c3251c3-86a9-42e4-b482-9d17733d9b5e",
    "corsOrigins" : [ "*" ],
    "type" : "public",
    "clientId" : "0d05a8d2-b87c-45c4-946a-c709b7e45b27",
    "redirectUrls" : [ "" ]
  } ]
} 

having a staging file where name, description and credential oauth are modified : appli_test.rec.json : 
{
  "name": "appliTESTCHANGE",
  "description": "appliTEST from REC",
  "credentials" : [ {
    "credentialType" : "oauth",
    "enabled" : true,
    "secret" : "a4b74195-8f6f-429f-9b6c-c47e51ff6ed5",
    "corsOrigins" : [ "*" ],
    "type" : "public",
    "clientId" : "bceae3fe-debb-4daf-b390-6097c39b62c0",
    "redirectUrls" : [ "https://www.getpostman.com/oauth2/callback" ]
  } ]
} 

execute : apim.bat app import -s rec -c appli_test.json

**Comment by cwiechmann** [comment]
@Rennaud, yes, this is known issue in version 1.2.3 - Can you please try with the latest SNAPSHOT-Build of version 1.3.0 attached in the last comment of issue: #84 
Staging support has been added in that version for all entities. https://github.com/Axway-API-Management-Plus/apim-cli/blob/develop/CHANGELOG.md
