### ISSUE TITLE
support for local markdown file

### ISSUE THREAD

**Issue by gwandwingor** [Axway-API-Management-Plus/apim-cli#110]
**User story**
I would like apim-cli to support reading local markdown description files when deploying APIs

**Additional context**

In the context of enriching an API description, there is already the possibility to use "manual" or "markdown" options. 
As stated in the wiki, "markdown" option requires actual markdown file to be uploaded to a location available to API Manager server. 

For an API owner who wants to work autonomously and doesn't have access to the server, only "manual" option remains of interest. 

I ran some tests and it appears that when using "manual" option, by simply json-escaping a markdown file content, apim-cli can handle pretty long descriptions, which is a valid workaround. 

But this also means that it probably wouldn't cost much to go the extra mile and be able to load an external .md file and feed it to API Manager Rest API. It would then dramatically improve UX.

That would probably require indroducing a new descriptionType as shown below (as an example) : 

```
"descriptionType" : "markdownLocal",
"markdownLocal" : "../description/MyAPIDescription.md"
```

With this, API owners would be able to manage their markdown descriptions alongside their swagger and API config. They would also be able to leverage git versioning & markdown rendering capabilities.

This is clearly not something vital to apim-cli but I guess it would be much more useful than current "markdown" option.

What do you think ?

**Comment by cwiechmann** [comment]
I think that is a great idea and I will add this option to the CLI!

**Comment by cwiechmann** [comment]
@gwandwingor, obviously during export of such an API, the Markdown-Documentation will be exported with type manual, as the export cannot realize anymore that this has been managed by an external file. Is this acceptable?

**Comment by gwandwingor** [comment]
Yes @cwiechmann, that would totally make sense.
