### ISSUE TITLE
Add Upgrade API feature

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apim-cli#120]
**User story**
In some situations it might be useful to use the CLI to upgrade an API. This is basically the following function in the UI:

![image](https://user-images.githubusercontent.com/16292002/100357614-35245a80-2ff5-11eb-8e7a-2da1f110cfd9.png)

For that, the CLI will ask for two, the old and new API, and then perform the same steps as in the UI. It will basically call then:
`/proxies/upgrade/{id}` and `{id}` will be old API and `upgradeApiId` is the new API.

Also deprecation and retirement/retirementDate will be optionally supported by this command.

**Additional context**
See: http://apidocs.axway.com/swagger-ui/index.html?productname=apimanager&productversion=7.7.0&filename=api-manager-V_1_3-swagger.json#!/API_Proxy_Registration/post_proxies_upgrade_id

**Comment by davidgeiger** [comment]
I find it confusing to call this an "API upgrade" as it really just copies/upgrades app+org _access_ from one API to another. An _API upgrade_ includes much more: upgrade access, upgrade quotas, replace the previous API proxy, etc. So basically the entire process that the CLI performs today when publishing an API on the same URL. Would it be clearer to call it _upgrade-access_ (same as in the UI)?

**Comment by cwiechmann** [comment]
Hi @davidgeiger, you are right. I have renamed this command and released the change with version 1.3.4.
