### ISSUE TITLE
Is Routing to another API supported ?

### ISSUE THREAD

**Issue by gwandwingor** [Axway-API-Management-Plus/apim-cli#126]
**API-Manager CLI Version**
1.3.3

**API-Manager and Service-Pack Version**
7.7 Sept 20

**Question**
In the context of an Outbound per-method override, is it possible using apim-cli to route an incoming request to an other API, such as illustrated in the screenshot below ?

![image](https://user-images.githubusercontent.com/22820414/100754340-46050f80-33eb-11eb-9507-67b9f3fba763.png)

I didn't see it mentioned in the wiki. I'm guessing it is not possible as that would require to be able to uniquely identify the target API/method, which I guess might be tricky to implement without using ids.

**Comment by cwiechmann** [comment]
That is actually not supported and it requires substantial changes in the CLI. The requirement is described in the issue: #59. So, I'm going to close this question here.
