### ISSUE TITLE
Api Import vs Api Change

### ISSUE THREAD

**Issue by siemprepe** [Axway-API-Management-Plus/apim-cli#127]
**API-Manager CLI Version**
apim-cli 1.3.3

**API-Manager and Service-Pack Version**
7.7-20200930

**Question**
There is an api import and api change command.
We are migrating from swagger-promote where we only used import to create and change etc.
IS it neccesary with apim-cli to use import for create and change for actual changes to already created api's? Or can we safely use only import?

**Comment by gwandwingor** [comment]
Hi @siemprepe , 
We had to migrate from swagger-promote to apim-cli recently as well. To manage new or existing APIs, you can use import option only. It'll behave same way as swagger-promote did : create if new, update if existing.

**Comment by siemprepe** [comment]
@gwandwingor Thank you for the clear answer.

**Comment by cwiechmann** [comment]
Thank you the response @gwandwingor. Let me add, that the `change` command is just a convenience function to change aspects of an API, without the need to export/change and import it again.
