### ISSUE TITLE
[BUG] API custom properties are missing in API export

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#13]
**API-Mgr. CLI version**
1.0.0

**API-Manager and Service-Pack Version**
7.6.2 SP4

**Expected behavior**
As I am able to import API custom properties, I would expect to export the same.

**Actual behavior**
As orgAdmin if I export an API with apim api get -id ... -f json, the API proxy gets exported but without custom properties.

**Log-Output in Debug**

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by cwiechmann** [comment]
@jschaefer77, of course your expectation is correct. I'll investigate and let you know.

**Comment by cwiechmann** [comment]
I can confirm this issue.

**Comment by cwiechmann** [comment]
Improved API-Export integration test to include customProperties and implemented a fix for it. Will be fixed with 1.0.1
