### ISSUE TITLE
apim api publish command outputs misleading error messages

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#134]
**API-Mgr. CLI version**
1.3.3

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
As orgAdmin, I should be able to request publication (using apim api publish -name ...) for an unpublished API without any error messages in the CLI output.

**Actual behavior**
As orgAdmin, run "apim api publish -name ....." to request publication. The cli outputs misleading error message even if the request publication was successful.

**Log-Output in Debug**
1713   ERROR APIManagerAPIAdapter| Error updating API status. Received Status-Code: 200, Response: '[{"id":"e19f6be3-3423-454c-964d-5e1e02bc73c9","organizationId":"927e2993-fe46-47a5-bb0a-ea42867fd645","name":"...","loginName":"...","email":"...","role":"oadmin","enabled":true,"createdOn":1565247000302,"state":"approved","type":"internal","dn":"cn=...,o=test,ou=organizations,ou=APIPortal"}]'
1740   ERROR     APIResultHandler| Error publishing API: Petstore API 2
Done!

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by cwiechmann** [comment]
Hi @jschaefer77, Thanks for reporting this issue. Looks like the API-Manager sometimes also returns the status code 200 on a status-change request, which is okay, but was not expected by the CLI-Implementation. I changed this now like so:
https://github.com/Axway-API-Management-Plus/apim-cli/blob/59f2518776f8111e64383ce15c4810de7b42bc22/modules/apim-adapter/src/main/java/com/axway/apim/adapter/apis/APIManagerAPIAdapter.java#L645
