### ISSUE TITLE
When publish an API using the APIM CLI, events logs generated have null values for client, app & org

### ISSUE THREAD

**Issue by rohitthe** [Axway-API-Management-Plus/apim-cli#136]
API-Mgr. CLI version
1.3.2

API-Manager and Service-Pack Version
7.7_202005

Expected behavior
CLI should not assign the runtime ServiceContext values "null" for client,app & org fields for a particular transaction in API gateway event directory.

Actual behavior
CLI assign the runtime ServiceContext values "null" for client,app & org fields for a particular transaction in API gateway event directory.

Log-Output in Debug

When publish an API using the APIM CLI, events logs generated have null values for client, app & org in API gateway event directory :
and that's why information isn't displayed properly in Analytics.

{"type":"transaction", "time":1611745530596, "path":"/sno/devops/healthcheck/", "protocol":"https", "protocolSrc":"8065", "duration":2, "status":"success", "serviceContexts":[{"service":"SNO DEVOPS Healthcheck API", "monitor":true, "client":null, "org":null, "app":null, "method":"GET_Status", "status":"success", "duration":2}], "customMsgAtts":{}, "correlationId":"fa481160a33c361ba55e7783", "legs":[{"uri":"/sno/devops/healthcheck/", "status":200, "statustext":"OK", "method":"GET", "vhost":null, "wafStatus":0, "bytesSent":476, "bytesReceived":375, "remoteName":"10.196.162.134", "remoteAddr":"10.196.162.134", "localAddr":"10.196.162.150", "remotePort":"57764", "localPort":"8065", "sslsubject":null, "leg":0, "timestamp":1611745530594, "duration":2, "serviceName":"SNO DEVOPS Healthcheck API", "subject":"e6fc88e7-1b3a-466f-8779-83259b67196d", "operation":"GET_Status", "type":"http", "finalStatus":"Pass"}, {"uri":"/healthcheck/", "status":200, "statustext":"OK", "method":"GET", "vhost":null, "wafStatus":0, "bytesSent":345, "bytesReceived":406, "remoteName":"localhost", "remoteAddr":"127.0.0.1", "localAddr":"127.0.0.1", "remotePort":"8080", "localPort":"48760", "sslsubject":null, "leg":1, "timestamp":1611745530595, "duration":0, "serviceName":"SNO DEVOPS Healthcheck API", "subject":"e6fc88e7-1b3a-466f-8779-83259b67196d", "operation":"GET_Status", "type":"http", "finalStatus":null}]}

This is not the case when they deploy the same API Manually from API manager:

{"type":"transaction", "time":1611745590267, "path":"/sno/devops/manual/healthcheck/", "protocol":"https", "protocolSrc":"8065", "duration":2, "status":"success", "serviceContexts":[{"service":"SNO DEVOPS TEST2 Manuel", "monitor":true, "client":"e6fc88e7-1b3a-466f-8779-83259b67196d", "org":"API Management Group Core Team", "app":"SNO DEVOPS test", "method":"GET_Status", "status":"success", "duration":2}], "customMsgAtts":{}, "correlationId":"36491160c53c8b80f4f7f965", "legs":[{"uri":"/sno/devops/manual/healthcheck/", "status":200, "statustext":"OK", "method":"GET", "vhost":null, "wafStatus":0, "bytesSent":476, "bytesReceived":382, "remoteName":"10.196.162.134", "remoteAddr":"10.196.162.134", "localAddr":"10.196.162.150", "remotePort":"57784", "localPort":"8065", "sslsubject":null, "leg":0, "timestamp":1611745590265, "duration":2, "serviceName":"SNO DEVOPS TEST2 Manuel", "subject":"e6fc88e7-1b3a-466f-8779-83259b67196d", "operation":"GET_Status", "type":"http", "finalStatus":"Pass"}, {"uri":"/healthcheck/", "status":200, "statustext":"OK", "method":"GET", "vhost":null, "wafStatus":0, "bytesSent":345, "bytesReceived":406, "remoteName":"localhost", "remoteAddr":"127.0.0.1", "localAddr":"127.0.0.1", "remotePort":"8080", "localPort":"48778", "sslsubject":null, "leg":1, "timestamp":1611745590266, "duration":0, "serviceName":"SNO DEVOPS TEST2 Manuel", "subject":"e6fc88e7-1b3a-466f-8779-83259b67196d", "operation":"GET_Status", "type":"http", "finalStatus":null}]}

When we compare both APIs, the only difference is in the inbound security profile :

With APIM CLI (see api-export-apimcli.json) : "monitorSubject": " ${authentication.subject.id}"
Manually (see api-export.json) : "monitorSubject": "authentication.subject.id"

PFA the swagger files from the APIM CLI and from the API manager.

Apart from this ,In APIM CLI difference for that particular publication is that the API was unpublished first and then published again:

APIM CLI logs extract:
5536 INFO APIImportManager| Update API Strategy: Re-Publish API to apply changes
5544 INFO RepublishToUpdateAPI| Unpublish existing API for update: 'SNO DEVOPS TEST2 Manuel API' (ID: ed265fb4-d7b6-4558-b749-e97310e34a23)
6773 INFO UpdateExistingAPI| Update existing unpublished API: 'SNO DEVOPS TEST2 Manuel API' 1.0.0 (ID: ed265fb4-d7b6-4558-b749-e97310e34a23)
6773 INFO APIChangeState| Updating Frontend-API (Proxy) for the following properties: authenticationProfiles outboundProfiles inboundProfiles

**Comment by cwiechmann** [comment]
Thanks @gwandwingor providing a fix for it. Honestly I was experiencing the same working on the ELK-Solution, but so far not figured out the root cause. Let’s see if the ELK-Solution shows applications with the next CLI version.

**Comment by cwiechmann** [comment]
Just tried it now the Kibana dashboard shows the applications as expected:
![image](https://user-images.githubusercontent.com/16292002/106099385-df764680-613a-11eb-8d44-56a11b18b78e.png)

Thanks @rohitthe for reporting this issue.
