### ISSUE TITLE
Rename "api upgrade" to "api upgrade-access"

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apim-cli#139]
**User story**
I find it confusing to call this an "API upgrade" as it really just copies/upgrades app+org access from one API to another. An API upgrade includes much more: upgrade access, upgrade quotas, replace the previous API proxy, etc. So basically the entire process that the CLI performs today when publishing an API on the same URL. Would it be clearer to call it upgrade-access (same as in the UI)?

**Additional context**
See issue: https://github.com/Axway-API-Management-Plus/apim-cli/issues/120#issuecomment-735751744

**Comment by jschaefer77** [comment]
Hi @cwiechmann, are there any plans to support and command like "api upgrade", which does the steps like upgrade access, upgrade quotas, replace the previous API proxy ...?

**Comment by cwiechmann** [comment]
@jschaefer77, is this what you are looking for not what the `api import` command does?
