### ISSUE TITLE
Apply outbound parameter configs to all API methods at once

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#140]
**User story**
As an orgAdmin I would like to add additional outbound parameters to all methods of my API, but using only a single configuration. So instead of configuring each outbound parameter in a separate per method override, the same outbound parameter config should be applied to all API methods.

**Additional context**
API Manager UI unfortunately has the limitation that you cannot declare additional attributes for all API methods with only one configuration.  Instead you have to create multiple per method overrides and then you end up by adding the same additional attribute to each per method override.

**Comment by cwiechmann** [comment]
So your idea is to generate multiple method overrides based on a single config section in the config file?

**Comment by jschaefer77** [comment]
hi @cwiechmann, yes correct. e.g. I want to add an outbound header or query parameter to all of my methods. But instead of creating multiple per-method-overrides I just want to create a single config and with this APIM CLI will generate multiple per-method-overrides (for all methods of my API).

**Comment by cwiechmann** [comment]
I’m not sure, if this should be part of the config file as it would break the concept of desired vs. actual state.

What about a convenience method to do what you are looking for? 
For instance as part of the api change command?

**Comment by jschaefer77** [comment]
Hi @cwiechmann, I can understand your concerns. But I still think, I would be the best to have it available with the api import command. Otherwise ZDU upgrades are not as easy anymore, because I already have to run an api change command as a second step.

**Comment by cwiechmann** [comment]
I see no bandwidth to implement this feature, therefore I'm closing this issue now.
