### ISSUE TITLE
CLI communication with the API of APIM exposed in APIM

### ISSUE THREAD

**Issue by gdumond** [Axway-API-Management-Plus/apim-cli#141]
Jeremy is not able to reach directly the API Manager, the CLI is instanced in a Jenkin slave to communicate with the API Manager, he have no other solution than publishing the API of the API Manager in the API manager with a Virtual host protection.

The API exposition is normalyzed and look like;  https://intranet-api:443/fr/apim/v13/portal....
The API is configured without security.

The actual configuration file have only server and port parameter.

**Comment by cwiechmann** [comment]
This will be implemented as an additional parameter that can be set to anything and if set, it will be replace the default value set internally. Obviously the customer has to take care pointing to the same version number as the CLI is doing, which is currently 1.3. I'll make that clear in the documentation. 

As any other the parameters, the new one: `APIMANAGER_API_BASEBATH` can be set as a command-line parameter or the environment properties file.

Here is an example:
`APIMANAGER_API_BASEBATH=/fr/apim/v13/portal`
