### ISSUE TITLE
Export/Import app OAuth scopes

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#144]
Is it possible to export/import application's oauth scopes? I have one w/20 

thx

**Comment by cwiechmann** [comment]
Hi @emmanuel-galindo, This is currently not supported.

**Comment by cwiechmann** [comment]
I have added support to export Application-Scopes like so:
```json
  "appScopes" : [ {
    "uriprefix" : "resource.WRITE",
    "scopes" : [ "resource.WRITE" ],
    "scope" : "resource.WRITE",
    "enabled" : true,
    "isDefault" : true
  }, {
    "uriprefix" : "openid",
    "scopes" : [ "openid" ],
    "scope" : "openid",
    "enabled" : true,
    "isDefault" : true
  }, {
    "uriprefix" : "resource.READ",
    "scopes" : [ "resource.READ" ],
    "scope" : "resource.READ",
    "enabled" : true,
    "isDefault" : true
  } ]
```
However, the export format needs to be improved anyway. See issues: #145 and #146. And it has to be assured, that the import of appScopes works as expected.

**Comment by emmanuel-galindo** [comment]
cool, so this is ready?? what is the easiest way to update my apim-cli installation to test this feature?
