### ISSUE TITLE
Cannot import API from API metadata exported via apimcli before

### ISSUE THREAD

**Issue by rekies** [Axway-API-Management-Plus/apim-cli#149]
**API-Mgr. CLI version**
API-Manager CLI: 1.3.5  (new download today)
Platform: Ubuntu 20.04 headless on WSL2, Java 8

**API-Manager and Service-Pack Version**
API-Manager V7.7.20200330, no SP

**Expected behavior**
I copied the exported API folder to a new one. Changed the directory name as well as the API-Name and base path with api-config.json (name and path attributes) and tried to re-import the API as a new one. Purpose is to setup a test environment.

**Actual behavior**
A part of the backend API seems to be created. BE API is not fully created. Import stops with exception below.

The name of the API contains spaces. The resulting file name for the exported Swagger files is keeping this. But during import the reference to a file with spaces seems to cause the problem. 

**Log-Output in Debug**
Console Trace:
169    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/home/axway/zdu-test/sample1/Petstore-Sample-API HTTP.json' (absolute path)
204    INFO      APISpecification| Used the configured backendBasepath: 'https://petstore.swagger.io' to adjust the Swagger definition.
554    INFO  IImportConfigAdapter| Handling configured client-applications.
765    INFO  IImportConfigAdapter| Found existing application: 'Petstore Test App' (null) based on given name 'Petstore Test App'
843    INFO      APIImportManager| No existing API found, creating new!
1488   ERROR APIManagerAPIAdapter| Error importing Swagger-Definition. Received Status-Code: 500, Response: '{"errors":[{"code":500,"message":"Failed to import API definition. Reason: Internal server error"}]}'
1495   ERROR         APIImportApp| Can't import definition / Create BE-API.
com.axway.apim.lib.errorHandling.AppException: Can't import definition / Create BE-API.
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.importBackendAPI(APIManagerAPIAdapter.java:726)
        at com.axway.apim.apiimport.actions.CreateNewAPI.execute(CreateNewAPI.java:40)
        at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:49)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:103)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Can't read Swagger-File.
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.importFromSwagger(APIManagerAPIAdapter.java:808)
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.importBackendAPI(APIManagerAPIAdapter.java:718)
        ... 10 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Can't import Swagger-definition / Create BE-API.
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.importFromSwagger(APIManagerAPIAdapter.java:803)
        ... 11 more

**Test case sample**
As stated above, I exported an API I had created via API-Manager Web-UI before. The given API was imported via URL to Swagger document from https://petstore.swagger.io/v2/swagger.json. Here you get two API's for HTTP and HTTPS use. I only used the HTTP version and configured it for HTTPS on API-Manager with HTTPS on petstore.swagger.io (imported the certs).
After export and changed API name and base path I got the error.

**Comment by cwiechmann** [comment]
Hi @rekies, I tried to reproduce this problem on the API-Management Reference environment. I followed all the steps you described, but it is working as expected.

```
[axway@api-env apim-cli-1.3.5]$ ./scripts/apim.sh api import -s api-env -c /home/axway/myapi/v2-petstore/api-config.json

----------------------------------------------------------------------------------------
API-Manager CLI: 1.3.5
                                                                        
To report issues or get help, please visit: 
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - I M P O R T (1.3.5)
----------------------------------------------------------------------------------------
0      INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200730) on: https://api-env:8075
672    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/home/axway/myapi/v2-petstore/Petstore HTTP.json' (absolute path)
829    INFO      APISpecification| Used the configured backendBasepath: 'http://petstore.swagger.io' to adjust the Swagger definition.
2642   INFO  APIManagerAPIAdapter| Found existing API on path: '/v2/petstore' (unpublished) (ID: 'b58be407-aa59-496c-8fce-3e1c2cdca88b'
2644   INFO      APISpecification| Detected API-Definition-Filesizes: API-Manager: 13843 vs. Import: 13835
2647   INFO      APIImportManager| Recognized the following changes. Potentially Breaking: [apiDefinition, securityProfiles] plus Non-Breaking: []
2647   INFO      APIImportManager| Update API Strategy: Re-Create API as changes can't be applied to existing API.
2648   INFO   RecreateToUpdateAPI| Create new API to update existing: 'Petstore HTTP' (ID: b58be407-aa59-496c-8fce-3e1c2cdca88b)
2932   INFO          CreateNewAPI| Create unpublished API: 'Petstore HTTP' 1.0.5 based on Swagger 2.0 specification.
3359   INFO          CreateNewAPI| Successfully created unpublished API: 'Petstore HTTP' 1.0.5 (ID: 1b8a1da9-45bc-4a4c-915d-78b37ba27c67)
3360   INFO   RecreateToUpdateAPI| New API successfuly created. Going to delete old API: 'Petstore HTTP' 1.0.5 (ID: b58be407-aa59-496c-8fce-3e1c2cdca88b)
3482   INFO  APIManagerAPIAdapter| API: Petstore HTTP 1.0.5 (b58be407-aa59-496c-8fce-3e1c2cdca88b) successfully deleted
```

And this the config file that has been exported:
```
[axway@api-env apim-cli-1.3.5]$ cat /home/axway/myapi/v2-petstore/api-config.json
{
  "name" : "Petstore HTTP",
  "path" : "/v2/petstore",
  "state" : "unpublished",
  "version" : "1.0.5",
  "organization" : "API Development",
  "apiDefinition" : "Petstore HTTP.json",
  "backendBasepath" : "http://petstore.swagger.io",
  "clientOrganizations" : [ "API Development" ]
```
Perhaps it was a temporary problem, as the root cause seems not reading the Swagger-File, instead the API-Manager returns the error code: 500 Internal server error:
```json
{"errors":[{"code":500,"message":"Failed to import API definition. Reason: Internal server error"}]}
```
If you still can reproduce this problem, it would be good to know, what is logged in the API-Manager traces (perhaps enabling Debug for port;: 8075).
