### ISSUE TITLE
Expose DEFAULT_API_BASEPATH as env variable

### ISSUE THREAD

**Issue by tcheronneau** [Axway-API-Management-Plus/apim-cli#154]
**User story**
We would want to use the api path v1.4 instead of v1.3.

**Additional context**
I've found in the code where it must belong : 
```
static String APIM_CLI_HOME = "AXWAY_APIM_CLI_HOME";
static String DEFAULT_API_BASEPATH = "/api/portal/v1.3";
```
I think APIM_CLI_HOME can be override by env var maybe it could be interesting to do the same for this one.

**Comment by tcheronneau** [comment]
My bad it's already possible to update with option -apiBasepath.

**Comment by cwiechmann** [comment]
Perhaps the name of the parameter was not the best choice and very likely I'll rename it and deprecate the old name. But yes, it should work with that parameter. But keep in mind, that the CLI is not tested with the REST-API Version 1.4.

**Comment by mateustanaka** [comment]
@cwiechmann @tcheronneau is this parameter **-apiBasepath** still working on APIM-CLI version 1.14.3?
I need to use the api path v1.3 instead of v1.4 but is not working.

https://github.com/Axway-API-Management-Plus/apim-cli/issues/453
