### ISSUE TITLE
Error importing frontend api with virtual host

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apim-cli#155]
**API-Mgr. CLI version**

1.3.5

**API-Manager and Service-Pack Version**

7.6.2 SP2

**Expected behavior**

Consider this simple json config file for importing a rest api on api manager.

{
  "organization": "API Development",
  "apiDefinition": "https://petstore.swagger.io/v2/swagger.json",
  "backendBasepath": "http://localhost:8103",
  "clientOrganizations": [],
  "name": "PetStoreVHost",
  "version": "1.0",
  "path": "/test/petstore/v1",
  "vhost": "pippo:8443",
  "state": "published"
}

I expected this simple api would be imported successfully

**Actual behavior**

an error occurs and the api cannot be imported.

**Log-Output in Debug**

0      DEBUG nvironmentProperties| Loaded environment properties from file: env.properties
3      DEBUG nvironmentProperties| Loaded environment properties from file: env.istanzasec.properties
133    DEBUG nvironmentProperties| Property: 'returnCodeMapping' not found.
137    DEBUG    APIManagerAdapter| Logging in with User: 'apiadmin'
1839   DEBUG nvironmentProperties| Property: 'clearCache' not found.
1840   DEBUG nvironmentProperties| Property: 'clearCache' not found.
1842   DEBUG nvironmentProperties| Property: 'clearCache' not found.
1848   DEBUG nvironmentProperties| Property: 'clearCache' not found.
1849   DEBUG nvironmentProperties| Property: 'clearCache' not found.
1852   DEBUG nvironmentProperties| Property: 'clearCache' not found.
1852   DEBUG nvironmentProperties| Property: 'clearCache' not found.
1857   DEBUG nvironmentProperties| Property: 'clearCache' not found.
1859   DEBUG nvironmentProperties| Property: 'clearCache' not found.
1860   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.6.2 SP2) on: https://192.168.2.43:8075
1916   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=API Development, id=null]
2576   DEBUG IImportConfigAdapter| Current path=D:\Git\BancoBPM\RilasciPartizioniImola\svil\istanzasec\manager
2577   DEBUG IImportConfigAdapter| Reading API Definition from configuration file
2581   INFO  IImportConfigAdapter| Loading API-Definition from: https://petstore.swagger.io/v2/swagger.json
2585   DEBUG IImportConfigAdapter| NO javax.net.ssl.keyStore property.
2585   DEBUG IImportConfigAdapter| https protocols: TLSv1.2
3342   DEBUG SpecificationFactory| Handle API-Specification: '{"swagger":"2.0","info":{"description":"This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http:......', apiDefinitionFile: 'https://petstore.swagger.io/v2/swagger.json'
3363   DEBUG     APISpecification| Replacing existing host: 'petstore.swagger.io' in Swagger-File to 'localhost:8103' based on configured backendBasepath: 'http://localhost:8103'
3370   DEBUG     APISpecification| Replacing existing protocol(s): '["https","http"]' with 'http' according to configured backendBasePath: 'http://localhost:8103'.
3370   INFO      APISpecification| Used the configured backendBasepath: 'http://localhost:8103' to adjust the Swagger definition.
3402   DEBUG APIManagerAPIAdapter| Sending request to find existing APIs: https://192.168.2.43:8075/api/portal/v1.3/proxies
4251   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=null, id=5f52bce6-4ef5-4a20-ac6a-bc4d74da6e71]
4540   DEBUG APIManagerAPIAdapter| No existing API found based on filter: [apiPath=/test/petstore/v1 vHost=pippo:8443 filter=APIFilter [id=null, name=null, vhost=pippo:8443, apiPath=/test/petstore/v1, queryStringVersion=null, state=null, deprecated=false, retired=false, loadBackendAPI=false]]
4541   DEBUG       APIChangeState| No existing API found. Creating  complete new API
4543   INFO      APIImportManager| No existing API found, creating new!
4543   DEBUG APIManagerAPIAdapter| Import backend API: PetStoreVHost based on Swagger 2.0 specification.
5316   INFO          CreateNewAPI| Create published API: 'PetStoreVHost' 1.0 based on Swagger 2.0 specification.
5316   DEBUG APIManagerAPIAdapter| Create Front-End API: 'PetStoreVHost' (API-Proxy)
6068   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=null, id=c30255a3-bc37-4c3b-a155-42247decafd0]
6909   DEBUG APIManagerAPIAdapter| Updating API-Proxy
7776   ERROR APIManagerAPIAdapter| Error updating API-Proxy. Response-Code: 403. Got response: '{"errors":[{"code":403,"message":"Cannot modify a protected field"}]}'
7777   DEBUG APIManagerAPIAdapter| Request sent:{"caCerts":[],"descriptionType":"original","securityProfiles":[{"name":"_default","isDefault":true,"devices":[{"name":"Pass Through","type":"passThrough","order":0,"properties":{"subjectIdFieldName":"Pass Through","removeCredentialsOnSuccess":"true"}}]}],"authenticationProfiles":[{"name":"_default","isDefault":true,"parameters":{},"type":"none"}],"tags":{},"outboundProfiles":{"_default":{"routeType":"proxy","authenticationProfile":"_default"}},"serviceProfiles":{"_default":{"apiId":"78442ee2-fd6f-4be0-91f9-9f53a68ab758","basePath":"http://localhost:8103"}},"inboundProfiles":{"_default":{"monitorAPI":true,"monitorSubject":"authentication.subject.id","securityProfile":"_default","corsProfile":"_default"}},"corsProfiles":[{"name":"_default","isDefault":true,"origins":["*"],"allowedHeaders":[],"exposedHeaders":["X-CorrelationID"],"supportCredentials":false,"maxAgeSeconds":"0"}],"path":"/test/petstore/v1","state":"unpublished","version":"1.0","vhost":"pippo:8443","name":"PetStoreVHost","summary":"","createdOn":1614788294804,"createdBy":"e575d3d7-f1b1-4c4d-a4ea-609920b612b2","id":"51c10beb-dded-45a0-8284-c0de6841db11","apiId":"78442ee2-fd6f-4be0-91f9-9f53a68ab758","deprecated":"false","retirementDate":0,"organizationId":"c30255a3-bc37-4c3b-a155-42247decafd0"}
7779   INFO        RollbackAction| Rollback FE-API: 'PetStoreVHost' (ID: '51c10beb-dded-45a0-8284-c0de6841db11' / State: 'unpublished')
7780   DEBUG APIManagerAPIAdapter| Sending request to find existing APIs: https://192.168.2.43:8075/api/portal/v1.3/proxies/51c10beb-dded-45a0-8284-c0de6841db11
8607   DEBUG APIManagerAPIAdapter| Found: 1 exposed API(s)
8609   DEBUG     APIStatusManager| Desired and actual status equal. No need to update status!
8610   DEBUG APIManagerAPIAdapter| Deleting API-Proxy
9477   INFO  APIManagerAPIAdapter| API: PetStoreVHost 1.0.5 (51c10beb-dded-45a0-8284-c0de6841db11) successfully deleted
9478   DEBUG APIManagerAPIAdapter| Deleting API-Proxy
9649   INFO       RollbackHandler| Rolled back: '[Frontend-API: false, Backend-API: false]'
9650   ERROR         APIImportApp| Cannot update API-Proxy.
com.axway.apim.lib.errorHandling.AppException: Cannot update API-Proxy.
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.updateAPIProxy(APIManagerAPIAdapter.java:556)
        at com.axway.apim.apiimport.actions.CreateNewAPI.execute(CreateNewAPI.java:57)
        at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:49)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:103)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Error updating API-Proxy. Response-Code: 403
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.updateAPIProxy(APIManagerAPIAdapter.java:551)
        ... 10 more

**Test case sample**
> Please describe the steps you have done to replicate the issue

 just lunch apim-cli with **api import -c <file>** args

the <file> contains this definition

{
  "organization": "API Development",
  "apiDefinition": "https://petstore.swagger.io/v2/swagger.json",
  "backendBasepath": "http://localhost:8103",
  "clientOrganizations": [],
  "name": "PetStoreVHost",
  "version": "1.0",
  "path": "/test/petstore/v1",
  "vhost": "pippo:8443",
  "state": "published"
}

in old swagger-promote tool this error doesn't occur.

**Comment by gcornacchia** [comment]
I forgot to mention that the problem seems to be the handling of vhost field in config file

**Comment by cwiechmann** [comment]
I did run the same example on a 7.7-July release and it's working as expected:
![image](https://user-images.githubusercontent.com/16292002/109874276-3063e800-7c6f-11eb-9b9f-76e5da1c4909.png)

Can you please update to the latest service-pack SP5 for your API-Manager. The following has been changed in SP3:
![image](https://user-images.githubusercontent.com/16292002/109874796-e29baf80-7c6f-11eb-85b3-1673a7b72031.png)

**Comment by cwiechmann** [comment]
Closing this issue. Feel free to re-open if you need further information.
