### ISSUE TITLE
apim.sh: Fails if CWD has a space

### ISSUE THREAD

**Issue by dim0x69** [Axway-API-Management-Plus/apim-cli#160]
**API-Mgr. CLI version**: 1.3.6

apim.sh changes to the CWD before executing the jar. If the CWD has a empty space, apim.sh can't change to it. (Missing quotation marks in apim.sh)

https://github.com/Axway-API-Management-Plus/apim-cli/blob/develop/modules/apim-cli/assembly/scripts/apim.sh#L35

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @dim0x69. I implemented this fix as you suggested.
