### ISSUE TITLE
Streams not closed bring to a FileSystemException

### ISSUE THREAD

**Issue by florentlh** [Axway-API-Management-Plus/apim-cli#161]
**API-Mgr. CLI version**
> Please make sure to use the latest available version before reporting a bug.

1.3.6

**API-Manager and Service-Pack Version**

 7.7.20200930

**Expected behavior**

I am using directly the libraries from my java application and i don't use directly the tool as a CLI tool.

In the class `APIImportConfigAdapter`, two InputStream are open but not closed.
This means i'm not able to delete temp file (swagger + image) in my JVM, because the stream is still opened.

With CLI, it is not a big trouble because, when the JVM stopped, the streams are released.

The issue happens in this section:

```
	private byte[] getAPIDefinitionContent() throws AppException {
		try {
			InputStream stream = getAPIDefinitionAsStream();
			Reader reader = new InputStreamReader(stream,StandardCharsets.UTF_8);
			return IOUtils.toByteArray(reader,StandardCharsets.UTF_8);
		} catch (IOException e) {
			throw new AppException("Can't read API-Definition from file", ErrorCode.CANT_READ_API_DEFINITION_FILE, e);
		}
	}
```

Than can be fixed by:

```
	private byte[] getAPIDefinitionContent() throws AppException {
		try(InputStream stream = getAPIDefinitionAsStream()) {
			Reader reader = new InputStreamReader(stream,StandardCharsets.UTF_8);
			return IOUtils.toByteArray(reader,StandardCharsets.UTF_8);
		} catch (IOException e) {
			throw new AppException("Can't read API-Definition from file", ErrorCode.CANT_READ_API_DEFINITION_FILE, e);
		}
	}
```

And in this section: `APIImportConfigAdapter#addImageContent`

```
InputStream is = this.getClass().getResourceAsStream(importApi.getImage().getFilename());
				if(file.exists()) {
					LOG.debug("Loading image from: '"+file.getCanonicalFile()+"'");
					importApi.getImage().setImageContent(IOUtils.toByteArray(new FileInputStream(file)));
					return importApi;
				} else if(is!=null) {
					LOG.debug("Trying to load image from classpath");
					// Try to read it from classpath
					importApi.getImage().setImageContent(IOUtils.toByteArray(is));
					return importApi;
				} else {
					throw new AppException("Image not found in filesystem ('"+file+"') or Classpath.", ErrorCode.UNXPECTED_ERROR);
				}
```

That can be fixed by:
```
				try(InputStream is = this.getClass().getResourceAsStream(importApi.getImage().getFilename())) {
					if (file.exists()) {
						LOG.debug("Loading image from: '" + file.getCanonicalFile() + "'");
						importApi.getImage().setImageContent(IOUtils.toByteArray(new FileInputStream(file)));
						return importApi;
					} else if (is != null) {
						LOG.debug("Trying to load image from classpath");
						// Try to read it from classpath
						importApi.getImage().setImageContent(IOUtils.toByteArray(is));
						return importApi;
					} else {
						throw new AppException("Image not found in filesystem ('" + file + "') or Classpath.",
								ErrorCode.UNXPECTED_ERROR);
					}
				}
```

Thanks

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @florentlh. I guess you missed the finally block in your "...fixed by" code samples, as they look like the original. Can you confirm?

It would be also interesting to know, the use-case you are trying to solve by using the library directly. Perhaps there is room for improvement, as many people are using it with the CLI only.

**Comment by florentlh** [comment]
Hello,

I've used the try-with-resources statement, that exists since java 8: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

```
		InputStream is = null;
		try {
			is = new BufferedInputStream(...);
			...
		}
		finally {
			if(is ! = null) {
				is.close();;
			}
		}
```

Is similar to this: 
```
		try(InputStream is = new BufferedInputStream(...)) {
			...
		}
```

`InputStream` implementes `Autoclosable`, and the method `close()` is automatically called with this syntax at the end of the `try` statement.


> It would be also interesting to know, the use-case you are trying to solve by using the library directly. 

Globally, the use case is this one.
We have a process to onboard automatically some providers, that want to deploy API.
A workflow is started and a review has to be done by a team manually (checking the swagger, checking front/back URL, security config and so one), and when the team validate the onboarding, the API is deployed automatically for this organization by the workflow (we're using an java stack for the workflow engine)

I know using the library directly can bring to other issues (especially due to multi-threading (not really a problem with the CLI)), but it was a good start for us to work with this library.

**Comment by cwiechmann** [comment]
Thanks for the recommendation @florentlh . I implemented a fix as you suggested plus some other small changes. As version 1.3.6 has just been released, it is more likely to get a new release in about 4-6 weeks. Do you need something earlier or can you continue using a SNAPSHOT-Version you build yourself?

Let me know, if you find anything else in the Java-API that makes you life hard. You know, the interface it's not really optimized, but I'm happy to do so to make your adoption easier.

**Comment by florentlh** [comment]
Thanks, for now, we still are in development phase, we can wait for the next release
