### ISSUE TITLE
Allow override per method 

### ISSUE THREAD

**Issue by tcheronneau** [Axway-API-Management-Plus/apim-cli#162]
**User story**
We have some specific tags that we would want to apply to some of our API. 
Those tags are per method override and from what I've seen so far it's not possible to add this kind of thing to the API definition. 
I'm not sure it's really something standard but in our context it allows us to override without modifying the swagger. 

**Additional context**
The idea would be to add in the API definition a way to allow tag override per method. 
I think this can be done through the proxies/{id}/operations API. 

Also currently the apim cli does not re-create this kind of tag if it was previously there when you redeploy the API.

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @tcheronneau. You are referring to this possibility within the Frontend-API?:
![image](https://user-images.githubusercontent.com/16292002/113700289-f6a35880-96d6-11eb-8fc8-027c51d6250b.png)

At the very bottom:
![image](https://user-images.githubusercontent.com/16292002/113700468-2bafab00-96d7-11eb-979b-4d7a8aa5754a.png)

**Comment by tcheronneau** [comment]
Hi @cwiechmann yes exactly that part. 
Again I don't know if it's something relevant or not but it could be useful for us at least.

**Comment by cwiechmann** [comment]
@tcheronneau, I think it's relevant and the APIM-CLI is supposed to support the entire function-set of the API-Manager. 

I did some research and as of now, the API-Methods were not handled by the APIM-CLI, besides security overrides in the FE-Proxy and Quota-Management. 

There are a few more things to manage per method/operation:
- summary
- descriptionType
- descriptionManual, descriptionMarkdown, descriptionUrl
- and tags

I propose the following structure in the API-Configuration to support method level overrides:
```json
{
   "name":"Samples MethodLvl HTTPBasicAuthN AddParam OneMethod",
   "path":"/sample/methodlvl/httpbasic/param/one/method/api/v1",
   "state":"published",
   "version":"1.0.7",
   "organization":"API Development",
   "apiMethods":{
      "uploadFile":{
         "summary":"uploads an image",
         "descriptionType":"markdown",
         "descriptionMarkdown":"A markdown description for the method",
         "tags": {
            "tag1": [
                "tagValue1"
            ]
         }
      },
      "getOrderById":{
        "tags": {
            "tag1": [
                "tagValue1"
            ],
            "tag2": [
                "tagValue2",
                "tagValue2.1"
            ]
        }
      }
   }
}
```

__For the API-Import:__
The APIM-CLI, when reading the API-Configuration would check, if apiMethods are given and only then, it would read the operations for the actual API. Then it performs the Desired- vs. Actual-State compare, etc.
- it would fail, if the operationId (e.g. `getOrderById`) is invalid
- all properties of the apiMethod are optional (e.g. only giving tags)
When apiMethods are changed between Actual & Desired state, the API will be unpublished, changed and republished.

__For the API-Export:__
- it would get the operations for the API(s) to be exported from the API-Manager
- then it checks:
- are there any tags, is the description type other than original and only then the apiMethod will appear in the exported API-Config.
The missing piece, how to handle a modified API-Method-Summary? I don't want to export all API-Operations, as quite often they are not changed. Perhaps, indicating the summary as not supported and to be maintained in the API-Specification.

**Comment by tcheronneau** [comment]
@cwiechmann it seems really promising indeed. 
On our side we would only use the tag part but I understand the will to have it all. 
But I think that if it's something that is overcomplicated you should put it aside for now and come to it if the need is back for someone ?

**Comment by cwiechmann** [comment]
Hi @pgcastro, Mid- or Long-Term we don't have the capacity to implement this feature. I could pin this issue, but unfortunately it would stay open for a very long time.

**Comment by rathnapandi** [comment]
@tcheronneau 

I have implemented the feature in develop branch. 

- Export API methods data from API manger, It only works for JSON export
   apim api get -s prod -name "Petstore 3" --output json -exportMethods
- When we import API, it will compare the config file vs API in API manger, if additional tags or change in tags / description change, it will update API manger. 

Could you please verify the below binary?
[axway-apimcli-1.12.4-SNAPSHOT.tar.gz](https://github.com/Axway-API-Management-Plus/apim-cli/files/9365356/axway-apimcli-1.12.4-SNAPSHOT.tar.gz)

**Comment by saper** [comment]
@rathnapandi Tried to build the develop as of 27198e50bccb78422039b5affd60c0e94d08fedc and the test fail like this

```
Tests run: 168, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 2.563 sec <<< FAILURE! - in TestSuite
testPropertyFileWithoutStage(com.axway.lib.CoreCLIOptionsTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected [https://localhost:8075] but found [https://null:8075]
        at com.axway.lib.CoreCLIOptionsTest.testPropertyFileWithoutStage(CoreCLIOptionsTest.java:67)

testProxyParametersFromStage(com.axway.lib.CoreCLIOptionsTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: expected [proxyHost] but found [null]
        at com.axway.lib.CoreCLIOptionsTest.testProxyParametersFromStage(CoreCLIOptionsTest.java:77)

testStagePropertyFiles(com.axway.lib.CoreCLIOptionsTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: expected [yetanotherUser] but found [null]
        at com.axway.lib.CoreCLIOptionsTest.testStagePropertyFiles(CoreCLIOptionsTest.java:55)


Results :

Failed tests:
  CoreCLIOptionsTest.testPropertyFileWithoutStage:67 expected [https://localhost:8075] but found [https://null:8075]
  CoreCLIOptionsTest.testProxyParametersFromStage:77 expected [proxyHost] but found [null]
  CoreCLIOptionsTest.testStagePropertyFiles:55 expected [yetanotherUser] but found [null]

Tests run: 168, Failures: 3, Errors: 0, Skipped: 0

```

**Comment by rathnapandi** [comment]
Fixed
