### ISSUE TITLE
Streams not closed bring to a FileSystemException

### ISSUE THREAD

**Issue by florentlh** [Axway-API-Management-Plus/apim-cli#165]
**API-Mgr. CLI version**

1.3.6

**API-Manager and Service-Pack Version**

7.7.20200930

**Expected behavior**

Similar to this issue: https://github.com/Axway-API-Management-Plus/apim-cli/issues/161

But related to the certificate management.
In the class: *APIImportConfigAdapter*, method: *completeCaCerts*

A stream is open, but not closed:
```
JsonNode certInfo = APIManagerAdapter.getCertInfo(getInputStreamForCertFile(cert), cert);
```

Can be replaced by something like:
```
					try(InputStream is = getInputStreamForCertFile(cert)) {
						JsonNode certInfo = APIManagerAdapter
								.getCertInfo(is, cert);
						CaCert completedCert = mapper.readValue(certInfo.get(0).toString(), CaCert.class);
						completedCaCerts.add(completedCert);
					} catch (Exception e) {
						throw new AppException("Can't initialize given certificate.", ErrorCode.CANT_READ_CONFIG_FILE, e);
					}
```

**Actual behavior**

Stream is not closed

**Log-Output in Debug**

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by cwiechmann** [comment]
Thanks for reporting @florentlh. I have implemented your suggestion. 

However, I'm concerned about your use case to have a server application and the ErrorState singleton. I think this needs to be refactored. It was very likely not best decision to handle errors that way. 
You may be okay with the way it works right now, when you are not calling the library in parallel and delete the singleton each time you call it.
