### ISSUE TITLE
Resolve environment variable in a property value

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#166]
**API-Manager CLI Version**
1.3.6

**API-Manager and Service-Pack Version**
7.7.20200730

**Question**
I would like to use environment variables in env property files, so that I can store all env properties files in my source control system. Would that work? Environment variables are used for username and password of API Manager.

I know I could store username and password inside of the env.properties and use a git ignore for that specific file.

**What I've tried so far**
Tried to resolve  with ${VAR-NAME} and %VAR-NAME%. Both did not work.

**Additional information**

**Comment by cwiechmann** [comment]
Hi @jschaefer77, this is actually not supported. But I consider this as very helpful and it should be easy to implement, as the responsible code is pretty well encapsulated.

**Comment by cwiechmann** [comment]
That was easy and I implemented support for that. With version 1.3.7 you can use OS-Environment variables in your environment.property files like so:
```
myVariable=${MY_OS_VARIABLE}
anothotherVariable=Static and ${VARIABLE}
```
