### ISSUE TITLE
vhost="" will create a new API each time

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apim-cli#169]
v 1.3.5 of apim-cli

when you have an empty vhost, apim-cli will create each time a new api.
This seems to be because apim-cli is looking for vhost="" instead of vhost=null.
Importing an API with vhost="" will create in API Manager an API with vhost=null (we can see it by exporting the API in a .dat format).

each execution of the import, you will get this log : 
 No existing API found based on filter: [apiPath=/healthchek vHost= filter=APIFilter [id=null, name=null, **vhost=,** apiPath=/healthchek, queryStringVersion=null, state=null, deprecated=false, retired=false, loadBackendAPI=false]]
...
...
CreateNewAPI| Successfully created published API

You can use a simple configuration file such as : 
{
        "name": "Sample Minimal API",
        "path": "/sample/minimal/api/v1",
        "state": "unpublished",
        "version": "1.0.0",
        "organization": "API Development",
        **"vhost" : ""**
}

**Comment by cwiechmann** [comment]
Thanks @Rennaud for reporting this. With version 1.3.8 a given empty `vhost=""` will be considered as NOT given.
