### ISSUE TITLE
apim api publish resets vhost to configured Default virtual host

### ISSUE THREAD

**Issue by tcheronneau** [Axway-API-Management-Plus/apim-cli#170]
**API-Mgr. CLI version**
> Please make sure to use the latest available version before reporting a bug.

v1.3.7
**API-Manager and Service-Pack Version**

7.7.20200930

**Expected behavior**
Publish API with the good vhost. 

**Actual behavior**
Publish API with vhost as IP. 

**Log-Output in Debug**

**Test case sample**
> Please describe the steps you have done to replicate the issue

Publish some API using : `apim api -c api.json -a swagger.json`
Then after checking publish those with : `apim api publish`

The vhost defined in the api config (example.domain.tld) become an IP after publishing.

**Comment by cwiechmann** [comment]
Hi @tcheronneau, you are right. I checked verified the issue and the API turns back to the configured Default-Virtual-Host. Thanks for reporting this!
