### ISSUE TITLE
 Is it possible to use apim-cli with API Manager 7.5.3 ?

### ISSUE THREAD

**Issue by Boubacar-Diarra** [Axway-API-Management-Plus/apim-cli#171]
**API-Manager CLI Version**
1.3.7

**API-Manager and Service-Pack Version**
7.5.3 SP13

**Question**
Hello. In the documentation, I saw that the version 7.5.3 of API Manager is not covered by the tests. But is it still possible to use the apim-cli tool on this version?

**Comment by cwiechmann** [comment]
Hi @Boubacar-Diarra, I can tell, that the CLI does not check the version and will hard stop, if the version is unsupported. So, you may give it a try and most of the things will work. But if you run into issues related to the API-Manager version 7.5.3, the CLI will not changed.

**Comment by Boubacar-Diarra** [comment]
Thanks for your feedback.
Indeed I tried and the commands are executed.
One last question. The import and export procedure take a lot of time (5 to 15 min). I would like to know if this was normal? Thank you in advance.

**Comment by cwiechmann** [comment]
No that is not normal. How many APIs, Apps, Orgs do you ap. have in your platform?

**Comment by Boubacar-Diarra** [comment]
There are around 200 APIs, 200 Apps, and 25 Orgs.

**Comment by cwiechmann** [comment]
Not that many, but it might already cause the slowness. 
The CLI is based on the API-Manager REST-APIs and if that REST-APIs are slow, the also the APIM-CLI is slow. There are made a number of improvements to boost the API-Performance, but I'm not sure they have been made for version 7.5.3 as well.

I assume, when using the UI you also experience some slowness.

> The import and export procedure take a lot of time (5 to 15 min)

Is this to export / import all APIs?

**Comment by Boubacar-Diarra** [comment]
No, it's just for import / export of a single API

**Comment by cwiechmann** [comment]
That should not take any longer than 5-10 seconds and not minutes.

**Comment by Boubacar-Diarra** [comment]
Okay. Thank you very much for your feedback
