### ISSUE TITLE
Is it possible to use APIExportApp from maven as with APIImportApp? 

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#174]
**API-Manager CLI Version**
1.3.7

**API-Manager and Service-Pack Version**
7.7 March

**Question**
Is it possible to use APIExportApp from maven as with APIImportApp? 

**What I've tried so far**
I tried but the main class of that export class seems to be execuet grantAccess() and not exportApi() 
Not sure how to execute that method from maven

**Comment by cwiechmann** [comment]
You are right, I missed that use case. I need to think about how to improve it.

For now, you may use the CLI main class:
`com.axway.apim.cli. APIManagerCLI`
This class requires the normal parameters such as `api Export` and based on that the module is called.
You have to make sure to add the core CLI as a dependency.
https://mvnrepository.com/artifact/com.github.axway-api-management-plus.apim-cli/apimcli-tool/1.3.7

**Comment by emmanuel-galindo** [comment]
ok that works @cwiechmann  .. thanks!
