### ISSUE TITLE
next version 1.3.8?

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apim-cli#177]
Hi @cwiechmann,
when are you supposing to release the 1.3.8 version?

**Comment by cwiechmann** [comment]
I'll release version 1.3.8 end of this week.

**Comment by gcornacchia** [comment]
news on the release?

**Comment by cwiechmann** [comment]
Hi @gcornacchia, unfortunately an integration test concerning the password changes fails on the test-with-7.7-20200331 and I had no time, to work on this. I try to release the new version as soon as possible.
