### ISSUE TITLE
Update RemoteHost lost CreatedBy & CreatedOn

### ISSUE THREAD

**Issue by archi73** [Axway-API-Management-Plus/apim-cli#180]
**API-Mgr. CLI version**
APIM-CLI 1.3.8

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
Update a remote host configuration

```
Created on: 18 June 2021, 15:44
Created by: My user
```

**Actual behavior**
Update a remote host configuration but lost the "createdOn" and "createdBy" fields when updating 

```
Created on: NaN undefined 0NaN, NaN:NaN
Created by: API Manager Administrator
```
When clicking on API Manager Administrator, a window is displayed : "Not Found. A user with the ID "null" cannot be found - it may have been already approved."

**Log-Output in Debug**

First call and second call have the same logs ; 
```
----------------------------------------------------------------------------------------
Module: API-Manager - S E T T I N G S (1.3.8)
----------------------------------------------------------------------------------------
266    INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200730) on: https://myapimanager.com
781    INFO  PIManagerSettingsApp| API-Manager configuration (Remote-Hosts) successfully updated.
```

**Test case sample**
Call **apim settings import** with the following json, two times : 

```
{
  "remoteHosts":  {
    "mywebsite.com":  {
      "port":  443,
      "offerTLSServerName":  true,
      "name":  "mywebsite.com",
      "verifyServerHostname":  true,
      "organization":  "Test"
    }
  }
}
```

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @archi73. I fixed basically two issues to fix this problem, which I haven't identified before. Will be part of the release 1.3.9.
