### ISSUE TITLE
question about apim-cli as "official tool"

### ISSUE THREAD

**Issue by ftriolet** [Axway-API-Management-Plus/apim-cli#182]
In our organization, we are interested by using apim-cli for our ci/cd but we have some questions about it : 

- is apim-cli an official tools or will be?
- what is the release cycle of apim-cli : every month, every two months...?
- is apim-cli tested against each new version of api manager?

regards

**Comment by cwiechmann** [comment]
Hi @ftriolet, Thanks your questions. Please see my comments below.

- The APIM CLI is still a community asset and from a purely formal point of view, it is not directly supported by Axway. Nevertheless, it is used by many customers globally who also open support cases and get help on the tool as far as possible. There are efforts to make the CLI an official Axway tool, but without a concrete timetable.

- There is no fixed release cycle for the APIM-CLI, it depends on changes/features/bugfixes when a new version is released. Typically after 1-2 months there is a new version. However, it is not mandatory that customers follow this cycle. They can easily skip some versions if changes are not important on their side. See Changelog.md

- Yes, the APIM CLI is automatically tested against each new API Manager version as soon as it is available. 

I hope this helps!

**Comment by ftriolet** [comment]
Thanks
