### ISSUE TITLE
Manually configured API-Quotas get lost, when API is re-created

### ISSUE THREAD

**Issue by sebastian-cofi** [Axway-API-Management-Plus/apim-cli#187]
**API-Mgr. CLI version**
1.3.8
> Please make sure to use the latest available version before reporting a bug.

**API-Manager and Service-Pack Version**
7.7.20201130

**Expected behavior**
Updating APIs via CLI without losing quota settings

**Actual behavior**
Losing quota settings while updating APIs via CLI

**Log-Output in Debug**
3715   DEBUG APIManagerAPIAdapter| Found: 5 subscribed applications for this API. Taking over potentially configured quota configuration.

**Test case sample**
> Please describe the steps you have done to replicate the issue
1. create quotas via WebUI
2. update APIs via CLI
3. check quota settings via WebUI
3.1 settings are lost

**Comment by cwiechmann** [comment]
The issue has been fixed and is part of the release 1.3.9. 

Please note the following also mentioned in the documentation:
_Application-Quota overrides are not taken over as long as the API is unpublished_
