### ISSUE TITLE
Custom filter when upgrading frontends

### ISSUE THREAD

**Issue by j-boumans** [Axway-API-Management-Plus/apim-cli#189]
**User story**
The main objective is to offer the possibility to use custom filters to find the right frontend during an update.
The three default filters do not allow to find a single frontend in some specific cases.

**Additional context**
There are two behaviours:  
1. A project wants to rename its service, in this case the API must be renamed when you modify the name (and only the name) in the api-config.json file.
> Bare in mind that there is some projects that change their name and modify the name and path at the same time (in this case, the creation of a new frontend is not the best option, it would be more interesting to update the old FE)
2. Two differents projects want to expose different services with different names but on the same path.
> Here, however, it is necessary to block to prevent the second project from overwriting the first.

To address these issues, it would be interresting to have the ability to filter on custom fields (name, tag etc.).

**Comment by cwiechmann** [comment]
Hi @j-boumans, 

There are already a number of filters you can use:
```
 -a,--api-path </api/v1/my/great/api>                         Filter APIs to be exported, based on the exposure path.
                                                              You can use wildcards to export multiple APIs:
                                                              -a /api/v1/my/great/api     : Export a specific API
                                                              -a *                        : Export all APIs
                                                              -a /api/v1/any*             : Export all APIs with this prefix
                                                              -a */some/other/api         : Export APIs end with the same path
 -n,--name <*MyName*>                                         Filter APIs with the given name. Wildcards at the beginning/end are supported.
 -org <*MyOrg*>                                               Filter APIs with the given organization. Wildcards at the beginning/end are
                                                              supported.
 -id <UUID-ID-OF-THE-API>                                     Filter the API with that specific ID.
 -policy <*Policy1*>                                          Filter APIs with the given policy name. This is includes all policy types.
 -vhost <vhost.customer.com>                                  Filter APIs with that specific virtual host.
 -state <published>                                           Filter APIs with specific state: unpublished | pending | published
 -backend <*mybackhost.com*>                                  Filter APIs with specific backendBasepath. Wildcards are supported.
 -inboundsecurity <oauth-ext|api-key|*my-security-pol*|...>   Filter APIs with specific Inbound-Security. Wildcards are supported when
                                                              filtering for APIs using a custom security policy.
 -outboundauthn <oauth|api-key|My provider profile*|...>      Filter APIs with specific Outbound-Authentication. Wildcards are supported
                                                              when filtering for an OAuth Provider profile.
 -tag <tagGroup=*myTagValue*>                                 Filter APIs with a specific tag. Use either "*myTagValueOrGroup*" or
                                                              "tagGroup=*myTagValue*"
```

**Comment by j-boumans** [comment]
Hi @cwiechmann, 

Thanks for the information ! I wasn't aware of that possibility ! 
But after testing it with the tag, I don't know what to think
Maybe I am using it the wrong way

_For example :_ 
First, try to create a FE 
**Name**: API TESTING
**Path**: /my-path/hello
**tag**: id_001

Then, create another FE
**Name**: API TESTING
**Path**: /another-path/johndoe
**tag**: id_002
 
Finally, try to update the path of the second FE filtering on the tag "id_002"
**Name**: API TESTING
**Path**: /my-path/hello
**tag**: id_002

> apim api import -s dev -c ./api-config.json -tag id_002 -force

I was expecting the APIM-CLI to warn me that I am trying to update my frontend with a path that is already used by another FE but actually, it is not using the tag to filter. The API-CLI is updating the first FE and not the second one

Is this an expected behaviour ?

**Comment by cwiechmann** [comment]
That way is working for me:
```
PS C:\workspaces\apigateway-openlogging-elk\apibuilder4elastic> apim api get -s api-env -tag industry
----------------------------------------------------------------------------------------
API-Manager CLI: 1.3.9-SNAPSHOT

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - E X P O R T / U T I L S (1.3.9-SNAPSHOT)
----------------------------------------------------------------------------------------
324    INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200930) on: https://api-env:8075
1103   INFO          APIExportApp| 3 API(s) selected.
+--------------------------------------+-----------------------+------------------------------+---------+
| API-Id                               | Path                  | Name                         | Version |
+--------------------------------------+-----------------------+------------------------------+---------+
| 14295903-2583-430a-8e5b-fda415191639 | /api/hipaa/control    | Security-HIPAA-Control       |     1.0 |
| 1350f245-29d8-4e97-89d9-dcfd15d68cb0 | /api/ins/check        | INS-InsuranceCheck           |     1.3 |
| e69c03e1-d99d-4efc-bbd1-65701b20ed72 | /api/sec/auth/patient | Security-PatientAuth-Service |     2.2 |
+--------------------------------------+-----------------------+------------------------------+---------+
```

Or with a specific tag value:
```
PS C:\workspaces\apigateway-openlogging-elk\apibuilder4elastic> apim api get -s api-env -tag industry=Healthcare
----------------------------------------------------------------------------------------
API-Manager CLI: 1.3.9-SNAPSHOT

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - E X P O R T / U T I L S (1.3.9-SNAPSHOT)
----------------------------------------------------------------------------------------
264    INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200930) on: https://api-env:8075
779    INFO          APIExportApp| 2 API(s) selected.
+--------------------------------------+-----------------------+------------------------------+---------+
| API-Id                               | Path                  | Name                         | Version |
+--------------------------------------+-----------------------+------------------------------+---------+
| 14295903-2583-430a-8e5b-fda415191639 | /api/hipaa/control    | Security-HIPAA-Control       |     1.0 |
| e69c03e1-d99d-4efc-bbd1-65701b20ed72 | /api/sec/auth/patient | Security-PatientAuth-Service |     2.2 |
+--------------------------------------+-----------------------+------------------------------+---------+
```

**Comment by ftriolet** [comment]
I think @j-boumans talks about the api import capability and there is no filtering on tag in this case

**Comment by j-boumans** [comment]
Indeed, it work when you want to retrieve informations
But if you want to import changes (like modifying the path of your FE) filtering on a tag, it does not filter on it
It is only using the V-Host, the path and the API-Routing-Key

**Comment by cwiechmann** [comment]
Technically you cannot expose two different APIs on the same path, as at runtime the API-Gateway would not know, which API should serve the request.
That is the reason why the CLI, during import, is using these three criteria only to identify the actual API.

If you would like to change the path of an API, would it not be possible to register the second API with a new path, grant access to the newer API and afterwards delete the old API?

**Comment by cwiechmann** [comment]
Closing this issue now. Feel free to re-open if you need more information.

**Comment by berkane-kh** [comment]
Hi,

We are integrating apim-cli in our DevOps pipelines however we are facing a problem on the import of new API or updating an old one (with a change of the path).

### Explication: 
There are 3 criteria used to look up and identify an API: Path, V-Host & API-Routing-Key. Only "Path" is mandatory and the others are optional.
In my company we're not using the criteria:  V-Host & API-Routing-Key (because they are not mandatory). We're using tags to ensure the unicity of our FE.

In order to open our platform within DevOps pipeline (using apim-cli) we need to **filter** on **tags** when using the command: **“apim api import**” like the command **“apim api get –tag a=b ”**. 
This option will allow not just to resolve our problem but to offer more flexibility when installing/updating API.

Do you think that will possible on futures versions of apim-cli ?
