### ISSUE TITLE
A WSDL file with a long comment at the beginning is not recognized as a WSDL specification

### ISSUE THREAD

**Issue by themikebe** [Axway-API-Management-Plus/apim-cli#190]
Hello, 

I have an issue with apim-cli 1.3.9 when trying to import a new definition for an existing api.

I receive WSDL's and other formats from external clients that I don't have permission to modify. 
On this occurence, the wsdl file contains a big xml comment () at the beginning of the file. 

I use the api import feature with the following arguments
`api, import, -s, dev, -c, src/main/soap/Surveyor/SurveyorPlan2/v1/SurveyorPlan2-api-WSS-v1-config.json, -a, src/main/soap/Surveyor/SurveyorPlan2/v1/SurveyorPlan2-api-v1.url, -forceUpdate`

on the first import (clean instance), the import is successful.

the second time i run the api import with the same arguments, it returns this error:

```
----------------------------------------------------------------------------------------
API-Manager CLI: 1.3.9
                                                                        
To report issues or get help, please visit: 
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - I M P O R T (1.3.9)
----------------------------------------------------------------------------------------
16:35:58.146 [main] INFO  c.a.apim.adapter.APIManagerAdapter - Successfully connected to API-Manager (7.7.20201130) on: https://lesbgwd01.finbel.intra:10675
16:36:04.010 [main] INFO  c.a.a.a.APIImportConfigAdapter - Loading API-Definition from: http://lesbrabbitd01.lx.finbel.intra/descriptors/Surveyor/SurveyorPlan2/v1/ConsultSurveyorPlan.wsdl
16:44:22.370 [main] ERROR c.a.a.a.d.APISpecificationFactory - API: 'SurveyorPlan2-api-WSS-v1' has a unkown/invalid API-Specification: '<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI (http://jax-ws.java.net). RI's version is JAX-WS RI 2.2.11-b150616.1732 svn-revision#a247ba216861f2c0baac9a3657c5690bce0c744d. --><!--...'
Listening for transport dt_socket at address: 5005
16:44:22.380 [main] ERROR com.axway.apim.APIImportApp - Cannot read APIs from API-Manager
                                 | Cannot parse API-Definition for API: 'SurveyorPlan2-api-WSS-v1' (1.0.0) on path: '/SurveyorPlan2/api/WSS/v1'
                                 | Can't handle API specification. No suiteable API-Specification implementation available.
```

I debugged the issue and it seems to happen in WSDLSpecification.java

```
@Override
	public boolean configure() throws AppException {
		if(apiSpecificationFile.toLowerCase().endsWith(".url")) {
			apiSpecificationFile = Utils.getAPIDefinitionUriFromFile(apiSpecificationFile);
		}
		if(apiSpecificationFile.toLowerCase().endsWith("?wsdl") ||
				apiSpecificationFile.toLowerCase().endsWith(".wsdl") ||
				apiSpecificationFile.toLowerCase().endsWith("?singlewsdl")) {
			return true;
		}
		if(new String(this.apiSpecificationContent, 0, 100).contains("wsdl")) {
			return true;
		}
		LOG.debug("No WSDL specification. Specification doesn't contain wsdl in the first 100 characters.");
		return false;
	}
```

on the first import on a clean instance, it goes through : `apiSpecificationFile = Utils.getAPIDefinitionUriFromFile(apiSpecificationFile);` because I have un .url file. and the API is imported correctly.

on the second import, `APIManagerApiAdapter.getAPIs(APIFilter filter, boolean logProgress) throws AppException {` is called then `public static APISpecification getAPISpecification(byte[] apiSpecificationContent, String apiDefinitionFile, String apiName, boolean failOnError) throws AppException {`

but this time, the apiSpecificationFile is the xml that we got from the api manager, so 

```
if(new String(this.apiSpecificationContent, 0, 100).contains("wsdl")) {
			return true;
		}
```
returns false.

Would it be possible to improve the specification detection mechanism for wsdl files ?

Thanks a lot for your help.

**Comment by cwiechmann** [comment]
What would you recommend? 
Extend the number of characters to check if it's a WSDL? How long is the comment in your WSDL?

**Comment by themikebe** [comment]
my idea is:
if it was parsed once before by the api manager, we could assume that the WSDL is valid in the Axway context and from the getApi() request.
Maybe we could parse the DOM of `this.apiSpecificationContent` and look for the 'service' or 'binding' nodes that are always present ?

something along the lines of: 

```
private boolean isWsdl() throws ParserConfigurationException, SAXException, IOException {
		// read this.apiSpecificationContent as source 
		Reader xml = new StringReader(new String(this.apiSpecificationContent));
		DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
		dbf.setNamespaceAware(true);
		DocumentBuilder db = dbf.newDocumentBuilder();
		Document dom = db.parse(new InputSource(xml));

		// the service node in a wsdl is always present
		// could also be "port" or "binding"
		NodeList service = dom.getElementsByTagName("service");
		return service.getLength() != 0;
	}
```
this solves my problem with this particular wsdl, but I am unsure how the parser would react on more complex wsdl files.

**Comment by cwiechmann** [comment]
The APIM-CLI doesn't parse the WSDL, as it doesn't do anything with it and just parsing it for this purpose feels like a bit overkill for me. I would like to avoid it, as it may also cause other issues. That is the reason, why I choose the cheap approach in this detector. 

Do you think it's possible to share the WSDL, as I would like to make it part of the unit test: APISpecificationWSDLTest ?

**Comment by themikebe** [comment]
unfortunately I can't share the complete wsdl as it is not my property.

but an example failing is when some programs/frameworks add automatic comments when they generated the xml, such as:

```
<?xml version='1.0' encoding='UTF-8'?>
<!-- Published by JAX-WS RI (http://jax-ws.java.net). RI's version is JAX-WS RI 2.2.11-b150616.1732 svn-revision#a247ba216861f2c0baac9a3657c5690bce0c744d. --><!-- Generated by JAX-WS RI (http://jax-ws.java.net). RI's version is JAX-WS RI 2.2.11-b150616.1732 svn-revision#a247ba216861f2c0baac9a3657c5690bce0c744d. -->
<definitions>
....
```

maybe this comment line could be added to `sample-wsdl.xml` to reproduce ?

**Comment by cwiechmann** [comment]
That is perfect and sufficient!
