### ISSUE TITLE
Ability to grant API access when importing organisation

### ISSUE THREAD

**Issue by siemprepe** [Axway-API-Management-Plus/apim-cli#196]
We have the use case where organisations are created after api's have been onboarded.
As far as I can see, I cannot grant access to api's when importing organisation.
The ability to do so, as we can for applications would be useful.

example:
  "enabled" : true,
  "restricted" : false,
  "development" : true,
  "name" : "orgname",
  "description" : "org description",
  "apis" : [ {
      "apiName" : "testapi",
      "apiVersion" : "1.0"
    } ]

**Comment by cwiechmann** [comment]
Hi @siemprepe, the next version 1.3.11 will include this feature. You may give it a try before the release if you like and provide feedback. 
[axway-apimcli-1.3.11-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/7037027/axway-apimcli-1.3.11-SNAPSHOT.zip)

https://github.com/Axway-API-Management-Plus/apim-cli/wiki/4.-Manage-Organizations#import-an-organization
