### ISSUE TITLE
Ability to update the createdOn field when importing an existing api

### ISSUE THREAD

**Issue by archi73** [Axway-API-Management-Plus/apim-cli#197]
**User story**
When we want to update an existing api using the command `apim api import`, the creation date is never updated.
Is it possible to add a field createdOn to specify the date when importing an api into APIM ?
```
{
  "name" : "TEST",
  "path" : "/test",
  "state" : "published",
  "version" : "1.0",
  "organization" : "TEST",
  "createdOn" : 1627479182        // new field
}
```

**Comment by cwiechmann** [comment]
Hi @archi73, also for APIs, it's not possible to control the `createdOn` field externally. It's for instance not allowed to send it along with a PUT request.
