### ISSUE TITLE
Ability to update the createdOn field when importing an existing remoteHost

### ISSUE THREAD

**Issue by archi73** [Axway-API-Management-Plus/apim-cli#198]
**User story**

When we want to update an existing remote host using the command `apim settings import`, the creation date is never updated.
Is it possible to add a field createdOn to specify the date when importing a remote host into APIM ?

```
{
  "remoteHosts":  {
    "mybackendurl.com":  {
      "port":  443,
      "name":  "mybackendurl.com",
      "createdOn":  1627547807,           // new field
      "verifyServerHostname":  true,
      "offerTLSServerName":  true,
      "organization":  "Test"
    }
  }
}
```

**Comment by cwiechmann** [comment]
Hi @archi73, Looks like it's possible to update the createdOn for a remoteHost for any reason, but not to set it when creating it.
