### ISSUE TITLE
Ability to update the createdOn field when importing an existing application

### ISSUE THREAD

**Issue by archi73** [Axway-API-Management-Plus/apim-cli#199]
**User story**

When we want to update an existing application using the command `apim app import`, the creation date is never updated.
Is it possible to add a field createdOn to specify the date when importing an application into APIM ?

```
{
    "name":  "My app",
    "organization":  "Test",
    "createdOn":  1627548423,     // new field
    "description":  "My test app",
    "state":  "approved",
    "enabled":  "True"
}
```

**Comment by cwiechmann** [comment]
Hi @archi73, also here, the API-Manager doesn't allow to set or modify the `createdOn` field.
