### ISSUE TITLE
staging with a dedicated configuration directory

### ISSUE THREAD

**Issue by ftriolet** [Axway-API-Management-Plus/apim-cli#202]
We use staging for api config files. I understand that I can use the following project structure

- All at the same level (According to the wiki):

_petstore.json
minimal-config.json
minimal-config. preprod.json
minimal-config.prod.json_

- With "staging directories" (According to the code)

_petstore.json_
_minimal-config.json_
**production**
_|--minimal-config.prod.json_
**preprod**
|--minimal-config. preprod.json

- But our projects structures are

_petstore.json_
_minimal-config.json_
**configuration**
_|--minimal-config.preprod.json_
_|--minimal-config.prod.json_

So we need to create a new parameter **configDir** to pass the value"configuration"

`apim api import -s prod -configDir configuration -a petstore.json -c minimal-config.json`

**Comment by gwandwingor** [comment]
Hi @ftriolet ,

What about putting minimal-config.json in the configuration folder as well ? that would avoid requiring this configDir option ?

petstore.json
configuration
|--minimal-config.json
|--minimal-config.preprod.json
|--minimal-config.prod.json

**Comment by ftriolet** [comment]
We want to keep the main api configuration file and the environnement-specific configuration files separated because 

- we have a lot of environnements ( > 10 )
- we have this kind of structure in the deployment part of our µ-services

**Comment by cwiechmann** [comment]
I am a little reluctant to add this change, as the requirement is pretty specific. My suggestion would be to run a script in advance that copies the stage configurations accordingly to the expected flat level and then call the APIM-CLI.

**Comment by cwiechmann** [comment]
Closing this issue now, as with the new parameter `-stageConfig` you have more control about the stage config to use. It also supports a relative path such as `configuration/minimal-config.prod.json`
