### ISSUE TITLE
Import Application scopes doesn't work

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apim-cli#206]
Export of an Application will contains the scopes.
But importing the Application exported with the scope won't create them in API Manager.

**Comment by cwiechmann** [comment]
I have refactored the Application-OAuth-Resource handling. Now OAuth-Scopes are imported/updated/deleted as expected. 

Additionally, the exported application scopes will look like so:
```json
  "appScopes" : [ {
    "scope" : "scope.WRITE",
    "isDefault" : false
  }, {
    "scope" : "scope.READ",
    "isDefault" : true
  } ]
```
As the other fields are not used anyway.
