### ISSUE TITLE
Unable to refer the json file for Security profiles

### ISSUE THREAD

**Issue by meharunissa-Basheer** [Axway-API-Management-Plus/apim-cli#210]
**API-Mgr. CLI version**
> Please make sure to use the latest available version before reporting a bug.
7.7
**API-Manager and Service-Pack Version**
7.7

**Expected behavior**
To refer the json file for Security profiles updation

**Actual behavior**
Unable to refer the json file for Security profiles, getting Cant parse JSON-Config file(s)

**Log-Output in Debug**
 ERROR         APIImportApp| Cant parse JSON-Config file(s)

**Test case sample**
> Please describe the steps you have done to replicate the issue

We have added the below line in config.json, PFA for reference.
"securityProfiles": "MSC2.json",
"outboundProfiles": "requestMscJWT-noAuth.json",

We have validated the json files and all are valid one.

<img width="706" alt="SecurityProfiles" src="https://user-images.githubusercontent.com/90256844/132340964-94effef1-ccec-48d4-ace9-5b2c96b46f29.PNG">
<img width="485" alt="config" src="https://user-images.githubusercontent.com/90256844/132340486-d79c5446-bd56-43eb-b630-263b9b9aa20f.PNG">
<img width="699" alt="outboundProfiles" src="https://user-images.githubusercontent.com/90256844/132340631-8d45ef31-eb32-40ef-9ecc-f0a25c9d5779.PNG">

All the json files are available under same repo folder, We can able to refer the Swagger.json but getting issue while referring SecurityProfiles json.

<img width="327" alt="Repos" src="https://user-images.githubusercontent.com/90256844/132341445-997fbc3b-f6fa-4183-9f32-18f077c4d9dd.PNG">

**Comment by cwiechmann** [comment]
Hi @meharunissa-Basheer, What you try to do is unfortunately not supported by the CLI.

**Comment by meharunissa-Basheer** [comment]
Hello Cwiechmann,

Will it be supported in the upcoming versions, If yes kindly give us the tentative month when it will be released.

Do we have a simple way to refer the multiple security profiles, outbound profiles while deploying an API. Kindly suggest.

**Comment by cwiechmann** [comment]
Hi @meharunissa-Basheer, There is currently no plan to add support for this requirement. All belonging profiles must be part of the API-Configuration file. 
Of course, you may use a script/java-tool that is preparing the JSON-File by resolving external references before finally handing it over to the APIM-CLI. This might run, as an extra step in your CI-Pipeline.

**Comment by cwiechmann** [comment]
Closing this issue now. Feel free to re-open if you have any further questions @meharunissa-Basheer.
