### ISSUE TITLE
Unable to import Application with their API Key credential

### ISSUE THREAD

**Issue by drissslim** [Axway-API-Management-Plus/apim-cli#211]
**API-Manager CLI Version**
1.3.11

**API-Manager and Service-Pack Version**
7.7.20210530

**Question**
An error was raised during an Application import. The application was created but without their credentials (API Key).
The import was tried into 7.7.20210530 from 7.7.20210330 APIM release 
Keep the API Key credential into the imported Application

**What I've tried so far**
[error.txt](https://github.com/Axway-API-Management-Plus/apim-cli/files/7130532/error.txt)

**Additional information**
In attachment the encountered error

**Comment by cwiechmann** [comment]
This is the sample application:

```json
{
  "name" : "permut",
  "organization" : "Usine Digitale",
  "state" : "approved",
  "enabled" : true,
  "credentials" : [ {
    "credentialType" : "apikeys",
    "applicationId" : "c1d1f014-a6eb-4acf-9d23-a90685985650", // must-be-removed
    "secret" : "ed2b0212-f592-4042-a2a5-7c51fd672a4d",
    "corsOrigins" : [ "*" ],
    "apiKey" : "5dd94e53-5b8f-4da0-8f9b-4832ba5fd33c"
  } ],
  "apis" : [ {
    "apiName" : "compere",
    "apiVersion" : "beta"
  } ]
}
```

Please remove the applicationId to workaround the issue. Unfortunately previous versions of the APIM-CLI 1.3.11 have exported the applicationId as part of the application-credentials, which is not needed. See #146
