### ISSUE TITLE
Config file json schema

### ISSUE THREAD

**Issue by gwandwingor** [Axway-API-Management-Plus/apim-cli#214]
Hi,
We're evaluating the possibility to use a linting tool such as spectral to validate API config files as part of our CI/CD chain.

One of the basic check that would be interesting to apply would be to perform a schema validation on the JSON config files.

Is there a JSON schema somewhere or is it something that we would have to create ourselves ? I didn't see anything in the sources but I could have missed it.

**Comment by cwiechmann** [comment]
Hi @gwandwingor, there is NO existing JSON-Schema. Is your plan to run the schema validation before calling the APIM-CLI?

**Comment by gwandwingor** [comment]
Yes, it is.

**Comment by cwiechmann** [comment]
I was thinking it would also makes sense to integrate a schema validation directly within the APIM-CLI. So, if you are implementing this anyway, you might also do it directly. I'm happy to accept a PR, if you prefer/can.

**Comment by gwandwingor** [comment]
Yes, sure. We'll see how it goes on our side.

We haven't designed the solution yet but it is very likely that we'll also require an external Linter such as spectral to perform customer specific controls on names, paths, security and so on...
