### ISSUE TITLE
APIM duplicating API even though it already exists

### ISSUE THREAD

**Issue by pgcastro** [Axway-API-Management-Plus/apim-cli#216]
**API-Manager CLI Version**
1.3.12

**API-Manager and Service-Pack Version**
7.7

**Question**
APIM is always creating new configs even though nothing has changed and API already exists and it is published.
I enabled DEBUG and I can see this:

4015   DEBUG APIManagerAPIAdapter| No existing API found based on filter: [apiPath=/bank/party/v3 vHost=apiz3-syst.exttest.lab filter=APIFilter [id=null, name=null, vhost=apiz3-syst.exttest.lab, apiPath=/bank/party/v3, queryStringVersion=null, state=null, deprecated=false, retired=false, loadBackendAPI=false]]

I can see the API in there for the same vhost and it just keeps creating new ones (even without ANY CHANGES):

![image](https://user-images.githubusercontent.com/57509516/133256251-48356a92-3447-4151-87ff-09e6cb4f6049.png)

What am I missing?

**Comment by cwiechmann** [comment]
Based on the information you shared @pgcastro, that looks like a bug to me. Can you maybe enable Traffic-Monitoring for the API-Manager Port (default 8075) so that you can see the REST-API-Calls executed by the APIM-CLI. 

I'm most interested into the following request:
![image](https://user-images.githubusercontent.com/16292002/133257304-9fd158fb-d7dc-491e-8c12-1eff83e9f1a2.png)

Open that request and share the request details:
![image](https://user-images.githubusercontent.com/16292002/133257447-59cfb702-0afb-4b1f-aed0-a5f0c9dfd5fd.png)

And check, if there is a response:
![image](https://user-images.githubusercontent.com/16292002/133257625-ad65475a-e4dd-4a18-9589-69043fc7ca70.png)

If yes, I would like to know:
- how many APIs are returned
- confirm the returned API(s) include the VHost as configured

I tested it locally and it works as expected.

**Comment by pgcastro** [comment]
Hi @cwiechmann, first of all thank you so much for the quick response. I tried to make it work for a long while but had no clue on what to do anymore.

Because I turned DEBUG on I can see the call being made:

https://apiz3-manager-syst.ext.sun:443/api/portal/v1.3/proxies?field=path&op=eq&value=%2Fbank%2Fparty%2Fv3&field=state&op=ne&value=published

When I call that I get no results (even though API is indeed there). If I remove the "not equals to published" and call this instead:

https://apiz3-manager-syst.ext.sun:443/api/portal/v1.3/proxies?field=path&op=eq&value=%2Fbank%2Fparty%2Fv3

I get the response:

[
    {
        "id": "980e0dba-b297-4505-9bc8-04d5505f1b03",
        "organizationId": "ba897bc4-4ac6-4731-885d-b103f71f5aa4",
        "apiId": "280ecb37-dda3-4b33-82ef-9d1331c8fd1d",
        "name": "Bank Party API v3",
        "version": "3.0.0",
        "apiRoutingKey": null,
        "vhost": "apiz3-syst.ext.sun",
        "path": "/bank/party/v3",
        "descriptionType": "original",
        "descriptionManual": null,
        "descriptionMarkdown": null,
        "descriptionUrl": null,
        "summary": null,
        "retired": false,
        "expired": false,
        "image": null,
        "retirementDate": 0,
        "deprecated": false,
        "state": "published",
        "createdOn": 1631621587866,
        "createdBy": "b3c31b4a-52d4-4200-ae24-b1f59e0bfccb",
...........

Does that help?

**Comment by cwiechmann** [comment]
That helps a lot. For any reason the API-Manager does not return the API even it's published and of course the GET /proxies endpoint supports filtering on the state. 
![image](https://user-images.githubusercontent.com/16292002/133423761-71c24a36-1f7c-4255-adf0-fdab3e647c5d.png)

http://apidocs.axway.com/swagger-ui/index.html?productname=apimanager&productversion=7.7.0&filename=api-manager-V_1_3-swagger.json#!/API_Proxy_Registration/get_proxies

I quickly checked in the Source-Code, why the actual API is looked up incl. the state, as my request was without the state. I assume you are using an Org-Admin account. 

Can you confirm?

**Comment by pgcastro** [comment]
Hi @cwiechmann ,

I'm not really sure to tell you the truth. Axway manager is handled by another team and they are the FULL ADMINs.
I know for sure my service account (the one I use to run APIM) is also not a FULL ADMIN but the APIs were created using the same service account before the second run so it should be considered an "owner"?

Is there any workaround that I can use?

**Comment by cwiechmann** [comment]
You see what the code is doing. It skips/ignores all "Published" APIs, if the user has no Admin-Role. The reason for that is, that Org-Admins cannot change that API anyway. 

Have you enabled the flag, which has been introduced in one of the more recent releases?:
```xml
<ConfigurationFragment>
    <VMArg name="-Dapi.manager.orgadmin.selfservice.enabled=true"/>
</ConfigurationFragment>
```

**Comment by cwiechmann** [comment]
This is a feature flag for the API-Manager to enable Org-Admins more privileges. This would explain, why your APIs are published, even an Org-Admin is used. But the APIM-CLI is not fully supporting this flag right now.

You read more about this flag here: 
https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_relnotes/20200930_apimgr_relnotes/index.html
https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_relnotes/20201130_apimgr_relnotes/index.html 

It would be really good to know, if this flag is configured.

**Comment by pgcastro** [comment]
I'll try to find out with the Axway team. So for the time being, there nothing I can do for this to work?
I'll have to first unpublish my apis and then run import? Or is there any other workaround you can think of?

**Comment by cwiechmann** [comment]
Hi @pgcastro, I'm afraid at the moment unfortunately not. It's a complicated topic. I created another issue to add support for the mentioned feature flag: #217.
In the meantime it would be great, if you can check if the flag is set or not. _If not, I would be really surprised about the actual behavior._

**Comment by pgcastro** [comment]
Unfortunately the workaround was not enough. Even unpublishing the existing api before running APIM, the config gets duplicated saying it didn't find an existing one. :(

FYI the flag is indeed configured.
