### ISSUE TITLE
SSL client

### ISSUE THREAD

**Issue by swapon666** [Axway-API-Management-Plus/apim-cli#221]
**API-Manager CLI Version** : 1.3.13

**API-Manager and Service-Pack Version**  Axway API Manager Product Version: 7.7.20210530

**Question**

Hi Chris,

I use your apim client and it works very well in most case. One case is strange. I have a backend with SSLMutual authentification on outbound.

i use the following conf : 
....
  "authenticationProfiles" : [ {
    "name" : "_default",
    "isDefault" : true,
    "parameters" : {
      "source" : "file",
      "trustAll" : true,
		"certFile" : "C:/outils/apim-cli-1.3.3/openiris/api-integ/openiris-mobile-v1/esb-client-int.avem-groupe.com.p12",
      "password":"XXX",
	  "_id_" : 0
    },
    "type" : "ssl"
  } ],
  "caCerts" : [ {
    "certFile" : "pkiavem-int.crt",
    "inbound" : "false",
    "outbound" : "true"
  } ],
....

No error, password is correct (if not apim give me an error). But when i test my endpoint in api gateway i have an error on ssl. 
If i go on IHM, unpublished application and on outbound tabs add the same certificate and use the same password, it's works.

**What I've tried so far**

I test with no caCerts in config file, with "trustAll" : false , all don't works anymore.

I export my config when it's work the base64 decode show me a pks12 contents and i can view it : 

  "authenticationProfiles" : [ {
    "name" : "_default",
    "isDefault" : true,
    "parameters" : {
      "source" : "file",
      "trustAll" : true,
      "pfx" : "data:application/x-pkcs12;base64,MIIRPgIBAzCCEQQGCSqGSIb3DQEHAaCCEPUEghDxMIIQ7TCCC1cGCSqGSIb3DQEHBqCCC0gwggtE\r\nAgEAMIILPQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIsIOtmi4miQICAggAgIILEBCMIgz7\r\nnEIXkmive8I9xYB8UgajIYXDQPqN9TpkmOn1yHqr2XsUqXr5aCEuP/OoOF1Gj1xywKNDXa8RsFkk\r\n0DtKR+t+glDrUlcc8j9c6KwMmELAKMkRYm3vWQXwaPexFoUFQdkqwu3X3VSx3BjgQIfcvInIDE4f\r\np389BkgZy6O1iFVK+cyvZ8OFY1DoitUnlZ68AkN4d/j9PlZKce5mv3jXq0sciH2GN5e6DvILIJZI\r\ng7qJq0BShVfd3OH9YHNQTkD6FG9/+CqT1tspy6TWYNAZdVQ1hC1PV3wSVsGSI36OKtLmr5bBmaex\r\nop1eRnECU63ZpZ25LuOE0gzdvjtk7vhgB3FaiAdbGQ2soTz5loURc5KmxWH61MaOhNn42Fz7tNQr\r\nf9Jz+5X0aGdsb2HjTFGWAeKmYkFpJlqF0kXwP5I4eiJLxI6cX/+SSNpj3qj4ALmFjvPjabLiSyVC\r\nvBAc6RkaE+/9nwQ+a5GNQhUuCwpxIPIlx+EDnfKedN+PqICohhPc1bNMUztTgi1oZXqG2bzOJpoF\r\n/DYdPmW1wO7DcScqNExi8Anr5mKcIlsLsuUuxS/vpO3iUEYdEPzUSgHesOZyxulkse+effbeiGHX\r\nKig7KK0XQyDyig3+3fZMJOOPINn7qvKB3hU83iMV/53FCGBEl7DoyCKXlfxYEMgrcUf9rTvHCY3r\r\nL0+ey8k+QRBsmA3DEcd1GB5/wVhbyzyxdOltIbAFpXv/6v+/DpOLyC0+/+r54CB/DXOSYpFVY4ds\r\nfLQxuEtSSj74P4TwLohxGSIlpvK9qq/0KnRSfSCqVSs1z+jmxm+H5hyJgAENb2jdxjRsTZThq8JI\r\nwNB8BCNCIP9m+2HnLRxhCfAIjrzH3/shJO6zsn+b9p9x7A77nX9DoHSv3CUaY/9WqvXsCFXveG7i\r\nyJYqEbbHMT+leYuL1wW2fDq0zJzbhcPqzfT6t22H3CWInZpK/3VXOdp1ivept+R73m11XKQ/WGPD\r\nm+Lyay3qFHOUdnoJKzr70R58UPnEDaKTtmGCPbkDmbLQsNGeVTlMMFoA42Ykn82kk9MijSa2HZj2\r\n6e2CJMCARSyYZ2ZxyIjpUy0eN7Q6K7a4sR+BBZQsvBDFUn8F1KdjLqLBUngcmwmR8TudcLUDTJfa\r\n0U1RyLhWHtIUtLA2isw1FwcSQuhUZ9iTP9/ewxkpr8auA1ZHZHO4jcHwaChM8VUSWScXFdo/RxvT\r\nzYQIHoCGE62MjD50pCcgrHvXdJOSvhMbZaK2AZWStYDuNoLpFd1aLAFKCwFkrGBbNLDmX/OJxtA8\r\nFa3D8KZhscfsoSns0CCguNVn3JhjM5A/D/8trlfnvUHOepSvU+dBBEIx6Is8y134annomSgGYlRX\r\n4DpwpHY8ehSFUfBxH2p26PHvIrBxnIOazlzoZZCUW61OwNITXDbrAcP9qZ0agtQgEY0J0TDBoSVI\r\n5Q+Bz79D3DLZbIRURUX8jVNxo6o4C/GYtpOx897Tmf5Tbuuw7C0LzPZeQHWr2qCncfDv9MoymO4z\r\nXNMSc0MFyo52wtmsps3THOhgFCnSmE9SGPxZtJ3XPcyc7ELTQST+6OpO9ruc5jSLBVVK095lEqYR\r\ncne4+38+fmwHVFYByFr5g64Tj2M597qNFva/pPnf1mrQjOvCgS2iiozPt1A7EkieWdR8DiN1I/Xe\r\noUvLXpAKDjkt7pnbNmOr6YIHmt5TC7kBNIHIuk5GvNy0Jl7n15RsXHXeNbh8Xfsb/n1j6RiIR0i6\r\nsxi1Cb5Xcp7mSQ55+3uhY0Xf3/Z4kL5K0oylf5OBupn/PdMg1blVFEgnb22peSdArtrik8LWwOm3\r\nNNMgmiU73EkwRiZY/DGXr/hREfW7V4x21IoWxv00OCCxpjedtuCLsTbB7OttUyHmM9T20hJfCDPx\r\niCDT6p67XzlKvvIW0BUMDHaDU3/5r+70VLsb9weD1kTQ2iAC2AWUUdBbPXbX4EhabiLRjHinlu9G\r\nYdvOjFA7/qAR4vlqvpBnCE8SC7KB2CXZlZWfPZSU7XbwK17mUH8nTUKKz8Ed8RX2dLZapc6mhVcj\r\na/CfrCOHhN26fKm8fmfsNivYwswlUh/MCoeHgkI3xDUGLaGOfOjqsTBvush/0Ug3oMWtsakjll//\r\nqhhVYIfPqSjIUXdIjbWyGEq72FGZqhzYXiYXQ+ZvXL+S8LN8zK2Jyx2JJSBwd2Q/PRDQeaGN40BM\r\nZvdZM3U/fElOZylrMR+6OoOtcL/oyhicBOFtzlC/yzyPwqw9OpKbdgcyeszOYqjteWTB6mX4Ojih\r\nuv5iP2JAlHvIchmiX5EgmH1Bh6oXSgHcPlDWjrBB1iYJogGTcScL26ktBZWULKzZ3sn0oEuuziv3\r\nLIoh2gVkIdoU4dQTzrVTgXFb0GK9s1qiSKvJK+fkSTh3SlEz/y7ILWyZQhQ0ZQFUNPq9cIHOamsO\r\ntV2tppFylASvlUtuImyQs1l0Yqw9OPkGVFZEBOZJ2ePwkGw38LnSsi9fvA9NpYZYGjsr+8y1QSid\r\nL43MJezAB37Bi6up83WENi0RkwNbJg66gXjvW2mVrIKKxuPjk184Ya7H+ICZM99WM1LktysG8MZc\r\nl193Cp8e1HswZcj/nxOtO+rzfeWVy4PVSZH6McjqDgOp8OFgWnjkuMW7Oqed8o9bIWpJGrsJon8u\r\ne3TgOKpJ07hC8srtYyMMSh6wm3XtZa3QPCyM5tFpigP2fEXRtefpIZWxXZq1/tLCsQgbqmer1ai+\r\neD915gOIsC5BFm2912y+RJnseALiQJS8hO1bhuYMpjfK+bVxQMdHfaFQkGjpGNB74Zlpi1nDvC7T\r\nzyevGPi811f4MQmdRuuLEAK5wg1nFe1HDcNnsTVTx2HGopUrPBvc0e4EL6egxQmO20aQBBbmq1cg\r\npJT4wfEnWJxfzuXJJSQYj3VtzjDXK+Xo+sOEfnUlxTct4EmeUP4YMVfB8mGj1Wo0oefTknaOiumP\r\n8IpzmTzua5ciOgsb9T5Sxdo+vvtN5jWoZYdeRrvMl9+SkpX/i9isGYgcehRxBF/xIqqlcdTFPnm1\r\nGsLsmZg/wz8Wez+fRsXRBvl/YaExbMgHQMFlGa2f+8FaqjVTknShdeUJCbwjosObrqZVfTrsklYg\r\nmC0ngoqhCPctr6qegHHrSRGEbsnEJgGE3WdS/saP4qn/nCppZSKzPOyLXxOBaJTRFb54qrUySsN0\r\nQHZxOobNdtO2plR+rfXVbgbKDteKXChf+HHUeLY8OMEn9jyGXB/VEtb+5Vx5+0vMllrUaxFRvz0S\r\n/qTaxnE/JKISCfTve19s6ck7z4V+PQ3Sle6f3XMerYQp4uzfSOwjujo7AwUmbNOMTKy9KLmtfDOy\r\n2ib80jws+DUKXbB2I+UMPB9hZfjadMzCXfwHKsoffFta3ZVa6/DoGi7/JlGFVbcW+NQehTzKgVnq\r\nb4f6pCN1q+2Nt57W6FQYaYaGpqoXKLPIOxHpgWOLuk4Vh6zbRqWp855Zl49BlIhlIrydAv9l3yyL\r\nrhRAQGqpB0Av4Wy6AFkQhxSaE8hxGu4nNYNLMI1I6LJ260fC44QU/DQZSm1/p2X5vr/8caUYTJ6i\r\nw7OL88Nn0+pqz016nX9a4riNVwo3u83pAVRVpNRZK5yEg7lrR2+ARQMU1ZbFQW+zNmikccVkG1Hu\r\nY5GzgLpgp4YWwrF1wZOiEjT+8+GhEDbPyrnuEUt2EhQm++qGcvVmyQRrSYFgRCxEJibx1ZfHUUxJ\r\nMB1NBTHM0URQSzAGpTX29AnO+HEW9RyDJVm8SS+IbdPu7TCCBY4GCSqGSIb3DQEHAaCCBX8EggV7\r\nMIIFdzCCBXMGCyqGSIb3DQEMCgECoIIE7jCCBOowHAYKKoZIhvcNAQwBAzAOBAgkYN/AM7QmLQIC\r\nCAAEggTIv1NB+a1zZ4MOiv42hAE0asLrQGJfQvITEQkqr2PBbodv2gXAsT5Cs+nqV+HmrjYXlNC1\r\nBW9SsQFMqAQq+FUZtr6y3GjguqiClcgtilgv1lO1KwCr0793jB8p+yvcJQxXWhz+hV/aLAMO7bms\r\nBjrb2cqCqz+eyGboXJ4PyMWNyME5cGl7nNxn+P6gMsiROWS3uFDhTzZdoOJm5RCZUaFoY81h+O5k\r\nvQ3QmbMBFFDXOeyx0adgeMgcHqAIwW6FJMu8r0cSsng6CRP11DP03NWq+WK10a6mQLuYeUiaK4HL\r\naS3CwetRihQl4BVDXaDm9QXlDIs6+aFW02mh4p6Y+TmDhkGLF3qj82VF6ETx9FWL3xvRskFfZqf6\r\n4DyO50jU+BqqxKbWRRGCbdypo8vLeF6KvtjUu8+Nj9Hus9uq5b7ZghBl/05jr8PrsVk5rhagg2Nb\r\n07/wMViszc8VRF4RZxcL6+pwQrlXF48/Vhj4Hpp+D/vC1jozhgd9suA49NDACV4oyfku5+3Denou\r\nf4PgPpE5kNsBEqIrp1GKLXersnKsDSIwa1ca6qXb44b1WzTveL5yIK3dJgHLsSRqHYIcWSrm2Bnv\r\nLltdQ3PZ/aph5EEzMEAAHmg+cuEOVEsMQdfxNqnQFteQnbXaYGWDOt8uvrTjkY+eM1dGiP2u6O4o\r\nkp6fvnO2RUPWYJrka/ISkT03vD+v9C0sR/4mmZVBKR2eP4W8F+Qq+bnW8/Ts2qIF1FHzSVa5nd0d\r\ndhEN95Lf/qetZSVEGQJGxb29cJajhEpdYWhrtK7E6B3djNe9kk/rPN8/GR03VO/k4dDZHPxefdBh\r\nilQZhlWY4Hv5CfKD7lhpumFFW7uwlkHLU8kT4jPA08TeGrJcNeA+90Yyc8jWFDc+EOF3Rvnua1gI\r\n7KRDHwSw8ptfVYEfJgNUMw7Jo1VTsybobXyH+PHR2O0w1RERBzO57bxhKDwSRQePrN2n54DKFbAN\r\nWDt1k68gO9yaHnxkmKRmq5w15BY8LL7FzNEQ0Rc5GSwxbCR6w/DrMKS/VeGoIybLuuRiPc1ezx/Y\r\nkdYjkVJkXzh915jTwG2dlDfQMdrUGEn1W6K2blQtrG4FQB0GyF0DXkyN6OUFMsVSc87FqIQeZSBB\r\nEEsMrvf9PkDYIChyUDbc7JBFiFcBKTv4qkfYmtr66D84709qmIbTgbyo4Ln4u+a/0CDI/t2xCayS\r\nJcKd5NmYHa8ISsNAw8lJilE6hsWnE29MSc8cUkl1gotrcKaqRJDzrSTDvX7IqbxN/UYZaaF/J9PL\r\ns58d+sGZhW7ERE2KphadbPsMCnGSE7mQ5hOg8pN3d7/Wi295f/LKtWQTje9UBgYUiXXl6vkC/rlF\r\nkLsDyjSuqRX8sx4/M16yIBmGG1XPlno/JiD3qsFF1rdOpygF1qZb725XWgX+Fe/9oHWFBQ1K7A/y\r\n4STu9XTRabSqg8CvGfHxcSbao6EiN8cMLHYCmGJgRU0TsZnQegnhvVZqDczgg0hh0eP1VshS7xiq\r\nGq/7QQMJWAtnOtLc5JVdFNPSgz1lLuAUEb3vVf1P84BBCTVup94lkcJFVj6FboJaBG7LchHeP94N\r\naBKU8HxqJYAk+SwDyJjdZ/KJxO3PTIE7HALsKebVTv+GMXIwIwYJKoZIhvcNAQkVMRYEFLrqpRXA\r\nMN/plBdTy/6hgD6slqamMEsGCSqGSIb3DQEJFDE+HjwAZQBzAGIALQBjAGwAaQBlAG4AdAAtAGkA\r\nbgB0AC4AYQB2AGUAbQAtAGcAcgBvAHUAcABlAC4AYwBvAG0wMTAhMAkGBSsOAwIaBQAEFCcY9Ne9\r\ne8jItxdeAtEcUViK4R95BAgRVeheisVn2wICCAA=\r\n",
      "_id_" : 0
    },
    "type" : "ssl"
  } ],
  
  And export after launch apim with config file . not a pkcs12 content it seem to be an a file with private key ? I try to decrypt with openssl and no command works. file is very small : 
  
    "authenticationProfiles" : [ {
    "name" : "_default",
    "isDefault" : true,
    "parameters" : {
      "source" : "file",
      "trustAll" : true,
      "pfx" : "data:application/x-pkcs12;base64,MIIFozCCBIugAwIBAgIDEAAHMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNVBAYTAkZSMQ4wDAYDVQQI\r\nEwVSSE9ORTENMAsGA1UEBxMETFlPTjENMAsGA1UEChMEQVZFTTESMBAGA1UECxMJRFNJLUlOVEVH\r\nMRQwEgYDVQQDEwtwa2lhdmVtLWludDAeFw0xNzAxMTMxNTU2NDJaFw0yMjAxMTMxNTU2NDJaMHgx\r\nCzAJBgNVBAYTAkZSMQ4wDAYDVQQIEwVSSE9ORTENMAsGA1UEBxMETFlPTjENMAsGA1UEChMEQVZF\r\nTTESMBAGA1UECxMJRFNJLUlOVEVHMScwJQYDVQQDEx5lc2ItY2xpZW50LWludC5hdmVtLWdyb3Vw\r\nZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDlbFPOnfdkpsoG44ip3fNIM4sS\r\n7hf0ymbCpsQnMo833t/tpP5MT0LCoAnITg8x2qaoQk6B7gG6n9YRbKptRs574hZL/7QzMVMDQ6VN\r\neN5RkYllzsND7wr272AYYpmlmUR3KECITDBHrLheWSXlAntb0oMtLj57XdYlYcrovnfVEpb+qyM5\r\nGNJS4jGQvq7iDn49UG/mf/jUrvT9Ih7UOmqGYM9w0s+fq3KNWdxyqnvRk9L32uO+zU0GNrlJESOe\r\njM2iujLFuQBMiIbeDVz7vUw1tYsol2id262J6sFarj3vCJia/B0kYJ+rP6UCWn5/qxH3RelhHGTO\r\nNAE70TENv30VAgMBAAGjggJHMIICQzAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIF4DAdBgNV\r\nHSUEFjAUBggrBgEFBQcDBAYIKwYBBQUHAwIwEQYJYIZIAYb4QgEBBAQDAgWgMB0GA1UdDgQWBBQH\r\nyhBn0ureY/z9hBvtRM/dTxT2cTCBlwYDVR0jBIGPMIGMgBS+Vv44dgwG5UAi7JwbaPAjMLhJ+qFp\r\npGcwZTELMAkGA1UEBhMCRlIxDjAMBgNVBAgTBVJIT05FMQ0wCwYDVQQHEwRMWU9OMQ0wCwYDVQQK\r\nEwRBVkVNMRIwEAYDVQQLEwlEU0ktSU5URUcxFDASBgNVBAMTC3BraWF2ZW0taW50ggkAthxtDeqC\r\nFHEwCQYDVR0RBAIwADAJBgNVHRIEAjAAMEsGA1UdHwREMEIwQKA+oDyGOmh0dHBzOi8vcGtpYXZl\r\nbS1pbnQuYXZlbS1ncm91cGUuY29tL2luZGV4LnBocD9zdGFnZT1kbF9jcmwwOwYJYIZIAYb4QgEN\r\nBC4WLFBIUGtpL09wZW5TU0wgR2VuZXJhdGVkIFBlcnNvbmFsIENlcnRpZmljYXRlMDMGCWCGSAGG\r\n+EIBAgQmFiRodHRwczovL3BraWF2ZW0taW50LmF2ZW0tZ3JvdXBlLmNvbS8wIwYJYIZIAYb4QgED\r\nBBYWFG5zX3Jldm9rZV9xdWVyeS5waHA/MD4GCWCGSAGG+EIBCAQxFi9odHRwczovL3BraWF2ZW0t\r\naW50LmF2ZW0tZ3JvdXBlLmNvbS9wb2xpY3kuaHRtbDANBgkqhkiG9w0BAQsFAAOCAQEAT/SViJW1\r\nVYC7rGFZcG2ss8Y4VYFL3ADRCn3vZdnENTyRP7vhj+MH7MceffRKmwRSGIDIcKC2zs5xmTS+Ix4x\r\nE90FQIU68Q3fo+0q3z7uvDQO9fm5WSM7wYTQV4zR3rTKe75AyuitMlILzkXKTbqKGj4QyIVPGRWm\r\nvOZLEgMYFSOr8aR4iQNYs1INB0JE+vNq6ZzT7SQdr+KpR0DkYvCqX9GA9EOM2mKk5KW7/dUmScEa\r\no/f7lO3jVFjNhM/CmoYiAe/UE6lb9OBBg83vd1OXxaVFBkBOP/26PUzyhlK+d1JmxPqkWLhUPF/0\r\nEtrdE6uNVQXYLvrC2y09po9zyXrbyQ==\r\n",
      "_id_" : 0
    },
    "type" : "ssl"
  } ],

**Additional information**

Error SSL with apim
"/openiris/internal/v1/documentGed/findById"] [unique_id "Id-7156546107181dd99381f9fe"]
ERROR	9/29/21, 14:05:05.606	                                [SSL verify_cb, 0x13, 0 ] self signed certificate in certificate chain, { subject: /C=FR/ST=RHONE/L=LYON/O=AVEM/OU=DSI-INTEG/CN=pkiavem-int, thumbprint: FF:FB:8B:2A:7F:B0:86:37:51:00:3D:64:70:98:78:F9:C8:4D:3E:9E }.
ERROR	9/29/21, 14:05:05.606	                                [SSL alert write 0x230, 0x4]: unknown CA [fatal] { subject: /C=FR/ST=RHONE/L=LYON/O=AVEM/OU=DSI-INTEG/CN=pkiavem-int, thumbprint: FF:FB:8B:2A:7F:B0:86:37:51:00:3D:64:70:98:78:F9:C8:4D:3E:9E }.
ERROR	9/29/21, 14:05:05.606	                                [SSL_connect, 0x4]: error - self signed certificate in certificate chain { subject: /C=FR/ST=RHONE/L=LYON/O=AVEM/OU=DSI-INTEG/CN=pkiavem-int, thumbprint: FF:FB:8B:2A:7F:B0:86:37:51:00:3D:64:70:98:78:F9:C8:4D:3E:9E }.
ERROR	9/29/21, 14:05:05.606	                                transient failure connecting to remote: SSL protocol error
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed, source location: ssl/statem/statem_clnt.c:1915
ERROR	9/29/21, 14:05:05.606	                        The message [Id-7156546107181dd99381f9fe] logged Failure at 09.29.2021 14:05:05,606 with log description: Failed to route request to endpoint.
ERROR	9/29/21, 14:05:05.606	        The message [Id-7156546107181dd99381f9fe] logged Failure at 09.29.2021 14:05:05,606 with log description: Filter failed
ERROR	9/29/21, 14:05:05.606	The message [Id-7156546107181dd99381f9fe] logged Failure at 09.29.2021 14:05:05,606 with log description: Filter failed
ERROR	9/29/21, 14:05:05.606	Filter that caused failure: apimanager.outbound.ssl
Policy 'API Broker' {
Filter 'Set service context' Status: PASSED
Filter 'API Proxy' Status: FAILED
Policy 'Default API Proxy Routing' {
Filter 'Default Routing' Status: FAILED
Filter 'Id-0001529531619406-ffffffff85b212c2-1' Status: FAILED
Policy 'Default SSL-based Routing' {
Filter 'apimanager.outbound.ssl' Status: FAILED

**Comment by cwiechmann** [comment]
Hi @swapon666, I'm afraid you found a bug in the CLI and I'm working on it to get this fixed.

**Comment by swapon666** [comment]
Hi Chris,

I test with the following  patch and it's work very well :-)

$ diff  -Naur /c/outils/apim-cli-develop/modules/apis/src/main/java/com/axway/apim/apiimport/APIImportConfigAdapter.java modules/apis/src/main/java/com/axway/apim/apiimport/APIImportConfigAdapter.java
--- /c/outils/apim-cli-develop/modules/apis/src/main/java/com/axway/apim/apiimport/APIImportConfigAdapter.java  2021-10-04 10:40:34.710116200 +0200
+++ modules/apis/src/main/java/com/axway/apim/apiimport/APIImportConfigAdapter.java     2021-10-04 10:40:31.475728000 +0200
@@ -836,7 +836,7 @@
                                certificate.getEncoded();
                        }
                        if(this.apiConfig instanceof DesiredTestOnlyAPI) return; // Skip here when testing
-                       JsonNode node = APIManagerAdapter.getFileData(certificate.getEncoded(), clientCert);
+                       JsonNode node = APIManagerAdapter.getFileData(dataFile, clientCert);
                        String data = node.get("data").asText();
                        authnProfile.getParameters().put("pfx", data);
                        authnProfile.getParameters().remove("certFile");

**Comment by swapon666** [comment]
I can send you a MR if you want because paste of patch content in content it's not good

**Comment by swapon666** [comment]
[patch-ssl-client-pb.txt](https://github.com/Axway-API-Management-Plus/apim-cli/files/7276771/patch-ssl-client-pb.txt)

**Comment by cwiechmann** [comment]
Thanks @swapon666. In the meantime I changed the CLI to use the API-Manager REST-API directly to handle the given keystore instead of doing it in the CLI directly. With that I could remove the loadKeystore method.
I think I had initially a miss-understanding about how to use the REST-API endpoints (filedata, certinfo) correctly.

Very likely the change you propose goes into the same direction.

The changes are currently tested and once finished, it would be great if you make some smoke tests. Do you want me to upload a SNAPSHOT-Build here or do you want to build it yuorself?

**Comment by cwiechmann** [comment]
The build has passed. Let me know, if you can test a recent build of the CLI @swapon666.

**Comment by swapon666** [comment]
i just test your develop banch and i have some error when i run my config with p12 cert client :

1483   DEBUG nvironmentProperties| Property: 'port' not found.
1567   ERROR         APIImportApp| API-Manager failed to read certificate information.
                                 | API-Manager failed to read certificate information: esb-client-int.pfx. Got response: '<html><body>Unsupported Media Type</body></html>'.
com.axway.apim.lib.errorHandling.AppException: API-Manager failed to read certificate information.
        at com.axway.apim.adapter.APIManagerAdapter.getCertInfo(APIManagerAdapter.java:604)
        at com.axway.apim.apiimport.APIImportConfigAdapter.handleOutboundSSLAuthN(APIImportConfigAdapter.java:832)
        at com.axway.apim.apiimport.APIImportConfigAdapter.validateOutboundAuthN(APIImportConfigAdapter.java:780)
        at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:205)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:76)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:141)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
Caused by: com.axway.apim.lib.errorHandling.AppException: API-Manager failed to read certificate information: esb-client-int.pfx. Got response: '<html><body>Unsupported Media Type</body></html>'.
        at com.axway.apim.adapter.APIManagerAdapter.getCertInfo(APIManagerAdapter.java:599)
        ... 11 more

**Comment by swapon666** [comment]
My config for the test : 
.....
  "authenticationProfiles" : [ {
    "name" : "_default",
    "isDefault" : true,
    "parameters" : {
      "source" : "file",
      "trustAll" : true,
		"certFile" : "esb-client-int.pfx:PKCS12",
      "password":"QUE071NF",
	  "_id_" : 0
    },
    "type" : "ssl"
  } ],
....

the same is working with no error with my patch

**Comment by cwiechmann** [comment]
@swapon666, Unfortunately I cannot reproduce the behavior you reported. However, I made a change to use the endpoint: `/certinfoFromUrl` and perhaps that is the reason. Can you please try again. 

I really would like to stick to the approach leveraging the API-Manager REST-APIs instead of trying to open/load the keystore directly with the CLI itself.

**Comment by swapon666** [comment]
Hi Chris,

I try with your last commit and i 've got the same error. I use the last version of apigateway : 
Axway API Manager
Product Version: 7.7.20210830

Best regards,

Pascal PEJAC

AVEM

 
1436   DEBUG SpecificationFactory| Can't handle API specification with class: com.axway.apim.api.definition.Swagger1xSpecification
1521   DEBUG nvironmentProperties| Property: 'port' not found.
1706   DEBUG nvironmentProperties| Property: 'port' not found.
1706   DEBUG    APIManagerAdapter| data: [Content-Type: application/x-www-form-urlencoded,Content-Length: 6829,Chunked: false]
1838   ERROR         APIImportApp| API-Manager failed to read certificate information.
                                 | API-Manager failed to read certificate information: esb-client-int.pfx. Got response: '<html><body>Unsupported Media Type</body></html>'.
com.axway.apim.lib.errorHandling.AppException: API-Manager failed to read certificate information.
        at com.axway.apim.adapter.APIManagerAdapter.getCertInfo(APIManagerAdapter.java:605)
        at com.axway.apim.apiimport.APIImportConfigAdapter.handleOutboundSSLAuthN(APIImportConfigAdapter.java:832)
        at com.axway.apim.apiimport.APIImportConfigAdapter.validateOutboundAuthN(APIImportConfigAdapter.java:780)
        at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:205)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:76)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:141)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
Caused by: com.axway.apim.lib.errorHandling.AppException: API-Manager failed to read certificate information: esb-client-int.pfx. Got response: '<html><body>Unsupported Media Type</body></html>'.
        at com.axway.apim.adapter.APIManagerAdapter.getCertInfo(APIManagerAdapter.java:600)
        ... 11 more

**Comment by swapon666** [comment]
I can test with change Content-Type if you want

**Comment by swapon666** [comment]
Sorry Chris, 

Now it's working. I don't know why. I just restart my apigateway.
Thanks a lot Chris.

Best regards,

Pascal PEJAC
