### ISSUE TITLE
Filter on tag when import api

### ISSUE THREAD

**Issue by berkane-kh** [Axway-API-Management-Plus/apim-cli#223]
**User story**

We are working around DevOps pipeline by using apim-cli. We need to filter on tags when using the command: **“apim api import”** like the command **“apim api get –tag a=b ”**.

**Additional context**
There are 3 criteria used to look up and identify an API: ​Path, V-Host & API-Routing-Key. **Only "Path"** is mandatory and the others are optional.

In my company we're not using the criteria: V-Host & API-Routing-Key (because they are not mandatory). We're using tags to ensure the uniqueness of our api.

This option **(filtering on tag when import api)** will not just solve our problem but offer more flexibility when installing/updating API.

@cwiechmann Do you think that will possible on futures versions of apim-cli ?

**Comment by cwiechmann** [comment]
Thanks for creating this enhancement @berkane-kh. The APIM-CLI is using these three criteria on purpose, as they are used in the same way by the API-Gateway at runtime. 

When an API-Request is received, the API-Gateway must determine which API of the catalog should handle the request and this happens on the API-Path + VHost + Query-Version. 

Even you make the APIs unique using tags for a human, they are not unique for the API-Gateway perspective and method matching might fail or it's just random (very likely the last registered API) might be selected to handle the request.

Therefore, As of now and with my current knowledge, I believe changing this behavior of the APIM-CLI is not a good option.
