### ISSUE TITLE
How to import a swagger file with content: application/jwt?

### ISSUE THREAD

**Issue by luizsouzagarcia** [Axway-API-Management-Plus/apim-cli#226]
**API-Manager CLI Version**
Apim-Cli 1.3.10

**API-Manager and Service-Pack Version**
Api Manager 7.7.20210330

**Question**
I would like to know how to import swagger file with a header content-type = application/jwt ?
Sample of code:
`requestBody:
     content:
         application/jwt:
             shema:`

I receveid the follow message when I try:
"Failed to import Swagger. Unknown MimeType: \"application/jwt\"".

I've ready include this on fed file, in the Mime settings properties.

**What I've tried so far**
Import a swagger file usegin CLI.

**Additional information**

**Comment by cwiechmann** [comment]
Closing this issue. Feel free to re-open if you need more information/help.
