### ISSUE TITLE
Question around 1.4 release

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#231]
Hi, 
we have been using up to 1.3.12 in our CI, by automatically setting up 
      classpath group: 'com.github.axway-api-management-plus.apim-cli', name: 'apimcli-apis', version: '[1.3.0,1.4.0)'      

Is a 1.4 a major release? I've check the change log and it doesn't appear to bring any major or breaking change right? 
may i please ask for more info around the release strategy? 

Thanks

**Comment by cwiechmann** [comment]
Hi @emmanuel-galindo, in the future you will more often see major version upgrades, whenever the release contains a new feature. But such a release will never contain a breaking change. The minor version will contain bug fixes only if needed.

Only with a new generation (e.g. 2.x.y) compatibility is not guaranteed.

so, feel free to upgrade to version 1.4.0 as it is safe as before.
