### ISSUE TITLE
Error code 400 when updating the API Access of an Application

### ISSUE THREAD

**Issue by rribei** [Axway-API-Management-Plus/apim-cli#236]
**API-Manager CLI Version**
1.3.10

**API-Manager and Service-Pack Version**
7.7.20210330

**Question**
Could you please help me to add a new API Access to an existing Application using APIM CLI? I tried the following steps:

1. Exported the Applications with command: 
scripts/apim.sh app get -o json -t myapps/ -s api-env
It created a  myapps/APP1/application-config.json file with the content as below:

{
  "name" : "APP1",
  "organization" : "LAB",
  "state" : "approved",
  "enabled" : true,
  "apis" : [ {
    "apiName" : "PUCOMEX",
    "apiVersion" : "1.0"
  } ]
}

2. Changed directory to myapps/APP1 and ran the following to add a new API Access:
jq '.apis[.apis| length] |= . + {"apiName" : "Healthcheck", "apiVersion" : "1.0"}' application-config.json > new.json
It created a file with content as below:

{
  "name": "APP1",
  "organization": "LAB",
  "state": "approved",
  "enabled": true,
  "apis": [
    {
      "apiName": "PUCOMEX",
      "apiVersion": "1.0"
    },
    {
      "apiName": "Healthcheck",
      "apiVersion": "1.0"
    }
  ]
}

3. Tried to import the new file using the command below:

scripts/apim.sh app import -c myapps/APP1/new.json -s api-env

And got the following error:

$ scripts/apim.sh app import -c myapps/APP1/new.json -s api-env
/opt/Axway/apigateway/Linux.x86_64/jre/bin/java

----------------------------------------------------------------------------------------
API-Manager CLI: 1.3.10

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: Application - I M P O R T (1.3.10)
----------------------------------------------------------------------------------------
0      INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20210330) on: https://X.X.X.X:8075
789    ERROR agerAPIAccessAdapter| Error creating/updating API Access: APIAccess [apiName=Healthcheck, apiVersion=1.0, id=null, apiId=46a96537-96d5-483e-90fa-a35a8829ebba]. Response-Code: 400. Got response: '{"errors":[{"code":400,"message":"Invalid JSON format"}]}'
793    ERROR ApplicationImportApp| Error creating/updating application
                                 | Error creating/updating API Access.
                                 | Error creating/updating API Access. Response-Code: 400

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @rribei. 

I see you are using version 1.3.10 - Can you please try to do the same with version 1.4.0? I tried to replicate this issue, but it works on my side.

**Comment by rribei** [comment]
Hi @cwiechmann ,
I confirmed that 1.4.0 solves the issue. Thank you so much for the help!
