### ISSUE TITLE
Capability to filter the API-Specification (Operation/Method)

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apim-cli#238]
**User story**
It should be possible to filter the given API-Specification so that, for example, certain HTTP methods or individual operations are not registered with the API. A user can configure `includes` and/or `excludes` 

For example, to register an existing API based on a generated API-Specification, but without for instance the `DELETE` methods.

Currently the API-Specification is defined as a simple property `apiDefinition` which is a String. To support filters for an API specification, the APIM-CLI should be changed so that the API specification can be defined as an Object with the following structure. The path to the API-Specification itself, will be registered as a resource and is the only mandatory field. It works in the same way as the apiDefinition.

```json
{
  "name": "Filtered API",
  "path": "/api/which/is/filtered",
  "state": "unpublished",
  "version": "1.0.0",
  "apiSpecification": {
    "resource": "../petstore.json",
    "filter": {
      "paths": {
        "include": [
          "/pet.PUT",
          "*.GET"
        ],
        "exclude": [
          "/pet/{petId}.DELETE"
        ]
      }
    }
  },
  "organization": "API Development"
}
```

**Additional notes**
- filters are optional
  - in case of duplicated definitions, excludes take precedence over includes
    - to avoid for instance the DELETE-Method to be included accidentally
  - if a method or operation is not explicitly excluded, it is included by default
    - even if not declared as included
- `apiDefinition` should still be supported
- filtering should not be supported with command line parameter `-a`
- exporting API will not contain the filters anymore, as the information cannot be stored in API-Manager
  - export will contain the already filtered API
  - beginning with that version the API-Config will contain the `apiSpecification` object instead of the `apiDefinition`
- compare between Actual- vs. Desired-API should happen, after the filter have been applied
  - this results for instance in a No-Change, when the same filters are applied

**Comment by ftriolet** [comment]
Interesting feature. Is the filtering done against operation name or path ? Currently , i plan to use [Swagger Combine](https://www.npmjs.com/package/swagger-combine) in order to do such filtering

**Comment by cwiechmann** [comment]
Hi @ftriolet, the plan is use API-Filtering based on the HTTP-Methods and operationId's. This might esp. help for generated API-Specs that contain too many HTTP-Methods and/or operations.

Do you think the issue describes it entirely?

**Comment by ftriolet** [comment]
What about adding a specific file for the filter configuration and a new command line parameter ? API config file will be the same for the import/export and the filtering configuration  will be separate.

**Comment by ftriolet** [comment]
Hi @cwiechmann , I'm still wondering if operationId is the best option for filtering as it's not a required parameter. I have some APIs from external providers which not using operationId. I would prefer filtering on the path.

**Comment by ftriolet** [comment]
Hi @cwiechmann ,

I kept thinking about it. My proposal is to add a filter field in app-config file :

`{
  "name": "Filtered API",
  "path": "/api/which/is/filtered",
  "state": "unpublished",
  "version": "1.0.0",
  "apiDefinition": "./petstore.json",
  "filter" : "./filter.json"
  "organization": "API Development"
}`

And a new file for the filter : 

_filter.json_

`{
  "filter": [
    {
      "paths": {
        "exclude": [
          "*.delete"
        ]
      }
    },
    {
      "paths": {
        "include": [
          "/pet.put",
          "*.get"
        ]
      }
    }
  ]
}`

Further operations could be add later like renaming path

**Comment by cwiechmann** [comment]
@ftriolet, but why do you think it is better to have an external file instead of putting it directly into the API-Config file? 

```json
{
  "name": "API with API-Specification object",
  "path": "/api/v1/Some.Services/XmlApi",
  "state": "published",
  "version": "1.0.0",
  "organization": "API Development",
  "apiSpecification": {
  	"resource": "petstore.json",
  	"filter": {
  		"include": {
  			"GET": "*",
  			"PUT": "operation1, operation2" 
  		},
  		"exclude": {
  			"DELETE": "*" 
  		}
  	} 
  }
}
```

I have another question: 
I would like to make the filter configuration as simple as possible. As you can see in the example above, I would implement the filters based on the HTTP-Verb followed by the path, as I believe this is what customers more often need. For example: "Include all GET-Operations no matter which operation." Or: "Don't include DELETE-Operation". 

I see, you expected it differently based on your example. Do you see any specific benefit configuring it the other way around?

**Comment by ftriolet** [comment]
Hello  @cwiechmann,

For the first question, it was to keep the api config file as identical as possible  for the import and the export. If we have an unique file, export will no longer contains filtering configuration. This configuration could be huge in case of big swagger files ( i have some  > 9mb) 

Second question, I'm agree with you, it's just another syntax where path is before http verb as in swagger file . Maybe if you want to keep all operations of an identical path, you can do it in a more concive way with "/my_path.*"

**Comment by cwiechmann** [comment]
Thanks for the feedback @ftriolet. You mean, you Swagger-Files might be up to 9MB big and you would need that many filtering rules? 

I have slightly adjusted the filter config again like so:
```json
"apiSpecification":{
      "resource":"../petstore.json",
      "filter":{
         "include":{
            "paths":[
               "/pet.PUT",
               "/user.*",
               "*.GET"
            ]
         },
         "exclude":{
            "paths":[
               "/pet/{petId}.DELETE"
            ]
         }
      }
   }
```
This allows us to add other filters like tag-groups at the same level as path without the need to repeat include/exclude. Would it help to simplify you use-case when having the option to filter for tags?

Besides that, I completely followed your recommendation. You can configure combinations of wildcards as shown in the example above.
