### ISSUE TITLE
OAS draft

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#242]
Hey @cwiechmann  by any chance do you have a OAS draft for the tool different actions? We will need to create an API in top of the apimcli

Or maybe you know about anything already available or started?

**Comment by cwiechmann** [comment]
Hi @emmanuel-galindo, I'm not sure I understand it correctly.

As the APIM-CLI is not a server application it doesn't expose any REST-API and therefore there is no OAS specification.

**Comment by emmanuel-galindo** [comment]
ok, thanks for the quick response. It was just to check if there was anything started around developing an API to interface the tool, to not start from zero. 

As we use 100% SSO, we are not able to accomodate many use case scenarios that could benefit from your great tool

if this is correct, please go ahead and close it. once done, we'll try to publish the service to github for others to benefit
