### ISSUE TITLE
Custom directory name for cholocatey installation

### ISSUE THREAD

**Issue by davidgeiger** [Axway-API-Management-Plus/apim-cli#243]
When installing the apim-cli using chocolatey, it would be nice to specify a custom installation directory. The default directory points to chocolatey's script execution folder which requires administrator privileges on most machines for both installation and editing the config files.

I believe this can be done by adding an install argument to chocolateyinstall.ps1 and passing it using the --ia switch. Also, the file seems to reference an earlier version of the cli.

As an alternative, a pointer could be added to the installation instructions to adjust the (user) env variable AXWAY_APIM_CLI_HOME to be able to edit the config files. This would still require admin privilege for installation, though.

https://docs.chocolatey.org/en-us/getting-started#overriding-default-install-directory-or-other-advanced-install-concepts

**Comment by cwiechmann** [comment]
The current choco installation procedure is extracting the zipped archive and creates a shim (.exe file) to the bat file on Windows. 

I could change the location where the ZIP-Archive is extracted, but the generated apim.exe is anyway generated in the chocolatey\bin folder, which requires Admin-Permissions and I see no option to change this.

**Comment by cwiechmann** [comment]
Hi @davidgeiger, the --ia switch is to control parameters for an installer, that is executed by Choco. In case of the apim-cli just a ZIP-Archive that is extracted. 
The shim is required to make it possible to run the BAT/Java-Application like a normal executable. 

Concerning the configuration file, it should be possible to point the `AXWAY_APIM_CLI_HOME` to a directory which is writable by a normal user and if given, it's used by the APIM-CLI to read the config-files. I know, it requires 1-Time Admin-Permissions to set this up, but once configured users have the flexibility to control the CONF-Files on their own and they can stay in the same directory with every new version update.

**Comment by davidgeiger** [comment]
Hi Chris. Couple of other ideas:

1) The [Choco docs](https://docs.chocolatey.org/en-us/features/shim) indicate there's a non-administrator Choco install option to a user directory. Haven't been able to try it yet but that might resolve the issue (and would be worth a pointer in the CLI instructions).

2) Get rid of the shim and simply have the Choco installer script automate the same steps as a manual installation:
1. Download and extract the archive to a given (user-writeable) directory
2. Set AXWAY_APIM_CLI_HOME and add it to the search path.
Unless I'm missing something, this will yield the same result: users can simply type apim to run the bat/sh file?
