### ISSUE TITLE
Backslashes in user passwords are ignored

### ISSUE THREAD

**Issue by davidgeiger** [Axway-API-Management-Plus/apim-cli#244]
**API-Mgr. CLI version**
1.5.0

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
All passwords supported by API Manager should be accepted.

**Actual behavior**
A single backslash (\) in a password entered in an env config file is ignored. As a workaround, the backslash can be escaped with another backslash.

**Log-Output in Debug**
Login finally failed with statusCode: 403

**Test case sample**
Use an API Manager password that contains a backslash and store the password in an env config file.

**Comment by cwiechmann** [comment]
Happy new Year @davidgeiger :tada: and thanks for reporting this issue! 

As you may already know, the backslash is treated as special character in a properties file to support multi-line values, hence it is ignored. 
With the next version the APIM-CLI will replace all backslashes (in the entire file) with a double backslash to escape it.
