### ISSUE TITLE
Export multiple apps/apis with a single command call

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#245]
Hi,
is it possible to indicate multiple apps/apis when exporting them via the tool?
use case: clean up day! we need to remove unused stuff

**Comment by cwiechmann** [comment]
Hi @emmanuel-galindo, yes this is the default behavior for many of the operations. Many of them are designed as mass operations.

Depending on the operation, the  CLI selects all Apps, APIs, etc. using the given filters you provide. If you don't provide any filter all entries of a type are selected.
The operation, e.g. delete apps, is then performed on the returned selection.

So, it depends on the filters you provide. 
You may start with a simple get to see if your filters are working as expected and if you are happy with the selection and then change it to the command you want.

**Comment by emmanuel-galindo** [comment]
understood, in this case what we are doing is selecting apps and apis that have not been used in a certain period of time (6 months), export and remove them

we identify them by app-id, and maybe it was possible to send several ids in one call. We are talking a couple of hundreds and calling each of them has a lot of initialization overhead. Additionally, I've just realized that the exported app by apim-cli doesn't include app-id (which makes sense of course) and that unique app names is not enforced - therefore for this step, I am going to use the API mgr mgmt api call call /migrate/applications/export/download?filename=xxx.dat

maybe there is a better approach to do this? in any case, I will close this case.. thanks for teh quick response
