### ISSUE TITLE
Need to Provide a Certificate to Import a SOAP API

### ISSUE THREAD

**Issue by avoketaitis** [Axway-API-Management-Plus/apim-cli#249]
**API-Manager CLI Version**
1.6.1

**API-Manager and Service-Pack Version**
7.7.20200730

**Question**
I am attempting to import a SOAP API. The site that is serving the WSDL requires a certificate. I do not see a way to specify a certificate in the configuration settings file or any other means of specifying a certificate. Just to clarify, if I were to 'curl' the WSDL, I would need to provide my cacert, key, and cert using the --cacert, --key, and --cert options. I need to be able to provide these when running apim-cli so that it doesn't get a 403 access denied when importing the WSDL.

**What I've tried so far**

**Additional information**

**Comment by cwiechmann** [comment]
Is my understanding correct, that the site requires a Client-Certificate just to access the WSDL?

**Comment by avoketaitis** [comment]
Yes. That is correct!

________________________________

**Comment by cwiechmann** [comment]
I'm afraid, but this is unfortunately not possible as the CLI is not downloading the WSDL itself.

As you know, the API-Manager only supports the import of the WSDL from a URL. 
Therefore, when importing a SOAP-Service, the CLI tells the API-Manager to import it from the configured location. 
This is btw different to the OpenAPI/Swagger import where the CLI imports it from the local file system.

Hence, for the WSDL-Import the CLI has no control about the connection established by the API-Manager to the WSDL-Server. 

I'm really sorry, but I don't see any way to solve this.

**Comment by avoketaitis** [comment]
I would like to suggest an alternative. I am able to manually import the WSDL into my Policy Studio API Repository and then create a backend API in API Manager using 'Import from Topology'. Could you enhance apim-cli to support this feature as a means of importing APIs?

________________________________

**Comment by cwiechmann** [comment]
Hi @avoketaitis, Yes, that might work. I checked the response from the ANM for the WSDL-Discovery and got the following example:

```json
[
    {
        "id": "<key type='WebServiceRepository'><id field='name' value='Web Service Repository'/><key type='WebServiceGroup'><id field='name' value='Web Services'/><key type='WebService'><id field='name' value='BankingServices'/></key></key></key>",
        "deprecated": false,
        "apiVersion": "1.0",
        "swaggerVersion": "1.1",
        "basePath": "http://172.20.0.1:8080/BankingDemo.asmx?WSDL",
        "resourcePath": "",
        "models": {},
        "consumes": [],
        "produces": [],
        "name": "BankingServices",
        "basePaths": [
            "http://172.20.0.1:8080/BankingDemo.asmx?WSDL"
        ],
        "image": "",
        "state": "published",
        "cors": false,
        "expired": false,
        "retirementDate": 0,
        "retired": false,
        "tags": {},
        "availableApiDefinitions": {
            "Swagger 1.1": "/discovery/swagger/api/id/%3Ckey%20type='WebServiceRepository'%3E%3Cid%20field='name'%20value='Web%20Service%20Repository'/%3E%3Ckey%20type='WebServiceGroup'%3E%3Cid%20field='name'%20value='Web%20Services'/%3E%3Ckey%20type='WebService'%3E%3Cid%20field='name'%20value='BankingServices'/%3E%3C/key%3E%3C/key%3E%3C/key%3E?swaggerVersion=1.1&filename=BankingServices.json"
        },
        "availableSDK": {},
        "apis": [],
        "accessGrantedDate": 0,
        "type": "wsdl"
    }
]
```

In order to tell the APIM-CLI to load the API from the ANM the API-Definition/API-Specification must be configured differently. As a refactoring for the `apiDefinition` is planned anyway to support filters (#223), it might look like this:
```json
{
  "name" : "My Banking Services",
  "path" : "/banking/demo",
  "state" : "published",
  "version" : "2.0",
  "organization" : "API Development",
  "apiSpecification" : { 
    "type": "topologyWSDL",
    "name": "BankingServices"  <<< Must be the name as returned by the discovery response
   },
  ....
  ..
```

Additionally, it would be required to authenticate with the ANM, which is not yet the case. 

This is a considerable amount of work and it is not guaranteed, this gets finally implemented as the use-case pops up very rarely.

**Comment by cwiechmann** [comment]
I'm afraid I see no bandwidth to implement this requirement and I don't want give wrong expectations here, therefore I'm closing this issue now.
