### ISSUE TITLE
updateOnly option for publication for api import

### ISSUE THREAD

**Issue by Gilles-APIM** [Axway-API-Management-Plus/apim-cli#251]
**User story**
Joel from BNPP PF want to publish a new API, with this Organisation account with the DevOps Toolchain using apim-cli.
The DevOps administrator want only publication in the APIM if the API already exist, in the DevOps Toolchain launched by Ansible & Jenkis the CLI cmd is configured with an option ReplaceOnly

Like in this exemple
  apim.bat api import -c C:\git_repos\Test_cli_qa\cpay_special_revolving_payment_transfer\api-config.json -s qa **--replaceonly** 

If an API with the same frontend Url and organization exist it will be replaced
If the API is not present nothing happen

**Additional context**
The CLI is launched in our devops toolchain with Jenkins and Awx (Ansible) the cmd line options for the CI are fixed.

We simply want to execute the CLI with an option to only update existing API.

**Comment by cwiechmann** [comment]
Implementing such a parameter is not problem, but I think it should be named: **--updateonly**, as an existing API is updated (and for that sometimes replaced). 

If the API not yet exists the CLI will terminate with a specific error code.

**Comment by cwiechmann** [comment]
Implemented new toggle: -updateOnly will be part of the release.
