### ISSUE TITLE
Export and filter app creator

### ISSUE THREAD

**Issue by davidgeiger** [Axway-API-Management-Plus/apim-cli#252]
**User story**
When exporting apps include the creator user (email address?). Also enable filtering by the creator.

**Comment by cwiechmann** [comment]
Hi @davidgeiger, I have a question for this requirement. Not only about application, but in general for all other entities.

If you export an entity as JSON, including the "createdBy" property, that would contain the username. 

What should happen, if you try to re-import this entity and this user does not exists? 
Would it not be better not to export the createdBy property to avoid problems when staging an entity?

**Comment by davidgeiger** [comment]
That's a fair point. I guess properties that are exclusively intended to be automatically set should not be considered during import. If they are intended to (also) be adjusted manually (e.g., changing app ownership as an admin), they should at least be validated. In fact, both of these points should be enforced by the API Manager API itself, but that's a different story.

Re staging across environments, can't this be handled in the same way as all other properties that are or may be environment-specific?

In our case, we needed a quick way to report the creator's email address for all apps in a specific org in order to reach out to this group. We ended up using a series of API calls to achieve this for now, but it would be much easier through the CLI.

**Comment by cwiechmann** [comment]
Thanks for the feedback. In that case, I would implement a filter for the creator of an application and it will be exported as part of the Console- & CSV- for reporting, but not for the JSON-Output. 

I would like to avoid to have this createdBy validation for now. Would this be okay/sufficient for you?

**Comment by davidgeiger** [comment]
That would be very helpful! Reporting is completely sufficient from my perspective.

I am not sure if changing the creator of an app is a supported use case, at all (even if the API might technically allow it). But even so, it is probably an edge case that could be tackled by calling the API directly.
