### ISSUE TITLE
Updated/Changed Endpoint (Certificate or Hostname)

### ISSUE THREAD

**Issue by larswaldeZ** [Axway-API-Management-Plus/apim-cli#266]
**User story**

If the Certificate has Changed on the Endpoint it would be great to have an option that the apim-cli would update these certificates.

At the moment nothing happens because the API itself hasn´t changed.
I guess we had also the Problem if only the Endpoint has changed ... but that was tested with an earlier Version fo apim-cli.

**Additional context**

**Comment by cwiechmann** [comment]
You can force the API to be re-created, even if the Desired-State equals the Actual-State. With that, new certificates are loaded from the backend automatically.
