### ISSUE TITLE
Unpacking differences between 1.12.0 and 1.12.1 ? 

### ISSUE THREAD

**Issue by jboms** [Axway-API-Management-Plus/apim-cli#296]
### APIM-CLI version

1.12.1

### Question

Hello, 

We use APIM-CLI in a docker image
We download version 1.12.0 (axway-apimcli-1.12.0.tar.gz) and, with the "ADD" instruction in a dockerfile, we unpack the archive and move it to a specific directory. 

When we build this image, everything works fine: 
![image](https://user-images.githubusercontent.com/102585336/179707251-7126ca78-b856-4403-a785-083c3ba6bf10.png)

And our CI ends with a "Job Succeded"

However, when we retrieve version 1.12.1, the job ends with an error : 
![image](https://user-images.githubusercontent.com/102585336/179708448-29c114b5-61d4-473e-bef8-3e903bd75ac4.png)

At first we thought we had made a mistake somewhere or that the download had gone wrong: 
- We took the 1.12.0 release, it works
- We switched back to 1.12.1, it doesn't work anymore
- The runner is the same, the script has not changed, we do not see where the problem can come from

Are there any differences in encoding or anything else between the 1.12.0 and 1.12.1 releases?

Thanks for your help

**Comment by rathnapandi** [comment]
Hi @jboms, 

Yes, release 1.12.1 built and released from Mac.  From Mac I could unpack the file with command "tar zxvf axway-apimcli-1.12.1.tar.gz".  Could you please share your OS and dockerfile? I will test and get back to you.

**Comment by rathnapandi** [comment]
I am closing it, please reopen if you see still see the issue.
