### ISSUE TITLE
oas 3.0 base path handling

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apim-cli#297]
### APIM-CLI version

1.12.0

### API-Management version

7.7.20211130

### Bug description

I found a difference in handling import for swagger 2.0/oas 3.0 REST API.

For swagger 2.0 if the backendBasePath is only host and port (http://host:port) the basepath defined in swagger file is used in the backend api and at runtime the base path is concatenated before calling the backend.

For OAS 3.0 it seems that what is defined in servers.url is ignored and I have to redefine the complete URL in backendBasePath (http://host:port/base/path)

Is it a desired behaviour?  

I expected to same behaviour, reading the "base path" from the servers.url

what do you think?

**Comment by rathnapandi** [comment]
@gcornacchia I have tested with version  7.7.20220530 and I don't see the issue. 

If I don't provide hostname in servers.url e.g   
```json 
"servers": [
    {
      "url": "/api/v3"
    }
```
API Manager throws an error **Relative server URL not supported for scheme: 'file'. Please add $.servers to the OAS3 document, or host it as is, and import via URL.**

### Working Openapi example with servers.url

```json
  "servers": [
    {
      "url": "https://petstore3.swagger.io/api/v3"
    }
  ],
```
API Manager screen. 
![image](https://user-images.githubusercontent.com/3596610/181417109-45b4c7a0-efcf-4d96-a05c-ea5380589f9c.png)

When you manually import BE API, did you attach a file or use URL? if we use the URL API manager appends the host name.

**Comment by gcornacchia** [comment]
I wasn't speaking about importing manually in api manager but using apim-cli.

Consider the following scenario:


[petstore.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/9218275/petstore.zip)

In the attached zip file you can find:

1) **PetStoreAPI3.0.json** which is an API definition file that uses petstore3.json interfacefile (oas 3)

2) **PetStoreAPI2.0.json** which is an API definition file that uses petstore2.json interface file (swagger 2.0)

If you have a look at the interface files you will see that:

1) petstore2.json has a basePath field with a value of /v2
2) petstore3.json has a servers.url field with a value of  /api/v3

Consider that every definition has a "backendBasepath" field with the value "http://backend"
If I use apim-cli to import these 2 APIs I found that in the frontend API

for PetStoreAPI2.0 the backend service url is: http://backend/v2 (the base path is read from the swagger)

for PetStoreAPI3.0 the backend service URL is only: http://backend (it's ignoring /api/v3 in the oas)

That's the point I was talking about

Can you try this scenario in 7.7.20220530?

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

Thanks for clarification.  Your observations are correct, i am seeing same behavior in  7.7.20220530 too.

The issue is CLI is overriding the open api servers.url element with backendbasepath if backendbasepath is present in config.json file.  In my earlier comment I tested with CLI without backendbasepath parameter in config.json and seen a different behavior. 

I will work on the fix.
