### ISSUE TITLE
BackendBasepath problem exporting SOAP API with apim-cli

### ISSUE THREAD

**Issue by AyseErg** [Axway-API-Management-Plus/apim-cli#299]
### APIM-CLI version

1.12.0

### API-Management version

7.7.20210330

### Bug description

Hello, 
So I have a SOAP API created on the HMI. 
I export this API with apim-cli in order to integrate it in a CI/CD pipeline. 

I noticed that in the api-config.json file, in the backendBasepath object instead of having my host/basepath I find my host/basepath/path from wsdl.

Ex : 
Instead of : **_https://myhost/api/v1_** 
I have **_https://myhost/api/v1/some/more/path/from/wsdl_** 

For now I would have to modify the backendBasepath  to  **_https://myhost/api/v1_**  in order for the API to work.

Wouldn't it be more logical to retrieve in the api-config.json file, the url that is in the **backend service URL field** in the **Outbound** part of the API frontend?

**Comment by AyseErg** [comment]
That is correct. So when I export this API with **apim-cli**, in the configuration file, the **backendBasepath** contains the full path : _**http://test.axway.com/services/Calculator.CalculatorHttpsSoap12Endpoint/.**_ 
But I would expect getting only :  **_http://test.axway.com_**.

Yo explain my problem, in my ci/cd workflow: 

-  first the wsdl is uploaded on the server
-  then the url is put in the api-config.json file in the apiSpecification.resource field 
- finally  the API is imported with the **apim-cli** (apim api import). 

But I have a duplication problem, backendBasepath becames :  **_http://test.axway.com/services/Calculator.CalculatorHttpsSoap12Endpoint/services/Calculator.CalculatorHttpsSoap12Endpoint/)_**

Since the api manager adds once more the WSDL's service location as backendBasepath. 

So shouldn't apim-cli export only http://test.axway.com in the api-config file ?

**Comment by rathnapandi** [comment]
I agree with you. It should contain http://test.axway.com based on the above use case.  Let me double check on the fix is not going to break anything else.
