### ISSUE TITLE
Importing SOAP API with apim-cli adds "+" instead of spaces for the Backend API name

### ISSUE THREAD

**Issue by AyseErg** [Axway-API-Management-Plus/apim-cli#301]
### APIM-CLI version

1.12.0

### API-Management version

7.7.20210330

### Bug description

Hello, 

Whenever I'm deploying (import) a SOAP API using the apim-cli, I noticed that for the **Backend API name** the spaces are convert to "+".

For exemple : **Pet store_API** becames **Pet+store_API**.

Any ways to change that ?

**Comment by jschutte27** [comment]
I noticed this as well.

**Comment by al1073910** [comment]
Hi, I'm getting back to you after some testing on apim-cli's latest version (1.12.3). 
When I import soap APIs with apim-cli, I still get "+" in my backend API name.

For the one's I already imported with previous version,  doing a new import doesn't replace the backend API name.

Could you mind reopening this bug ?

**Comment by rathnapandi** [comment]
Hi @AyseErg 
Can you delete your front end and backend API and test it?

**Comment by al1073910** [comment]
Hi, 
It's working this way. But I guess if I don't delete the API the "+" won't affect it.

Thank you !
