### ISSUE TITLE
Backend API service URL for Per-method Overrides don't get exported and can't be imported via APIM CLI

### ISSUE THREAD

**Issue by jonkristjan** [Axway-API-Management-Plus/apim-cli#302]
### APIM-CLI version

1.12.2

### API-Management version

7.7.20210330

### Bug description

In cases where APIs have Per-method Overrides with customized Backend API service URLs (shown below) the APIM CLI does not export the customized URL and it is not possible to import a customized per-method backend.

![image](https://user-images.githubusercontent.com/6500351/183138747-8454f219-008a-4578-90a6-125b9a90aed0.png)

![image](https://user-images.githubusercontent.com/6500351/183138791-b8404bd5-f09b-4500-92df-d45fe6bffee7.png)

The APIM CLI export includes the per-method override but not the custom URL:
![image](https://user-images.githubusercontent.com/6500351/183139178-50da1906-7016-49bf-8290-fba7a50a8900.png)

### Steps to reproduce

1) Virtualize an API in API Manager.
2) Apply a per-method override on the Outbound config and customize the API Proxy with a different backend.
3) Export the API via APIM CLI.
4) The exported API Config will not include the customized/different backend.

**Comment by rathnapandi** [comment]
Hi @jonkristjan, 

We are linking two backend APIs for a frontendAPI by editing outbound configuration and customize the API Proxy with a different backend.
Currently APIM CLI handles single API state and it does not support the above use case.

I have marked as an enhancement, will discuss with Erik Nord and update you.

**Comment by lbouvard** [comment]
Hi @rathnapandi 

I have the same need to export/import the proxy override. I'am using the CLI (latest version) to deploy APIs between environment on CI/CD pipeline and it is not good that we have to update manually this config for each env.

Any news about this enhancement ?

Or is there a way via the REST API to update this configuration ?

Thanks

**Comment by ggavio** [comment]
Hi @rathnapandi 
We've many implementations waiting for this also. 
We would really appreciate if this can be prioritized. Almost an year  since @jonkristjan reported the issue. Many thanks!

**Comment by cbrowet-axway** [comment]
Hi, same request here.
It's quite problematic to not be able to reproduce a full APIM status. It kills the "configuration as code" approach for one of my customer.

Was it actually implemented (as it's closed). It doesn't seem so in v1.14...

**Comment by razvan4axway** [comment]
@rathnapandi I had a call today with a client who is facing the same issue/requests the same implementation. Practically you have one frontend and some methods are pointing to one backend ( old) while other(s) to a new backend. Exporting with apim cli will always output the original definition of the FE and the old BE. Practically the change needed would need to export both backends together with the FE. Importing should also permit importing one FE with multiple BE's. This might be a bit complicated but we want to clarify if this implementation can be done. Thanks!

**Comment by ggavio** [comment]
was this finally implemented ?
