### ISSUE TITLE
Test failures in APIImportConfigAdapterTest.usingOSEnvVariable EnvironmentPropertiesTest.testEnvironementWithOSEnvVariables

### ISSUE THREAD

**Issue by saper** [Axway-API-Management-Plus/apim-cli#305]
### APIM-CLI version

1.12.3

### API-Management version

unknown

### Bug description

Trying to run `mvn install` on a freshly checked out repository, happens both on 1.12.3 tag as well as on d4d8011aa491a6e66bc00fbbdbba0ddabd261ee4 (current `develop`)

Ubuntu 18.04

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Axway API-Manager CLI Parent 1.12.3-SNAPSHOT:
[INFO]
[INFO] Axway API-Manager CLI Parent ....................... SUCCESS [  0.402 s]
[INFO] Axway API-Manager CLI API-Manager Adapter .......... SUCCESS [  4.263 s]
[INFO] Axway API-Manager CLI Command Line Interface ....... SUCCESS [  1.053 s]
[INFO] Axway API-Manager CLI API Tool ..................... FAILURE [  4.792 s]
[INFO] Axway API-Manager CLI Application Tool ............. SKIPPED
[INFO] Axway API-Manager CLI Organization tool ............ SKIPPED
[INFO] Axway API-Manager CLI User tool .................... SKIPPED
[INFO] Axway API-Manager CLI Settings tool ................ SKIPPED
[INFO] Distribution ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.689 s
[INFO] Finished at: 2022-08-12T17:53:09+02:00
[INFO] ------------------------------------------------------------------------
```

### Steps to reproduce

git clone https://github.com/Axway-API-Management-Plus/apim-cli
cd apim-cli
mvn install

### Relevant log output

```shell
Tests run: 119, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 4.123 sec <<< FAILURE! - in TestSuite
testEnvironementWithOSEnvVariables(com.axway.apim.test.envProperties.EnvironmentPropertiesTest)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: expected [Fixed value and true some dynamic parts] but found [Fixed value and  some dynamic parts]
        at com.axway.apim.test.envProperties.EnvironmentPropertiesTest.testEnvironementWithOSEnvVariables(EnvironmentPropertiesTest.java:83)

usingOSEnvVariable(com.axway.apim.test.basic.APIImportConfigAdapterTest)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.AssertionError: expected [Operating system: null] but found [Operating system: ${OS}]
        at com.axway.apim.test.basic.APIImportConfigAdapterTest.usingOSEnvVariable(APIImportConfigAdapterTest.java:85)


Results :

Failed tests:
  APIImportConfigAdapterTest.usingOSEnvVariable:85 expected [Operating system: null] but found [Operating system: ${OS}]
  EnvironmentPropertiesTest.testEnvironementWithOSEnvVariables:83 expected [Fixed value and true some dynamic parts] but found [Fixed value and  some dynamic parts]
```

**Comment by saper** [comment]
To fix the second one, I have set `CI` to `true`, since I've had `JAVA_HOME` set already. In general, the tests should make sure the environment is known and clean prior to testing...

The first one seem to be a real bug - if `OS` is not set, it gets expanded as `${OS}`. Setting `OS` to `dupa` in my environment seemed to fix the first failure.

👎

**Comment by rathnapandi** [comment]
Hi @saper thanks for testing and raising the issue. 

I have fixed junit test. 
1. testEnvironementWithOSEnvVariables - The test is ignored if there is no "JAVA_HOME" environment variable  but it fails if there is no "CI" environment variable. The fix ignores  CI environment variable validation if environment variable is not set. 
2. usingOSEnvVariable - Windows has 'OS environment variable and OS check is ignored only for Mac.  Looks like all Linux flavors does not have OS environment variables.  The fix ignores the 'OS' environment variable validation if it is not found .

**Comment by saper** [comment]
Thank you for a quick fix! I can confirm that 7846b88b10970589f0e3ea5a6036cfad4a178374 runs tests successfully now.

**Comment by saper** [comment]
One more thing - I think that `${OS}` should expand to nothing (or raise an error) if `OS` is not set. Expansion to `${OS}` string is not good...

**Comment by rathnapandi** [comment]
You are right. The environment variable is not expanding in the test - usingOSEnvVariable. 

I have fixed the issue.
