### ISSUE TITLE
Path is added after the backend basepath

### ISSUE THREAD

**Issue by GuillaumeJq** [Axway-API-Management-Plus/apim-cli#307]
### APIM-CLI version

1.12.3

### API-Management version

7.7.20210530

### Bug description

Hi, 

An error occurred with the APIM-CLI upgrade (version 1.12.3)
When deploying an API, the path used for the front end concatenates with the backend URL, leading to a pathing error.

For example, in this [template.txt](https://github.com/Axway-API-Management-Plus/apim-cli/files/9426188/template.txt), the problem occurred during the deployment. After it, when we check on the API Manager, we see that the backend URL service in the "FrontEnd API" tab gives: http://localhost:8080/v1/adminorg/piste/v1/adminorg/ and no longer http://localhost:8080/v1/adminorg/

Is it desired ?

**Comment by rathnapandi** [comment]
Hi @GuillaumeJq, 

As part of defect https://github.com/Axway-API-Management-Plus/apim-cli/issues/299 we changed backendbasepath handling. 

Most cases the backendbasepath should contains protocol and hostname e.g - http://localhost:8080 and basepath will be derived from API specification ( like swagger, openapi or WSDL). If we want to add extra path prefix to existing basepath which is available in API specification then we will add basepath as part of backendbasepath. 

Please do let me know if it clarifies your question.
