### ISSUE TITLE
[BUG] Output folder is empty

### ISSUE THREAD

**Issue by kunwardhwaj** [Axway-API-Management-Plus/apim-cli#31]
**API-Mgr. CLI version**
> Please make sure to use the latest available version before reporting a bug.

**API-Manager and Service-Pack Version**

7.6.2, SP3
**Expected behavior**
Should be able to export the api;s.

**Actual behavior**
target folder is empty,

**Log-Output in Debug**

target folder is empty,

**Test case sample**
> Please describe the steps you have done to replicate the issue
I am able to see the exported API's on the terminal, but the target folder is empty after running this command : **apim api get -s dev --output json -t C:/axway/apis**

**Comment by cwiechmann** [comment]
Hi @kunwardhwaj, Do you see any log output?
What happens if you try to export just on the console by using no output option at all?

**Comment by cwiechmann** [comment]
Looks like it doesn’t realize the output format. Can you please try with -o json?

When the output format is detected successfully, it doesn’t print the console table anymore. Hence, in your case the output format is not detected.

**Comment by kunwardhwaj** [comment]
Hi @cwiechmann ,

I tried **apim api get -s dev -o json -t C:/axway/apis**, but it's still empty.

I prints the details on the terminal though.

**Comment by cwiechmann** [comment]
And you are using version 1.1.0? 

In version 1.0.0 and 1.0.1 the parameter was named -f or —format, which I have changed to -o or —output be aligned with the AMPLIFY CLI.

**Comment by kunwardhwaj** [comment]
yes, I am using version 1.0.1 Below is the output from my local dev API Manager:

**λ apim api get -s local -o json -t C:/axway/apis
------------------------------------------------------------------------
API-Manager CLI: 1.0.1

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
------------------------------------------------------------------------
Module: API - E X P O R T / U T I L S (1.0.1)
------------------------------------------------------------------------
1426   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.6.2 SP3) on: https://localhost:8075
1771   INFO          APIExportApp| 2 API(s) selected.
+--------------------------------------+-----------------------+-----------------------------+---------+
| API-Id                               | Path                  | Name                        | Version |
+--------------------------------------+-----------------------+-----------------------------+---------+
| 4d226e01-5444-420f-8f27-120efc1f8b8c | /api                  | Wisercare_Inbound_API       |     1.0 |
| 287e2508-a24f-4e92-9a6a-7d30c236cbd8 | /v2                   | petstore swagger.json       |   1.0.5 |
+--------------------------------------+-----------------------+-----------------------------+---------+**

**Comment by cwiechmann** [comment]
That is the problem. Please download the latest version 1.1.0 and then use the parameter: -o or —output

**Comment by cwiechmann** [comment]
Perhaps a good idea to watch the repository and select the option to get notified for new releases.

**Comment by kunwardhwaj** [comment]
Thanks! That fixed the issue!
