### ISSUE TITLE
Unknown MimeType supplied : application/x-pem-file

### ISSUE THREAD

**Issue by drissslim** [Axway-API-Management-Plus/apim-cli#314]
### APIM-CLI version

1.10.1

### API-Management version

7.7.20220228

### Question

Hi,
I'm getting this error when try to publish an API that produces an "application/x-pem-file" MimeType:

3808   ERROR APIManagerAPIAdapter| Error importing API-Specification (Swagger 1.x) to create Backend-API. Received Status-Code: 400, Response: '{"errors":[{"code":400,"message":"Failed to import Swagger. Unknown MimeType supplied"}]}'
3810   ERROR         AppException| Can't import definition / Create BE-API.
                                 | Can't import API-Specification to create Backend-API.

 I'm using version 1.10.1 of apim-cli. Could you please confirm if the tool doesn't support the mime-type?
  
Thank you.
Slim

**Comment by tbres** [comment]
I believe this is not a problem with the apim-cli tool, but a limitation of Axway API Manager. 

There is a setting to disable this mime-type validation during api import: https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_reference/api_mgmt_config_web/index.html#api-import

**Comment by drissslim** [comment]
That's right! Thank you very much
