### ISSUE TITLE
APIM does not detect changes made in API-Managment

### ISSUE THREAD

**Issue by GennaroRiccio** [Axway-API-Management-Plus/apim-cli#317]
### APIM-CLI version

1.13.0

### API-Management version

7.7.0.20220830

### Bug description

Import Api Definition swagger, edit from API-Managment GUI if export API-Definition modified swagger file does not contain the changes. 

### Steps to reproduce

From Api-Managment modifying an existing Api Definition, adding, for example, a method

Export Api-Managment definition 

apim api get -s test -name articoliwebapi -o json

The swagger.json don't contain new method or changes

**Comment by rathnapandi** [comment]
Hi @GennaroRiccio, 

Can you use the flag -useFEAPIDefinition. By default it exports API definition from backend which does not contain the changes made in API manager UI.

**Comment by GennaroRiccio** [comment]
HI @rathnapandi 
The proposed solution works well. Thank you
