### ISSUE TITLE
Problem with verbose

### ISSUE THREAD

**Issue by CLargemain** [Axway-API-Management-Plus/apim-cli#320]
### APIM-CLI version

1.13.0

### API-Management version

7.7.20220530

### Bug description

Hello team,
When running any command with the APIM CLI, we get two lines before the answer that we think we shouldn't be able to see since we are in level=FATAL everywhere in the log4j2.xml file.
```
nov. 02, 2022 11:05:50 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: spSessionId2=deleted;Version=1;Comment=;Domain=;Path=/api/portal/v1.4/;Max-Age=0;Secure;HttpOnly;SameSite=Strict". Blank or null value for domain attribute
```
Is it a bug or do we have something else to do to remove these two lines?
Thanks

### Steps to reproduce

Any command can work, but for example:
`apim app get -s XXXXX`

### Relevant log output

```shell
C:\Users\XXXXX>apim app get -s XXXXX
----------------------------------------------------------------------------------------
API-Manager CLI: 1.13.0

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: Application - E X P O R T / U T I L S (1.13.0)
----------------------------------------------------------------------------------------
nov. 02, 2022 11:05:50 AM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: spSessionId2=deleted;Version=1;Comment=;Domain=;Path=/api/portal/v1.4/;Max-Age=0;Secure;HttpOnly;SameSite=Strict". Blank or null value for domain attribute
Loading details of 88 applications [*********-] 90%
```

**Comment by rathnapandi** [comment]
Hi @CLargemain , 

I could not reproduce it on my local APIM version  7.7.20220530. Did you configure SSO on API manager?

**Comment by CLargemain** [comment]
Hello @rathnapandi,

Yes, we have configured SSO on our API Manager. Do you think it might be related?

**Comment by mvenzke-axway** [comment]
Looks like it should be an issue in APIM where we send a blank Domain=; in the Set-Cookie header instead of just leaving that whole section out and I've reported it in RDAPI-29530.  You can perhaps set com.axway.sso.domain.name to a domain name in APIM's JVM properties to get rid of this, assuming you don't rely on it being blank for some reason.  It looks like that's where SSO is pulling the domain from.
