### ISSUE TITLE
Delete verbose at the begenning of output with parameter

### ISSUE THREAD

**Issue by CLargemain** [Axway-API-Management-Plus/apim-cli#321]
### Problem description

Hello team,

When running any command with the APIM CLI, these lines show up at the begenning:
```
----------------------------------------------------------------------------------------
API-Manager CLI: 1.13.0

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
```

This is annoying for multiple reasons:

- When we run multiple commands in a row, we always get these lines and they are not necessary each time.
- When redirecting the ouput of the command in a file, we get these informations too and it's something we have to handle, we remove it with a piece of work on our side. 

Could it be possible to have an option to remove all the verbose that isn't the real output of the command?

### Feature request

We would like to have an option (it could be a parameter directly in the command or an argument in a file to set to true/false) to remove these lines.

**Comment by rathnapandi** [comment]
Removed those lines as part of latest release.
