### ISSUE TITLE
Export apiRoutingKey

### ISSUE THREAD

**Issue by Chillytwix** [Axway-API-Management-Plus/apim-cli#323]
### Problem description

Greetings.
When exporting an API, the property apiRoutingKey is not part of the export api-config.yaml file.

This property is used for controlling routing to the correct API based on it's version.
Example:
"apiRoutingKey" : "v2"

Best regards

### Feature request

Exporting of API value, apiRoutingKey

**Comment by rathnapandi** [comment]
Hi @Chillytwix, 
The APIM-Cli does handle apiRoutingKey, can you share more information like API Gateway version and debug logs.

**Comment by rathnapandi** [comment]
apiRoutingKey is exported as for get api command.
