### ISSUE TITLE
broken link on main page

### ISSUE THREAD

**Issue by jpouget74** [Axway-API-Management-Plus/apim-cli#326]
### APIM-CLI version

NA

### API-Management version

NA

### Bug description

main page https://github.com/Axway-API-Management-Plus/apim-cli/wiki/2.1.2-API-Configuration-file has a broken link "see here for more details"

![image](https://user-images.githubusercontent.com/87341755/202036465-81f71ba7-7851-448a-b9f3-3c83c5f81dd0.png)

![image](https://user-images.githubusercontent.com/87341755/202036544-d65f8f93-8664-416f-ac4c-5cf197a6d567.png)

### Steps to reproduce

go to https://github.com/Axway-API-Management-Plus/apim-cli/wiki/2.1.2-API-Configuration-file
click on the link "see here for more details"

### Relevant log output

```shell
see description
```

**Comment by rathnapandi** [comment]
Fixed
