### ISSUE TITLE
APIM UI FeAPI via UI WSDL import, exported and imported by CLI fails, due to wsdl file reference api-config.json

### ISSUE THREAD

**Issue by JSomervilleFromAz** [Axway-API-Management-Plus/apim-cli#328]
### APIM-CLI version

1.12.2

### API-Management version

7.7.20220228

### Bug description

Entered on behalf of a customer.

A WSDL based API imported using API Manager UI, is unable to be exported and then imported via CLI.

It will fail because the exported api-config.json file points to an apiSpecification resource that is not the original HTTP location of the WSDL, but the WSDL filename.  And, using file based import of WSDL api is not allowed.

Would it be possible for APIM CLI exports of such APIs to contain correct HTTP URL so it can be imported by the CLI?

Thanks

### Steps to reproduce

Steps:
Using API Manager UI, create a new BeAPI and then FeAPI from a WSDL hosted on an HTTP URL.
Using APIM CLI, export that API.
Then, use API CLI to import that API into a different environment, or the same after removing old one.

### Relevant log output

```shell
Console:
2711   INFO  SpecificationFactory| Reading API-Definition (Swagger/WSDL) from file: 'C:\00.GitSource\API.Axway.FromRedacted\redacted\redactedData.wsdl' (absolute path)
[...]
2891   ERROR APIManagerAPIAdapter| Error importing WSDL. Received Status-Code: 400, Response: '{"errors":[{"code":400,"message":"Invalid url"}]}'
2896   ERROR         AppException| Can't import definition / Create BE-API.
                                 | Can't import WSDL from URL / Create BE-API.

Instance trace:
ERROR    URl: 'redactedData.xml' is not a valid http/https url
DEBUG   java exception: javax.validation.ConstraintViolationException: createApiFromUrl.arg5: Invalid url
```

**Comment by rathnapandi** [comment]
Hi @JSomervilleFromAz,

This is the product limitation as API manager REST Api requires WSDL http URL. Please refer https://apidocs.axway.com/swagger-ui-NEW/index.html?productname=apimanager&productversion=7.7.0&filename=api-manager-V_1_3-swagger.json#/API%20Proxy%20Registration/post_proxies_importFromUrl
and

https://apidocs.axway.com/swagger-ui-NEW/index.html?productname=apimanager&productversion=7.7.0&filename=api-manager-V_1_3-swagger.json#/API%20Proxy%20Registration/post_proxies_importFromUrl

the second URL which is used for upload file doesn't support WSDL.

We need to edit the api-config.json file with http/s WSDL url to get it working.

**Comment by JSomervilleFromAz** [comment]
Agreed, the underlying API does not support file based import, and the current wiki does note this.

https://github.com/Axway-API-Management-Plus/apim-cli/wiki/2.1.10-API-Specification#options-to-provide-the-api-specification
"⚠️ Local files are not supported for WSDLs as the API-Manager doesn’t support import a WSDL from a local file!"


>>We need to edit the api-config.json file with http/s WSDL url to get it working.

The customer question is, can APIM CLI not detect it is a WSDL based API on export, and create a fixed api-config.json automatically with the orignal URL?   (Assuming it is accessable in the /apirepo data model for the BeAPI.)

Thanks

**Comment by rathnapandi** [comment]
I think it is feasible to add the url if it is available as the URL is stored in a variable importUrl.

**Comment by rathnapandi** [comment]
@JSomervilleFromAz 

The issue has been fixed; it will be released next week.
