### ISSUE TITLE
Special characters in Policy name used request, response or routing policy of an API

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apim-cli#336]
### APIM-CLI version

1.12.3

### API-Management version

7.7.20220228

### Bug description

exporting an API with a Policy on the outbound (request, response, routing,..) with a special character, it is HTML encoded on the config.json files : 

For example  : the request policy : "VALIDATE ACCESS TOKEN **&** GET JWT CACHE"
becomes in the config.json : "requestPolicy" : "VALIDATE ACCESS TOKEN \&amp\; GET JWT CACHE",

Then if you try to import it into API Manager you get an error:
2022-12-08 16:11:48,437 [APIImportApp] ERROR: Error reading API-Config file(s)
                                | The request policy: 'VALIDATE ACCESS TOKEN \&amp; GET JWT CACHE' is not configured in this API-Manager
                                 | Exception: com.axway.apim.lib.errorHandling.AppException: The request policy: 'VALIDATE ACCESS TOKEN \&amp; GET JWT CACHE' is not configured in this API-Manager

So as a workaround we need to modify the config.json file before importing it.

It seems that it is API Manager that give the name of the policy with the HTML encoded.
But maybe apim-cli should decode it before imported it?

### Relevant log output

```shell
2022-12-08 16:11:48,437 [APIImportApp] ERROR: Error reading API-Config file(s)
                                | The request policy: 'VALIDATE ACCESS TOKEN \&amp; GET JWT CACHE' is not configured in this API-Manager
                                 | Exception: com.axway.apim.lib.errorHandling.AppException: The request policy: 'VALIDATE ACCESS TOKEN \&amp; GET JWT CACHE' is not configured in this API-Manager
```

**Comment by rathnapandi** [comment]
Fix will be available as part of v1.13.3
