### ISSUE TITLE
importing api swagger including oauth security 

### ISSUE THREAD

**Issue by jordi-matelet** [Axway-API-Management-Plus/apim-cli#342]
### APIM-CLI version

1.13.2

### API-Management version

7.7.20221130

### Question

Hello,
I have a question regarding the creation of securityProfiles and the security per api method when importing an api swagger file.

I am working with swagger 2.0 api definitions in which I have different "securityDefinitions" elements which are secured with "oauth", exemple:
`"securityDefinitions": {
    "securityDef1": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://vmapi01:8089/api/oauth/authorize",
      "scopes": {
        "read": "Lecture",
        "write": "Ecriture"
      }
    }
  }`
Then in the swagger, each api methods are secured with a security block that point to a securityDefinitions and use a subset of its oauth scopes, exemple:
`"security": [
          {
            "securityDef1": [
              "read"
            ]
          }
        ]`

When importing this api swagger using apim-cli, all those oauth securityDefinitions and method security are totally ignored, and the created frontend api is set to passthrough. There is no securityProfiles associated to all the api methods.
Is there a way to automatically create the security defined in swaggers at a frontend level? Am I doing something wrong?

Thank you

**Comment by rathnapandi** [comment]
Hi @jordi-matelet, 
API CLI import operation does not use securityDefinitions  from specification.  We need to manually define it in api-config.json file.  

We do have an option to create a config file from specification and import it to manager.  But it supports openapi with apikey and basic auth. Oauth is not fully supported yet. 

Refer - https://github.com/Axway-API-Management-Plus/apim-cli/wiki/10.-Create-API-configuration-file-from-OpenAPI-specification

Thanks
Rathna
