### ISSUE TITLE
backendBasepath not working correctly when server url missing in swagger

### ISSUE THREAD

**Issue by jschutte27** [Axway-API-Management-Plus/apim-cli#348]
### APIM-CLI version

1.13.3

### API-Management version

20220530

### Bug description

When we have a swagger file that is missing the servers block the backend basepath ends up with a duplicate path.  

With "backendBasepath" : "https://server.example.com" we get https://server.example.com/ on the backend.

With "backendBasepath" : "https://server.example.com/subpath" we get https://server.example.com/subpath/subpath on the backend.

### Steps to reproduce

Import a swagger file that does not contain servers:
```
  "servers": [
    {
      "url": "/subpath"
    }
  ],
```

**Comment by rathnapandi** [comment]
Hi @jschutte27, 

Can you please share the logs as I could not reproduce the issue. 
The backendBasepath should not contain context path. it should be https://server.example.com

**Comment by jschutte27** [comment]
I was using this changelog entry to determine how to use backendBasepath:  https://github.com/Axway-API-Management-Plus/apim-cli/releases/tag/1.12.3
It looks like the basepath should be "backendBasepath" + servers.url, but when I specify a path on backentBasepath it is duplicated.  

I tested with servers.url set to a value and it still ended up duplicating the path on backendBasepath so the swagger servers.url = null doesn't matter like I assumed before.
with
- backendBasepath = https://backendserver.xxxxxxxxx.com/testpath
- servers.url = /ordermanagement

the backend was set to:
https://backendserver.xxxxxxxxx.com/testpath/testpath/ordermanagement


Here is a debug log with backendBasepath set to https://backendserver.xxxxxxxxx.com/ordermanagement and no servers block in the swagger.  This set the backend path in api manager to https://backendserver.xxxxxxxxx.com/ordermanagement/ordermanagement

[double paths.log](https://github.com/Axway-API-Management-Plus/apim-cli/files/10787623/double.paths.log)

**Comment by rathnapandi** [comment]
Hi @jschutte27, 

As mentioned in the release notes, defect fix #299 introduced the new behavior from version 1.12. 3. 

1. If open api servers.url is /api/v3 and backendBasepath is https://backend/, the openapi server.url will be replaced with https://backend/api/v3
 >> The above one to adhere open API specification ( **If the server URL is relative, it is resolved against the server where the given OpenAPI definition file is hosted (more on that [below](https://swagger.io/docs/specification/api-host-and-base-path/#relative-urls)).** - Ref - https://swagger.io/docs/specification/api-host-and-base-path/) 
2. If open api servers.url is https://petstore.swagger.io/api/v3 and backendBasepath is https://backend, the openapi server.url is untouched and frontend API basepath will be set as https://backend instead of https://petstore.swagger.io.

API Manager proxy response. 
```
"serviceProfiles": {
            "_default": {
                "apiId": "28e3d0d8-2dfc-4009-82e5-333dcc5b4ed7",
                "basePath": "https://backend"
            }
        }
```
3. If open api servers.url is https://petstore.swagger.io/api/v3 and backendBasepath is https://backend/api,  the openapi server.url is untouched and frontend API basepath will be set as https://backend/api instead of https://petstore.swagger.io.
API Manager proxy response. 
4. If there are multiple servers section in open api specification, it will keep the first one and ignore the remaining as API manager does not support multiple backends. 

For your use case the backendBasepath should be https://backendserver.xxxxxxxxx.com. 

Please do let me know if it clarifies your concerns.

**Comment by jschutte27** [comment]
I need the backend URL to be https://backendserver.xxxxxxxxx.com/ordermanagement in api manager when the swagger servers.url is either null or /. 

With 1.12.3 I was able to use a backendBasepath of https://backendserver.xxxxxxxxx.com/ordermanagement and it would set the backend url to https://backendserver.xxxxxxxxx.com/ordermanagement as desired.  Now with 1.13.3 and that configuration the backend url is set to https://backendserver.xxxxxxxxx.com/ordermanagement/ordermanagement.

It works correctly if we do not provide a path in the backendBasepath and the swagger servers.url is correct, but when the swagger servers.url value isn't what we need that doesn't work for us.

This was working with 1.12.3 and I feel like it is a bug in 1.13.3.

**Comment by rathnapandi** [comment]
Hi @jschutte27, 

The issue has been fixed.  Can you test your use case with 
[axway-apimcli-1.13.4-SNAPSHOT.tar.gz](https://github.com/Axway-API-Management-Plus/apim-cli/files/10805736/axway-apimcli-1.13.4-SNAPSHOT.tar.gz)

**Comment by jschutte27** [comment]
Thanks @rathnapandi,  this snapshot fixes it when servers.url is present, but when servers.url is null it still duplicates the path provided in backendBasepath.

With servers.url = null and backendBasepath set to https://server.example.com/testpath, Api manager ended up with https://server.example.com/testpath/testpath. 

Perhaps if servers.url is null you can set it to "/" to fix the remaining issue?

For context, when the swagger is generated at compile time (instead of runtime) it doesn't include server.url.

**Comment by jschutte27** [comment]
Hi Rathnapandi, 

Sorry for the delay.  I was able to test this today and it appears to solve the issues.  Thanks.

I noticed one strange thing.  When the backendBasepath contains a host and path (https://server.example.com/path) the backend url in api manager ends up with a trailing slash but if the backendBasepath is just the host (https://server.example.com) the backend url does not have a trailing slash.  This doesn't seem to cause any issues, but is slightly different behavior.

When do you anticipate releasing 1.13.4?

**Comment by rathnapandi** [comment]
No issues and thanks @jschutte27 for testing it, i will validate the / issue.  

Currently testing APIM CLI with Feb 2023 APIM release. The release is planned on March 1st / before.
