### ISSUE TITLE
apim-cli and load balancer sessions

### ISSUE THREAD

**Issue by jonatiao** [Axway-API-Management-Plus/apim-cli#353]
### APIM-CLI version

1.6.7-1

### API-Management version

lastest

### Question

Hello,

We have an axway installed in HA mode(2 nodes), basically we replicate the database configs(cassandra) between both nodes, which takes some time to replicate, of course, like seconds.
The api gw are active-active.

Our infra is the following:

internet -> LB(round robin) -> apigw1 OR apigw2 -> services..

It works fine today, but, we send our api config requests directly to just one of those nodes, apigw1 or apigw2.
I wonder if we could use the LB to send requests by controlling maybe the session towards apimgr endpoint.

like:
apim-cli -> LB(TCP session sticky) -> apigw1 OR apigw2

So my question is.
apim-cli, when running it's api calls towards apimgr, will create several tcp/http channels or it will use only one channel, so we could use LB sticky session?
if not, there's any other way we could control this session and or use sticky sessions or any different apim-cli or LB config maybe?

thx!!

**Comment by rathnapandi** [comment]
Hi @jonatiao, 

Based on my test I do see one TCP connection to API manager. But I would recommend to setup a sticky session on http protocol as APIM CLI uses http session-based authentication. 

Press [CTRL+C] to stop..
tcp4       0      0  10.129.232.74.61877    10.129.61.129.8075     SYN_SENT
Press [CTRL+C] to stop..
Press [CTRL+C] to stop..
tcp4       0    516  10.129.232.74.61880    10.129.61.129.8075     ESTABLISHED
Press [CTRL+C] to stop..
tcp4       0    531  10.129.232.74.61885    10.129.61.129.8075     ESTABLISHED
Press [CTRL+C] to stop..
tcp4       0      0  10.129.232.74.61892    10.129.61.129.8075     ESTABLISHED
Press [CTRL+C] to stop..
tcp4       0      0  10.129.232.74.61895    10.129.61.129.8075     ESTABLISHED
Press [CTRL+C] to stop..
tcp4       0      0  10.129.232.74.61895    10.129.61.129.8075     ESTABLISHED
Press [CTRL+C] to stop..
tcp4       0      0  10.129.232.74.61895    10.129.61.129.8075     ESTABLISHED
Press [CTRL+C] to stop..
tcp4       0      0  10.129.232.74.61895    10.129.61.129.8075     ESTABLISHED
Press [CTRL+C] to stop..
tcp4       0      0  10.129.232.74.61895    10.129.61.129.8075     ESTABLISHED
Press [CTRL+C] to stop..
tcp4       0      0  10.129.232.74.61895    10.129.61.129.8075     ESTABLISHED
Press [CTRL+C] to stop..
tcp4       0      0  10.129.232.74.61895    10.129.61.129.8075     ESTABLISHED
Press [CTRL+C] to stop..
tcp4       0      0  10.129.232.74.61895    10.129.61.129.8075     ESTABLISHED
Press [CTRL+C] to stop..
tcp4       0      0  10.129.232.74.61895    10.129.61.129.8075     ESTABLISHED
