### ISSUE TITLE
Field BackendBasePath in api-config.json not used 

### ISSUE THREAD

**Issue by piglab** [Axway-API-Management-Plus/apim-cli#354]
### APIM-CLI version

1.13.3

### API-Management version

7.7.0

### Bug description

Hi,
I just upgraded to 1.13.3 from 1.11 , and there is a fix in this version that actually breaks the API imports that were working before.
I use the field **BackendBasepath** in api-config.json to set the path of the backend API, but at the end, the field in the swagger file is not updated with my value, and it keeps the value that was set by the developer in the swagger file.

Does it mean this field is not used anymore ?  Or do I miss someting ?

In my case, I need to override the one in the swaggerfile because I go through 2 axway gateways from DMZ to Internal, and backend enpoint for DMZ gateway needs to be change to Internal Gateway endpoint

thanks,

Olivier

PS - Maybe, the break is actually related to 1.12.3 reelase which comes with a change also on the backendbasepath option

### Steps to reproduce

Execute command api API import with the field BackendBasePath filled in the file api-config.json.

Expected : In the Backend API path, the value is the value of the field BackendBasePath, and not the value of the field servers[].url that was set by the developer.

**Comment by rathnapandi** [comment]
Hi Olivier, 

Your observations are correct.  To adhere to the open api specification, the specification/openapi changed in two use cases. 

1. If the open api server URL is relative, it is resolved against the server where the given OpenAPI definition file is hosted 
2. If the open api servers array is not provided or is empty, the server URL defaults to /.

Defect fix https://github.com/Axway-API-Management-Plus/apim-cli/issues/299 introduced the new behavior from version 1.12.3.

- If open api servers.url is /api/v3 and backendBasepath is https://backend, the openapi server.url will be replaced with https://backend/api/v3
The above one to adhere open API specification (If the server URL is relative, it is resolved against the server where the given OpenAPI definition file is hosted (more on that [below](https://swagger.io/docs/specification/api-host-and-base-path/#relative-urls)). - Ref - https://swagger.io/docs/specification/api-host-and-base-path/)

- If open api servers.url is https://petstore.swagger.io/api/v3 and backendBasepath is https://backend, the openapi server.url is untouched and frontend API basepath will be set as https://backend instead of https://petstore.swagger.io.
API Manager proxy response.

```
"serviceProfiles": {
            "_default": {
                "apiId": "28e3d0d8-2dfc-4009-82e5-333dcc5b4ed7",
                "basePath": "https://backend"
            }
        }
```
- If open api servers.url is https://petstore.swagger.io/api/v3 and backendBasepath is https://backend/api, the openapi server.url is untouched and frontend API basepath will be set as https://backend/api instead of https://petstore.swagger.io/.
API Manager proxy response.
```
   "serviceProfiles": {
            "_default": {
                "apiId": "aff6b33b-10ec-4e52-a2e7-25fa81f92cf3",
                "basePath": "https://backend/api"
            }
        }
```
- If there are multiple servers section in open api specification, it will keep the first one and ignore the remaining as API manager does not support multiple backends.

Can you do anything on your side to overcome the issue? If not, please do let me know. 

Thanks
Rathna

**Comment by piglab** [comment]
Hi,

thanks for your answer. I have 2 questions :

1 - I wonder if I'm supposed to use this version of the CLI for our Axway gateway 7.7.0 version. Maybe I should roll back to 1.11. 
Any thoughts on that ?

Also, I'n mot sure I understand it well in the 3 examples you give. 

2- Is there any way to change servers.url each time I deploy ? 
I could use a tool like JQ to edit the swagger json file as a workaround, but I would prefer another way, without havving to download the swagger file in my pipeline, change it, and then importing it.


best regards,

Olivier

**Comment by rathnapandi** [comment]
Hi Olivier, 
Check out Quality assurance process section under https://github.com/Axway-API-Management-Plus/apim-cli for APIM CLI and APIM version support matrix. 
The example describes how CLI works with backendbasepath and open api servers.url. 

I will fix the issue in next release (overriding basepath in specification) do you use swagger 2.0 or openapi?

**Comment by piglab** [comment]
thank you for the upcoming fix  @rathnapandi 
In this case, it is  "openapi": "3.0.1"
But, we have also older versions deployed, and also soap services on the gateway.

**Comment by rathnapandi** [comment]
Hi @piglab, 

Could you please test your use case with the binary 
[axway-apimcli-1.13.5-SNAPSHOT.tar.gz](https://github.com/Axway-API-Management-Plus/apim-cli/files/10917901/axway-apimcli-1.13.5-SNAPSHOT.tar.gz)

**Comment by piglab** [comment]
thanks a lot, 
I come back to you asap with the test results

**Comment by piglab** [comment]
I work on it today

**Comment by piglab** [comment]
### Here is the result of my 1st test on our internal Gateway :

The swagger I import is the same. the top is like this :

{
  "openapi": "3.0.1",
  "info": {
    "title": "SIG et Moi - Mobile app API",
    "description": "Use this API to get all customer data for the 'SIG et Moi' mobile app.",
    "version": "v1"
  },
  "servers": [
    {
      _**"url": "http://v477.dev.sig-ge.ch/Api_CustomersMobileApp"**_
    }
  ],
  "paths": { ...

### The CLI command is :

` exec bash '/home/tfs/agent/_work/97/s/apim-cli-1.13.5-SNAPSHOT/scripts/apim.sh' - - api import  - --apidefinition http://v477.dev.sig-ge.ch/Api_CustomersMobileApp/swagger/v1/swagger.json  - --config ../DevopsTemplates/axway/api/rest-noauth/api-config.json - --host v961.sig-ge.ch  - --username apiadmin  - --password ***  - -port 8075  - -force -ignoreCache -clientAppsMode add -overrideSpecBasePath`


Full CLI Output log is in the file 

### Result in Axway  :  

Frontend API has a duplicate in the outbound url :

![image](https://user-images.githubusercontent.com/23016287/224249340-a56aa0cf-8be1-44d2-bcca-d77f56098eb4.png)

Mobile API was created with this resource path : 
![image](https://user-images.githubusercontent.com/23016287/224249566-cf81c31c-8bcb-4420-980a-26a6e9b8fcc9.png)


Expected to have this field empty, as it was in previous version.

Maybe I need to change command args ?

I continue on the next test, which is basePath override on the external Gateway

**Comment by piglab** [comment]
[dock.txt](https://github.com/Axway-API-Management-Plus/apim-cli/files/10939603/dock.txt)

**Comment by piglab** [comment]
Test on External Gateway : 

The command is
`exec bash '/home/tfs/agent/_work/97/s/apim-cli-1.13.5-SNAPSHOT/scripts/apim.sh' - - api import  - --apidefinition http://v477.dev.sig-ge.ch/Api_CustomersMobileApp/swagger/v1/swagger.json  - --preserve-subscriptions - --config ../DevopsTemplates/axway/api/rest-ext-passthrough/api-config.json - --host v960.sig-ge.ch  - --username apiadmin  - --password ***  - -port 8075  - -force -ignoreCache -overrideSpecBasePath -clientAppsMode ignore
`

The swagger is the same as above
Looks like it was correctly overriden, but with the wrong backen path at the end. Should be **https://api-dev-int.sig-ge.ch/mobile-app/v1**

![image](https://user-images.githubusercontent.com/23016287/224254027-56b5a6aa-928a-401d-bd17-2a5d3f7732dc.png)


Backend API is : 
![image](https://user-images.githubusercontent.com/23016287/224254255-e779c18b-245a-4e3d-ad84-e57a48876e57.png)

**Comment by piglab** [comment]
Here are the results of my test  :  

It looks like the backend Base Path is overriden as expected, but, at the end the endpoint is not correct, because it adds a suffix in the path.

My swagger file is : 

{
  "openapi": "3.0.1",
  "info": {
    "title": "SIG et Moi - Mobile app API",
    "description": "Use this API to get all customer data for the 'SIG et Moi' mobile app.",
    "version": "v1"
  },
  "servers": [
    {
      **"url": "http://v477.dev.sig-ge.ch/Api_CustomersMobileApp"**
    }
  ],
  ...

server url ends with Api_CustomersMobileApp

When I import API to Gateway, I expect the outbounf backend url  to be

https://api-dev-int.sig-ge.ch/mobile-app/v1

But I get https://api-dev-int.sig-ge.ch/mobile-app/v1/Api_CustomersMobileApp
![image](https://user-images.githubusercontent.com/23016287/224270635-37c6de57-018e-42c1-b857-af62b7b5e344.png)

Command is 

`exec bash '/home/tfs/agent/_work/97/s/apim-cli-1.13.5-SNAPSHOT/scripts/apim.sh' - - api import  - --apidefinition http://v477.dev.sig-ge.ch/Api_CustomersMobileApp/swagger/v1/swagger.json  - --config ../DevopsTemplates/axway/api/rest-ext-passthrough/api-config.json - --host v960.sig-ge.ch  - --username apiadmin  - --password ***  - -port 8075  - -force -ignoreCache -overrideSpecBasePath -clientAppsMode add
`

Full log is in attached file

API Config file is : 

{
  "name": "Mobile App API",
  "path": "/mobile-app/v1",
  "state": "unpublished",
  "version": "v1",
  "organization": "SIG",
  "summary": "Mobile BFF Api",
  "image": "api-image.jpg",
  "descriptionType": "manual",
  "descriptionManual": "This API is a BFF API for SIG Mobile app. It contains operations for ... ",
  "tags": {
    "deployment": [
      "AzureDevops",
      "Mobile",
      "REST"
    ]
  },
...


[pipeline-log-api.txt](https://github.com/Axway-API-Management-Plus/apim-cli/files/10940309/pipeline-log-api.txt)

**Comment by piglab** [comment]
Ok, I'll try this next week. Thanks for your support and quick responses.

**Comment by piglab** [comment]
I try the latest version.
1st step, I remove the API in Axway API Manager GUI.
Log is in attached file

Result is the backend url is not overriden : 
![image](https://user-images.githubusercontent.com/23016287/224913768-beebd89f-db3e-4929-a8bb-b9e5231a3f44.png)

Frontend is : 
![image](https://user-images.githubusercontent.com/23016287/224913908-50d7fa6a-108e-43a6-877a-93026ed1a063.png)

Command is : 

`exec bash '/home/tfs/agent/_work/86/s/apim-cli-1.13.5-SNAPSHOT/scripts/apim.sh' - - api import  - --apidefinition http://v477.dev.sig-ge.ch/Api_CustomersMobileApp/swagger/v1/swagger.json   - --config ../DevopsTemplates/axway/api/rest-ext-passthrough/api-config.json - --host v960.sig-ge.ch - --username apiadmin - --password *** - -port 8075 - -overrideSpecBasePath - -force - -ignoreCache - -clientAppsMode add`


Same result with command : 

`exec bash '/home/tfs/agent/_work/86/s/apim-cli-1.13.5-SNAPSHOT/scripts/apim.sh' - - api import  - --overrideSpecBasePath - --apidefinition http://v477.dev.sig-ge.ch/Api_CustomersMobileApp/swagger/v1/swagger.json   - --config ../DevopsTemplates/axway/api/rest-ext-passthrough/api-config.json - --host v960.sig-ge.ch - --username apiadmin - --password *** - -port 8075 - -ignoreCache - -force - -clientAppsMode add`

(one more hyphen)

**Comment by rathnapandi** [comment]
@piglab 

Can you share the logs?

**Comment by rathnapandi** [comment]
Hi @piglab 
Also, i do see different checksum values for the file attached in github and my local copy.  Reuploading the file. https://github.com/Axway-API-Management-Plus/apim-cli/files/10970244/apimcli-13.5.-test.tar.gz

**Comment by jonatiao** [comment]
Hello guys,
We are using apimcli 1.13.4. 
We can see in the GUI that the host really does not change as it keeps the "https://localhost:8080" that we have in the swagger(openapi 3.0.1), but when we call "apimcli api get .. -ultra", it shows the correct "Backend".

Do you see the same behavior?

**Comment by rathnapandi** [comment]
Hi @jonatiao , 

the expected behavior of CLI https://github.com/Axway-API-Management-Plus/apim-cli/issues/354#issuecomment-1447142208. If you see any issue reopen / create an issue.
