### ISSUE TITLE
Application Client

### ISSUE THREAD

**Issue by piglab** [Axway-API-Management-Plus/apim-cli#360]
### APIM-CLI version

1.13.2

### Question

Hello,

When I import an API that already exist, sometimes it happens that the existing client applications loose their subscription to this API. Sometimes, not. It looks like when the API is recreated, it is the case, but not sure.

- Could you explain what is the rule in the CLI to trigger an API deletion + creation ? is it when there is any change in the swagger file ?
- Would you recommend to add the 'applications' field in api-config.json to make sure he application has access to the API. I do not do it today, but maybe I should.

thanks,

Olivier

**Comment by rathnapandi** [comment]
Hi @piglab, 

Can you share CLI command used? I will get back to you with the details.

**Comment by rathnapandi** [comment]
Hi @piglab, 

Based on your log, it detects changes to API specification ( open api document ),  it creates a new API and deletes the existing API.  As you set the flag -clientAppsMode ignore, it does not copy the subscription from old API. 

Remove -clientAppsMode ignore, it will copy the existing application from old API. You can also add an applications section to have more control.
