### ISSUE TITLE
apim does not import the whole chain in a PEM certificate

### ISSUE THREAD

**Issue by jonatiao** [Axway-API-Management-Plus/apim-cli#361]
### APIM-CLI version

latest

### API-Management version

latest

### Question

Hello,

Let's say I get a whole chain certificate from a server using the command:
`openssl.exe s_client -connect google.com:443 -showcerts < /dev/null 2>&1 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > cert.pem`
This will give me a chain of certs, in this case we will have 3 certs.

Then I use axway api manager GUI's "trusted certificate" interface to import this cert.pem. It will show me 3 certs, the root, intermediate and CA.
But when I try to do the same using the api-config.json:
`"caCerts":[
   {
      "certFile":"cert.pem",
      "useForOutbound":true,
      "useForInbound":false
   }]`

It does not work, only the root is imported.
I can workaround this by breaking the file into 3 pieces and then adding new objects to the array, still, it's easier to have all 3 in one file.
There's anything I could do using api-cli to have the same behavior as the GUI? I mean, importing one file with the whole chain?

thx!

**Comment by jonatiao** [comment]
Oh, thx @rathnapandi for the fast response!

I read the docs and I did not saw how the release process works.
Do you mind to share when this fix will be released?

thx

**Comment by rathnapandi** [comment]
Hi @jonatiao, 
Will release it before the end of this week.  
Normally the APIM CLI is released after API Gateway is released.

**Comment by jonatiao** [comment]
Hey @rathnapandi 
Any news on 1.13.5 release date. We are also interested in https://github.com/Axway-API-Management-Plus/apim-cli/issues/354. : )
