### ISSUE TITLE
no way to export all certificates

### ISSUE THREAD

**Issue by acirami** [Axway-API-Management-Plus/apim-cli#375]
### Problem description

we need to export all certificates and when the expire

### Feature request

a way to export all certificates.

**Comment by rathnapandi** [comment]
@acirami the certificates are managed as part of APIs. 

For expiry json report refer https://github.com/Axway-API-Management-Plus/apim-cli/issues/374#issuecomment-1491151904

**Comment by rathnapandi** [comment]
duplicate of #374
