### ISSUE TITLE
Password encryption in API export

### ISSUE THREAD

**Issue by piglab** [Axway-API-Management-Plus/apim-cli#377]
### APIM-CLI version

1.13.5

### Question

How is it possible to export the API configuration file without encryption in Api Manager GUI ?
When I export with the CLI, it's decrypted.
When I export from the GUI, there is an encryption, asking for a password.
I don't understand why.

**Comment by rathnapandi** [comment]
Hi @piglab, 

There is an equivalent operation in CLI which you are referring to in API Manager UI. 

```./apim.sh api get -n "petstore-override"  -u apiadmin -p changeme -h 10.129.61.129  -o dat -datPassword axway -deleteTarget```

The above command calls a REST API  https://10.129.61.129:8075/api/portal/v1.4/proxies/export which provides encrypted response. 

If we don't use the flag -o dat, it will call different set of REST APIs to access Frontend and Backend API to create a JSON output file.
