### ISSUE TITLE
updateonly option

### ISSUE THREAD

**Issue by GillesDumond** [Axway-API-Management-Plus/apim-cli#388]
### APIM-CLI version

1.13.7

### API-Management version

20230228

### Bug description

The updateonly option is not working anymore

We were previously using the 1.7 CLI and have updated to CLI 1.13.7 because we are actually migrate to the february 2023 API Manager version.

### Steps to reproduce

Try to publish an API with the updateonly option 

- A first API is published manually in the APIM IHM
- Export the api with the cli cmd
-  Import the same API with the updateonly option

The import failed with a 'Breaking changes error'

**Comment by rathnapandi** [comment]
Hi @GillesDumond, 
Can you share the debug log?
