### ISSUE TITLE
Application download fails if multiple SharePermissions are assigned

### ISSUE THREAD

**Issue by lreeb** [Axway-API-Management-Plus/apim-cli#389]
### APIM-CLI version

1.13.3

### API-Management version

7.7.20211130

### Bug description

I have an application with multiple SharePermissions, all users have permission "manage". After upgrading to the newest APIM-CLI, I can't download the application data with `apim app get` any longer, with the error message: 
`Cannot coerce empty String ("") to 'com.axway.apim.api.model.apps.ApplicationPermission$SharePermission' value`

However if I delete all but one user from the "Sharing" permissions, it works without error.

### Steps to reproduce

* Create an application "my-application" in Axway Manager UI
* In "Sharing", specify multiple users with permission "Manage"
* Try to download this application via `apim app get --output json --name "my-application"`

### Relevant log output

```shell
Error reading application permissions. Error: Cannot coerce empty String ("") to `com.axway.apim.api.model.apps.ApplicationPermission$SharePermission` value (but could if coercion was enabled using `CoercionConfig`)
```

**Comment by rathnapandi** [comment]
Hi @lreeb, 
It's working fine on the latest CLI version with APIM release 7.7.20221130. 
Can you test it with the latest CLI version (1.13.7)?

**Comment by lreeb** [comment]
Hi @rathnapandi, 
Thanks for the quick response. I can confirm that it works with the latest version 1.13.7, so closing this issue!
