### ISSUE TITLE
[Bug] property apiMethodId contains UUID after export instead of a path value - import fails

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#39]
**API-Mgr. CLI version**
1.1.0

**API-Manager and Service-Pack Version**
7.6.2 SP4

**Expected behavior**

**Actual behavior**
I configured a per method override and did an export as JSON via "apim api get -id ... -o json".
The import again seems to work but is inconsistent as the Backend API service URL is now an id instead of a path.
Checking the exported api config file, I assume there was a change in the property apiMethodId which change from a path value to a UUID.

**Log-Output in Debug**

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by cwiechmann** [comment]
Improved existing integration test to validate the API-Method-Id is NOT exported and added a Jackson filter for Outbound- and Inbound-Profiles. 
This issues is fixed in version 1.2.0

**Comment by jschaefer77** [comment]
hi @cwiechmann , thx. When do you release version 1.2.0

**Comment by cwiechmann** [comment]
Latest the 17th of June 1.2.0 will be released

**Comment by jschaefer77** [comment]
Hi @cwiechmann, I don't understand why the API-Method-Id is not necessary in the export anymore. Anyway if I run an import with CLI version 1.2.0 using the exported config file I can see in the cli output, that the import was successful. But in API Manager UI (V7.7.20200530) I am not able to open the outbound -> per-method-override. I get an forbidden error. I assume, the import created some inconsistencies. How can this issue reopened?

**Comment by cwiechmann** [comment]
@jschaefer77, The UUID Method-ID is internal and is different on each state, hence it cannot be exported and re-imported. The key to declare Method-Configuration is the "external" Operation-ID. That means, the Operation-ID, such as `findPetsByStatus` must be present in the export.
See here: https://github.com/Axway-API-Management-Plus/apim-cli/wiki/2.1.11-Method-level-overrides

**Comment by jschaefer77** [comment]
Hi @cwiechmann , thanks a lot for the explanation. Yes, I can confirm that the Operation-ID is present in the export. But there is still the issue, that the import then seems to creates some inconsistencies. The per-method-override cannot be opened in API Manager UI because of an error.

**Comment by cwiechmann** [comment]
I just tested it locally with a 7.6.2 SP4 and it looks good so far. 
This is the API Inbound config Method-Override for method addPet:
![image](https://user-images.githubusercontent.com/16292002/87922676-9c953100-ca7c-11ea-9286-20ff820d5aff.png)

And this the Outbound config for method deleteOrder:
![image](https://user-images.githubusercontent.com/16292002/87922777-c2223a80-ca7c-11ea-8499-4b4c4f4a861b.png)

And this results into the following API-Config-File:
![image](https://user-images.githubusercontent.com/16292002/87922370-314b5f00-ca7c-11ea-8096-5ae265d8ba06.png)

To test it further, I have deleted the API and re-imported it. All good. I can also open the Method-Override:
![image](https://user-images.githubusercontent.com/16292002/87922892-e41bbd00-ca7c-11ea-900a-eead6be27003.png)

:warning: Please make sure, that you Reload the API-Manager UI to reload the API state.

**Comment by jschaefer77** [comment]
Hi @cwiechmann, yes if I test with 7.6.2 I get the same error as you did. I tested as well with V7.7.20200530 and with that version I cannot open anymore the per-method-override. I just get "Error - Forbidden".

I don't know why, but I am not able to add any image to issues in this repo. Did you disable this?

**Comment by cwiechmann** [comment]
Okay. Thanks for the confirmation. I will create an issue for that problem and will fix that as soon as possible.

**Comment by cwiechmann** [comment]
I haven’t disabled the option in GitHub to upload images.

**Comment by cwiechmann** [comment]
@jschaefer77, I have created another issue: #50. I improved the Integration- and Unit-Test and made a fix. 
In issue #50 I attached a SNAPSHOT-Version that includes the fix. Can you please validate it's working as expected from your side and share feedback? Thanks!

Please comment on issue #50.
