### ISSUE TITLE
Support 7.7 May 2023 release 

### ISSUE THREAD

**Issue by rathnapandi** [Axway-API-Management-Plus/apim-cli#391]
### Problem description

Support 7.7 May 2023 release 

### Feature request

Support 7.7 May 2023 release

**Comment by jschutte27** [comment]
Is this broken on 20230530 or will the existing version work?  I haven't tested it, but we may need to upgrade soon.

**Comment by rathnapandi** [comment]
Hi @jschutte27,
The existing version won't work.
