### ISSUE TITLE
Existing Client Applications are lost

### ISSUE THREAD

**Issue by piglab** [Axway-API-Management-Plus/apim-cli#396]
### APIM-CLI version

1.13

### API-Management version

7.7.0

### Question

Each time I import a new version of the API, depending on the changes, I loose the existing Client application subscriptions.
If I change the inbound security sheme for example, then, the API at import is deleted and re-created.
On some APIs, we have manys clients.

Is there a way to keep track of existing subscritpions and reappling it at the end of the import ?
Or is there any recommendation on how to manage the subscriptions ?

thank you,

Olivier

**Comment by dmchughaxway** [comment]
Are you setting the zero downtime flag to true when making API changes?

See https://github.com/Axway-API-Management-Plus/apim-cli/wiki/FAQ#are-apis-updated-with-zero-downtime

**Comment by rathnapandi** [comment]
Not an issue.
