### ISSUE TITLE
breaking changes with ovverideSpecBasePath = true

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apim-cli#397]
### APIM-CLI version

1.13.7

### API-Management version

7.7.20211130

### Bug description

I have updated the apim-cli version from 1.13.0 from 1.13.7 facing some breaking changes introduced with the **ovverideSpecBasePath** property.

Consider the following situation:
base path in swagger 2: /test
backendBasePath in json config file: https://host/something

with 1.13.0 the output backend endpoint is: https://host/something [CORRECT]
with 1.13.7 (ovverideSpecBasePath =false)the output backend endpoint is: https://host/something/test [INCORRECT]

So I set the ovverideSpecBasePath property = true 

with 1.13.0 the output backend endpoint is: https://host/something [CORRECT]
with 1.13.7 (overrideSpecBasePath=true) the output backend endpoint is: https://host/something [CORRECT]

this situation is now correct but this configuration breaks another kind of scenario:

base path in swagger 2: /test2
backendBasePath in json config file: https://host2 
(only host, no relative path)

with 1.13.0 the output backend endpoint is: https://host2/test2 [CORRECT]
with 1.13.7 (ovverideSpeceBasePath=true) the output backend endpoint is: https://host2/ [INCORRECT]

in my opinion this case is not handled correctly.

the overrideSpecBasePath property must have a specific meaning.

it the backendBasePath in json config file has a value with a base path I can ovveride the swagger, otherwise not.

example:
backendBasePath in json config file = **https://host2** and overrideSpecBasePath = **true** :  I don't override anything because in backendBasePath there is no relative path.

backendBasePath in json config file = **https://host2/** (final slash) and overrideSpecBasePath = **true** :  I override the base path in swagger with / 

Moreover the wiki page https://github.com/Axway-API-Management-Plus/apim-cli/wiki/2.1.2-API-Configuration-file#parameter-backendbasepath is completely outdated!

What do you think  @rathnapandi ?

**Comment by rathnapandi** [comment]
@gcornacchia I agree with you and will update wiki page as well.

**Comment by gcornacchia** [comment]
thanks @rathnapandi, when are you going to release 1.13.8 version?

**Comment by rathnapandi** [comment]
First week of July.

**Comment by gcornacchia** [comment]
hi @rathnapandi, we absolutely need 1.13.8 version :)

**Comment by rathnapandi** [comment]
Hi @gcornacchia, issue #322 is taking lot of time along with May release update. I will try to release it at the earliest.

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

I will do the release tomorrow.
