### ISSUE TITLE
No change is returning RC 0 instead of RC 10

### ISSUE THREAD

**Issue by jonatiao** [Axway-API-Management-Plus/apim-cli#401]
### APIM-CLI version

1.13.7

### API-Management version

latest

### Bug description

During the import of an API we receive:

No changes detected. Existing with RC: 0

According to errorCode.java I believe it should be 10:

NO_CHANGE(10, "No change between desired and actual API has been detected.", false, LogLevel.WARN),

### Steps to reproduce

Try to import a api that already exists.

**Comment by rathnapandi** [comment]
Hi @jonatiao, 

Can you share the logs?

**Comment by rathnapandi** [comment]
Fixed in v1.14.1

**Comment by jonatiao** [comment]
> Hi @jonatiao,
> 
> Can you share the logs?

OH my, I'm really sorry, I lost your question!
Ok, thx for fixing. I believe this may break some pipelines mainly because we are changing this from rc 0 to 10. I hope ppl read the changelogs before downloading the new version.  ^^
