### ISSUE TITLE
question regarding system quota on all api 

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apim-cli#402]
### APIM-CLI version

1.13.7

### API-Management version

7.7.20211130

### Question

hi @rathnapandi,
looking at the importing of global system or application default quotas (introduced in 1.13.6) I've found that you have modelled the restriction in JSON as a single object field (systemQuota or applicationQuota).

{
  "quotas": {
    "systemQuota": {
      "method": "*",
      "type": "throttle",
      "config": {
        "messages": "10000",
        "period": "second",
        "per": "1"
      },
      "api": "*"
    },
    "applicationQuota": {
      "method": "*",
      "type": "throttle",
      "config": {
        "messages": "1000",
        "period": "second",
        "per": "2"
      },
      "api": "*"
    }
  }
}

in the API Manager web interface, you can create several system quotas with different types (mb or messages) or time units (days, hours, seconds).

![image](https://github.com/Axway-API-Management-Plus/apim-cli/assets/15086835/230d9012-33de-4c3d-9afe-7a5bf1740188)

I think this situation is not handled via apim-cli as in JSON config file there is only one restriction and not a list.

Am I right?

Was it something you thought about?

thanks

**Comment by rathnapandi** [comment]
Hi @gcornacchia, your observations are correct. it does not handle multiple entries.
