### ISSUE TITLE
[BUG] Documentation issue in How to get started

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#41]
**API-Mgr. CLI version**
1.1.0

**API-Manager and Service-Pack Version**
N/A

**Expected behavior**

**Actual behavior**
The described way in Option 1 by adding the Short-Cut-Folder to the PATH does not work.
e.g. adding just "C:\Axway\Tools\apim-cli" to the PATH works, but adding "C:\Axway\Tools\apim-cli\scripts" does not.
If you try to open "C:\Axway\Tools\apim-cli\scripts" in windows explorer you will get an error.

**Log-Output in Debug**

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by jschaefer77** [comment]
hi @cwiechmann, could you please quickly check this issue. It seems that the mentioned option 1 with the sort cut folder does not work on windows.

**Comment by cwiechmann** [comment]
Yes, you are right. I already tried to figure out a better approach, but no luck so far.
If you have an good recommendation I'm really happy if you could share it here.

**Comment by cwiechmann** [comment]
I have updated this part of the documentation to use the environment variable AXWAY_APIM_CLI_HOME and define the path based on that.
