### ISSUE TITLE
Add revoke API access command from Org/Application

### ISSUE THREAD

**Issue by Yamini1808** [Axway-API-Management-Plus/apim-cli#419]
### Problem description

I am writing to submit a feature request for the enhancement of the APIM CLI tool, specifically to include a "Revoke API Access" command for organizations.  
I have a customer who is trying to import API configuration into API manager, so that organizations will have the API access in the API Manager portal. But after this if they want to revoke the API access from one or two organization on API manager portal (on API Access tab), they are unable to do it from APIM CLI since it doesn't offer a way to do so. 

Please see the attached screenshot by customer:
![API acces](https://github.com/Axway-API-Management-Plus/apim-cli/assets/139923207/e3479d53-941f-4542-95ed-4f371694add1)

### Feature request

It'd be great to be able to add a revoke API access command from Org/Application on APIM CLI that would make it easy to use. I believe that this addition would greatly improve the management as it could offer some benefits like enhanced security, time efficient, etc.

**Comment by rathnapandi** [comment]
fixed in v1.14.1
