### ISSUE TITLE
Methods Tags are removed if all the methods are not declared in api-config.json

### ISSUE THREAD

**Issue by jonatiao** [Axway-API-Management-Plus/apim-cli#424]
### APIM-CLI version

1.13.7

### API-Management version

7.7.20220228_1.0

### Bug description

If I have two methods createUser and logoutUser. Both have tags. If I import the API using only one method declared in the api-config.json, the TAGs in the other method gets removed.
```
 "apiMethods": [
    {
      "name": "createUser",
      "summary": "Create user",
      "descriptionType": "original",
      "tags": {
        "stage": [
          "dev"
        ]
      }
    }
  ]
```

Is this a limitation from Axway api manager or a bug?

### Steps to reproduce

Create an APi:
```
 "apiMethods": [
    {
      "name": "createUser",
      "summary": "Create user",
      "descriptionType": "original",
      "tags": {
        "stage": [
          "dev"
        ]
      }
    },
    {
      "name": "logoutUser",
      "summary": "Logs out current logged in user session",
      "descriptionType": "original",
      "tags": {
        "stage": [
          "dev"
        ]
      }
    }
  ]
```

Remove the second method and import:
```
 "apiMethods": [
    {
      "name": "createUser",
      "summary": "Create user",
      "descriptionType": "original",
      "tags": {
        "stage": [
          "dev"
        ]
      }
    }
  ]
```

Check the logoutUser method and see that the tag was removed.

**Comment by rathnapandi** [comment]
Hi @jonatiao, 

Looks like a bug, i will check and get back to you with more details. 

Thanks
Rathna

**Comment by rathnapandi** [comment]
Hi @jonatiao, 

During API import, the CLI does the following. 

1. Create backend
2. Create Frontend
3. Delete existing API if it available with same name and path. 
 Tags are being removed as tag is created as part of frontend api and not part of openapi / swagger.

In our case, CLI is creating frontend api from backend and copy the tags from api-config.json file for createUser method, as there is no logoutuser method on api-config.json it uses configuration from backend and ignoring the old tags. 

It is limitation with API manager. When we run api export command with flag useFEAPIDefinition, it does not include the frontend api method tags created in API manger. 

./apim.sh api get -n petstore3 -u apiadmin -p changeme -h 10.129.61.129 -o json -t test5 -exportMethods -useFEAPIDefinition


Please let me know if you have any questions.
