### ISSUE TITLE
Inboud Profile - OperationId

### ISSUE THREAD

**Issue by piglab** [Axway-API-Management-Plus/apim-cli#435]
### APIM-CLI version

1.14.1

### API-Management version

7.7.0

### Bug description

When importing an API with CLI : 
In the confiration file api-config.json, I define a special inboud profile for my healthcheck method, that is Pass Through

    "inboundProfiles" : {
      "_default" : {
        "monitorAPI" : true,
        "queryStringPassThrough" : false,
        "monitorSubject" : "authentication.subject.id",
        "securityProfile" : "APIKey internal and Access Token External",
        "corsProfile" : "_default"
      },
      "GET /healthcheck" : {
        "monitorAPI" : true,
        "queryStringPassThrough" : false,
        "monitorSubject" : "authentication.subject.id",
        "securityProfile" : "NoAuth for Healthcheck"
      }

It works fine, but in some cases, I get an error when importing : 

2023-09-01 08:07:03,749 [APIImportApp] ERROR: No operation found with name: 'GET /healthcheck'

I found that it occurs when the field OperationId is set in the swagger file. If I remove the field, it works.

       ...
        "/healthcheck": {
            "get": {
                "operationId": "getHealth",
                "tags": [
       ...

Problem is , I cannot remove it, because I get the swagger definition file through http, and the API deployment is a step in a CICD pipeline.

Note : If I import manually the swagger file, and then define from the GUI the PER-METHOD Override, it works fine.

Any chance to fix this ?

thanks for your support,

Olivier

### Steps to reproduce

Import API from CLI and set a special inboud profile for an operation with operationId field

**Comment by rathnapandi** [comment]
Hi @piglab, 

Can you use operation id as input profiles method key like below?


"inboundProfiles" : {
  "_default" : {
    "monitorAPI" : true,
    "queryStringPassThrough" : false,
    "monitorSubject" : "authentication.subject.id",
    "securityProfile" : "APIKey internal and Access Token External",
    "corsProfile" : "_default"
  },
  **"getHealth"** : {
    "monitorAPI" : true,
    "queryStringPassThrough" : false,
    "monitorSubject" : "authentication.subject.id",
    "securityProfile" : "NoAuth for Healthcheck"
  }

**Comment by rathnapandi** [comment]
Hi @piglab 
I am closing this one. Please reopen if it does not work for you.
