### ISSUE TITLE
add forceUpdate property in CoreParameters.java module

### ISSUE THREAD

**Issue by mbelladelli** [Axway-API-Management-Plus/apim-cli#436]
### Problem description

Hello, in the past few years my team managed a custom maven plugin used to wrap the apim-cli in order to allow only a few of the apim-cli publishing functionalities.

We are now in a situation where it would be ideal to be able to publish an API via this maven tool using the forceUpdate flag of the apim-cli.

However, the forceUpdate property cannot be found in the CoreParameters.java module - apim-cli/modules/apim-adapter/src/main/java/com/axway/apim/lib/CoreParameters.java - where all other properties such as hostname/port/force/... are located, and therefore we are unable to call the apim-cli with the forceUpdate flag direclty from the maven tool.

The plugin is currently calling apim-cli 1.13.5 but most recent version are missing the forceUpgrade property as well from the CoreParameters.java module.

### Feature request

Would it be possible to implement the forceUpdate  functionality in the apim-cli modules? Thanks in advance.

**Comment by rathnapandi** [comment]
Hi @mbelladelli, 

Can you share your maven plugin configuration section please?

**Comment by mbelladelli** [comment]
[pom.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/12534658/pom.zip)

hi @rathnapandi here's our pom.xml config file

**Comment by rathnapandi** [comment]
Thanks @mbelladelli

I do see you are creating a maven plugin, How are you invoking the CLI commands? Can you please share?

**Comment by mbelladelli** [comment]
hi @rathnapandi

by looking deeper into the apim-cli code i just found APIImportParams.class that contains a boolean forceUpdate parameter. i'll try to set this from our maven plugin configuration and let you know

**Comment by mbelladelli** [comment]
hello @rathnapandi 

there will be no need to implement the forceUpdate property into the apim-cli modules since it's already in place inside module APIImportParams.class. by using the forceUpdate parameter defined in the APIImportParams.class module i was able to successfully invoke the apim-cli with the forceUpdate option from inside my custom maven plugin

thanks for your help, the issue can be closed
