### ISSUE TITLE
Handling removing of existing quota in API

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apim-cli#438]
### APIM-CLI version

1.14.2

### API-Management version

7.7.20211130

### Bug description

After testing different scenarios in adding/removing quotas on APIs I've found a strange behavior that I describe below.

### Steps to reproduce

STEP 1) Consider an API with already 2 application default quotas and 2 system quotas as in this config file

```
...
 "applicationQuota": {
    "restrictions": [
      {
        "method": "*",
        "type": "throttle",
        "config": {
          "messages": "1000",
          "period": "second",
          "per": "1"
        }
      },
      {
        "method": "method1",
        "type": "throttle",
        "config": {
          "messages": "500",
          "period": "second",
          "per": "1"
        }
      }
    ]
  },
  "systemQuota": {
    "restrictions": [
      {
        "method": "method1",
        "type": "throttle",
        "config": {
          "messages": "9000",
          "period": "second",
          "per": "2"
        }
      },
      {
        "method": "method2",
        "type": "throttlemb",
        "config": {
          "mb": 8000,
          "period": "second",
          "per": "1"
        }
      }
    ]
  }
...
```

STEP 2) Remove one application default quota and one system quota

```
   ...
   "applicationQuota": {
    "restrictions": [
      {
        "method": "*",
        "type": "throttle",
        "config": {
          "messages": "1000",
          "period": "second",
          "per": "1"
        }
      }
    ]
  },
  "systemQuota": {
    "restrictions": [
      {
        "method": "method1",
        "type": "throttle",
        "config": {
          "messages": "9000",
          "period": "second",
          "per": "2"
        }
      }
    ]
  }
 ....
```
When importing this config file with quotaMode=replace the existing quotas on API Manager are correctly removed. OK

2023-09-05 15:23:24,258 [APIQuotaManager] INFO : Updating System default quota for API: PublicAPI_v1
2023-09-05 15:23:24,260 [APIQuotaManager] INFO : Removing existing Quotas for API: PublicAPI_v1 as quotaMode is set to replace.
2023-09-05 15:23:25,306 [APIQuotaManager] INFO : Updating Application default quota for API: PublicAPI_v1
2023-09-05 15:23:25,306 [APIQuotaManager] INFO : Removing existing Quotas for API: PublicAPI_v1 as quotaMode is set to replace.

STEP 3) I try to remove all quotas **not serializing** applicationQuota and systemQuota field in json but no differences are found

 No changes detected between Import- and API-Manager-API

But...

STEP 4.1) I try to remove only  the application quota

```
...
"systemQuota": {
    "restrictions": [
      {
        "method": "method1",
        "type": "throttle",
        "config": {
          "messages": "9000",
          "period": "second",
          "per": "2"
        }
      }
    ]
  }
...
```
The application quota is correctly removed from API Manager but I don't understand the first two lines of log (as system quotas are untouched)

2023-09-05 15:30:16,648 [APIQuotaManager] INFO : Updating System default quota for API: PublicAPI_v1
2023-09-05 15:30:16,649 [APIQuotaManager] INFO : Removing existing Quotas for API: PublicAPI_v1 as quotaMode is set to replace.
2023-09-05 15:30:17,093 [APIQuotaManager] INFO : Updating Application default quota for API: PublicAPI_v1
2023-09-05 15:30:17,094 [APIQuotaManager] INFO : Removing existing Quotas for API: PublicAPI_v1 as quotaMode is set to replace.

BUT...

STEP 4.1) After step 3 if I try to remove only the system quota instead of application quota.

```
 ...
 "applicationQuota": {
    "restrictions": [
      {
        "method": "*",
        "type": "throttle",
        "config": {
          "messages": "1000",
          "period": "second",
          "per": "1"
        }
      }
    ]
  } 
 ...
```
the system quota is not removed from API Manager

 No changes detected between Import- and API-Manager-API

Maybe there's a need for uniformity in handling the semantics of null fields (not existent in JSON input file) or fields with empty values for "applicationQuota" and "systemQuota" fields.

"applicationQuota": { 
  restrictions: [] 
}

@rathnapandi what do you think?

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 
Thanks for reporting, looks like a defect to me. I will get back to you with more details.

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

I have added some Junit test cases and existing code is working as expected.  The only place I might see the issue is

the source contains 

```json
 "applicationQuota": {
    "restrictions": [
    ]
  }
```

and destination contains

```json
 "applicationQuota": {

  }
```

it throws exception. Do you see anything different?

Please review the code  https://github.com/Axway-API-Management-Plus/apim-cli/commit/730a52f30ea4597d0dd0f9d52f077b52d1d2b31f and let me know if i miss anything?

**Comment by lturricchia** [comment]
Hello about this problem in removing existing quotas on a specific API, we see Apim-cli is working.
 we see the problem still occurs in removing GLOBAL quotas for ALL API, as in https://github.com/Axway-API-Management-Plus/apim-cli/issues/442
