### ISSUE TITLE
Filter applications based on their configured credentials

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apim-cli#44]
**User story**
It is sometimes required to select/filter applications based on their configured Application-Credentials such as the Client-ID or API-Key.

**Additional context**
This is useful as sometimes only the Client-ID is known out of logs and without that option, it is hard to know which API it is.

**Comment by cwiechmann** [comment]
Feature is implemented and will be delivered with release 1.2.0

**Comment by jschaefer77** [comment]
Hi @cwiechmann; I tested this feature. Works great if I use an API Key as credential. But if I try to filter with a client-Id it won't find the app. Was this feature intended to work for both client-ids, from "OAuth Credentials" and "External Credentials" section in API Manager?

**Comment by cwiechmann** [comment]
Hi @jschaefer77, Thanks for the feedback. I just tested this and it is working as expected.

```
C:\temp\apimcli-demo>apim app get -s api-env -credential "ClientConfidentialApp"
----------------------------------------------------------------------------------------
API-Manager CLI: 1.3.0-SNAPSHOT

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: Application - E X P O R T / U T I L S (1.3.0-SNAPSHOT)
----------------------------------------------------------------------------------------
1236   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200130) on: https://api-env:8075
Laoding 10 Applications [****------] 40%
1963   INFO  ApplicationExportApp| Found 1 application(s).
+--------------------------------------+------------+----------+----------------------+---------+
| Application-Id                       | Name       | State    | Email                | Enabled |
+--------------------------------------+------------+----------+----------------------+---------+
| 4e8634ba-6762-45ca-bbe5-7ca4e99192ac | Client App | approved | sample@sampleapp.com |    true |
+--------------------------------------+------------+----------+----------------------+---------+
```

☝️ - Perhaps the issue is caused by caching. Can you please re-run with the toggle: `-ignoreCache` or you clean the App-Credential-Cache like so: `-clearCache applicationsCredentialCache` after you have changed an application credential.

**Comment by jschaefer77** [comment]
Hi @cwiechmann; ok thanks, I got it now. It works now if I use the toggle -ignoreCache. Could you add this toggle to the help. If I run `apim app get -h` only the -clearCache option is listed in the output.

But overall, really great work. Really helpful feature.

**Comment by cwiechmann** [comment]
Thanks @jschaefer77! Yes, I will add this toggle to the usage.
