### ISSUE TITLE
Add ability to update, add or remove certificates from 1 or many APIs

### ISSUE THREAD

**Issue by acirami** [Axway-API-Management-Plus/apim-cli#450]
### Problem description

The current Process: Select API from sheet below → Login to Test Axway API Manager → Search for the API Policy on the front-end → If Policy is published unpublish → Go to the certificate tab → Upload new certificates → Save → If it was published republish.

[Manual Updating Test CKP Certs_3ea097c6bad64e44b82808a738014f9c-201223-1438-4.pdf](https://github.com/Axway-API-Management-Plus/apim-cli/files/13731560/Manual.Updating.Test.CKP.Certs_3ea097c6bad64e44b82808a738014f9c-201223-1438-4.pdf)

### Feature request

we would like to be able to specify a cert or many certs from a folder and update 1 API or many APIs.  we would also like the ability to update all APIs with a particulate tag.
or
if we can specify an existing cert attached to any API and replace it with a new one.

**Comment by rathnapandi** [comment]
Hi @acirami, 

We can write a script to handle your use case.  The script should include following. 

1. Check for expired certificates on API manager using below command. 
`./apim.sh api check-certs -o json -u apiadmin -p changeme -h 10.129.61.129 -days 30 -t test`
2. The command generates json file with api which contains expired certificates. Iterate the Json array, run export API command ( ./apim.sh api get -id ${idfromjson}), replace expired certificate by manipulating api-config.json file and import it.

**Comment by acirami** [comment]
@rathnapandi thanks for the quick response.  I am aware of the import feature; however, it is my understanding from Axway support that any modification of a published API is considered potentially breaking and requires the flag, which is why the force option is there.  When you use the force option, it creates a new API, copies the app & org access, then deletes or deprecate the old API afterwards.

The procedure outlined in the PDF I attached is not impacting.  that is why I requested just adding or replacing a certificate via the APIM CLI.

are you saying this cannot be done and the only way to do it is the method you outlined in your reply?

**Comment by rathnapandi** [comment]
Hi @acirami, 

If we follow the steps mentioned in PDF, we will lose all the consumer application and organization once we unpublished the API. 

If consuming applications  are part of API development organization, we can run the below command to unpublish 

`./apim.sh api unpublish -id xxxx -u apiadmin -p changeme -h localhost`

Once API is unpublished, we can import it with updated certificates without force. 

Please let me know if you have any questions.

**Comment by rathnapandi** [comment]
Hi @acirami, 

The  **api unpublish**  command requires uses input to continue. 

we can pass user input using following command
`echo "Y" | ./apim.sh api unpublish -n petstore3 -u apiadmin -p changeme -h 10.120.61.120`

**Comment by acirami** [comment]
> Hi @acirami,
> 
> If we follow the steps mentioned in PDF, we will lose all the consumer application and organization once we unpublished the API.
> 
> If consuming applications are part of API development organization, we can run the below command to unpublish
> 
> `./apim.sh api unpublish -id xxxx -u apiadmin -p changeme -h localhost`
> 
> Once API is unpublished, we can import it with updated certificates without force.
> 
> Please let me know if you have any questions.

are you saying using the unpublish via APIM does not lose all the consumer application and organization once we unpublished?

**Comment by acirami** [comment]
what about adding the ability to update all APIs with a particulate tag?

**Comment by rathnapandi** [comment]
> > Hi @acirami,
> > If we follow the steps mentioned in PDF, we will lose all the consumer application and organization once we unpublished the API.
> > If consuming applications are part of API development organization, we can run the below command to unpublish
> > `./apim.sh api unpublish -id xxxx -u apiadmin -p changeme -h localhost`
> > Once API is unpublished, we can import it with updated certificates without force.
> > Please let me know if you have any questions.
> 
> are you saying using the unpublish via APIM does not lose all the consumer application and organization once we unpublished?

No, unpublish operation from CLI or API manager UI, loses all consumer application ( if it requested from different org) and organizations  ( consumer orgs). 

If you want to preserve all accesses, use import command from CLI with force operation.

**Comment by rathnapandi** [comment]
> > Hi @acirami,
> > If we follow the steps mentioned in PDF, we will lose all the consumer application and organization once we unpublished the API.
> > If consuming applications are part of API development organization, we can run the below command to unpublish
> > `./apim.sh api unpublish -id xxxx -u apiadmin -p changeme -h localhost`
> > Once API is unpublished, we can import it with updated certificates without force.
> > Please let me know if you have any questions.
> 
> are you saying using the unpublish via APIM does not lose all the consumer application and organization once we unpublished?

No, unpublish operation from CLI or API manager UI, loses all consumer application ( if it requested from different org) and organizations  ( consumer orgs). 

If you want to preseerve all access, use import command from CLI with force operation. 


> what about adding the ability to update all APIs with a particulate tag?

APIM CLI gives option to fetch api based on tags, once you get all apis based on tags, you can update it as needed. 

`./apim.sh api get -tag stageTag -u apiadmin -p changeme -h 10.120.61.120 -o json`

tag parameter supports wild card search too, we can search based on taggroup too
`./apim.sh api get -tag tagGroup=*myTagValue* -u apiadmin -p changeme -h 10.120.61.120 -o json`

**Comment by rathnapandi** [comment]
Hi @acirami, 
Based on our discussion I am closing the issue.
