### ISSUE TITLE
Export feature maturity 

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#455]
### APIM-CLI version

1.14.3

### API-Management version

7.7.20231130

### Question

Hi, 
we are looking to add a tag to all the APIs we currently have, they are in between 0-500 APIs and many of them were created in API management manually, others using the export/import method, and others using apim-cli.
These APIs are also very heterogenous in what features they are. For example, they might be relying in the advanced properties of the FE outbound screen, that allows to customize how the request is forwarded to a backend by maybe for some methods it might be sending the request to a different Backend API contract. 
Also they might have security profiles, or nested resources. 

Would it be possible to use APIM-CLI for adding a tag to existing API? is that recommended?
And if so, is it the only option to EXPORT the config first, adding the file, and then IMPORT it back? we are aware it basically removes and creates it back using whatever is in the config file. So, the follow up question is how mature is the EXPORT step? 
I have not been using the apim-cli since a while, and in my own experience there were open issues regarding the EXPORT step (see https://github.com/Axway-API-Management-Plus/apim-cli/issues/59). Is there a list of known issues related to the EXPORT step that we could use to build mitigations around them (ie. not using apim-cli for these APIs and do the change manually)

Thanks

**Comment by rathnapandi** [comment]
Hi @emmanuel-galindo, 

Export steps used by a lot of customers.  APIM CLI treat everything as code. For your use case, as you mentioned we need export API, add it to git, add tags and import it again. The code available in git will be a source of truth.  The git project will be used to promote the code to higher environments. 

We are not planning to fix the issue https://github.com/Axway-API-Management-Plus/apim-cli/issues/59 as it too complex to implement and not widely used. 

Thanks
Rathna

**Comment by emmanuel-galindo** [comment]
Hi @rathnapandi 
Of course I am aware of #59 but my question is other: 
Apart from that one, what are the other known limitations from apim-cli export step should we consider? 

Thanks

**Comment by rathnapandi** [comment]
There are no known limitations apart from the issues available on github issues. If you run into anything, please create github issue.

**Comment by emmanuel-galindo** [comment]
Hi,
how can I get the list of github issues you mention? because taking for example #59 it is closed, and you confirmed it is a known limitation. 
We just need to know that, to avoid breaking stuff in prod. 

FYI, we just need to add a tag to existing APIs.. and we have been working for weeks on this :(


thanks

**Comment by emmanuel-galindo** [comment]
Hi @rathnapandi , but in that list it does not appear #59 .. 

can you confirm that all known issues are:
- open issues 
- label:stale
- #59 

thanks

**Comment by rathnapandi** [comment]
HI @emmanuel-galindo, 

Check line item 3 in the image.
