### ISSUE TITLE
Issue with maven dependencies

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#464]
### APIM-CLI version

1.14.2

### API-Management version

7.7.20231130

### Bug description

Maven dependency:
    <dependency>
      <groupId>com.github.axway-api-management-plus.apim-cli</groupId>
      <artifactId>apimcli-apis</artifactId>
      <version>1.14.2</version>
    </dependency>
  
Throws this error (ie with mvn package) 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.887 s
[INFO] Finished at: 2024-03-11T14:37:40-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project changelist: Could not resolve dependencies for project com.boehringer.apim:changelist:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.github.axway-api-management-plus.apim-cli:apimcli-apis:jar:1.14.2 -> com.github.axway-api-management-plus.apim-cli:apimcli-apim-adapter:jar:1.14.2 -> org.ehcache:ehcache:jar:3.10.8 -> org.glassfish.jaxb:jaxb-runtime:jar:2.3.0-b170127.1453 -> org.glassfish.jaxb:jaxb-core:jar:2.3.0-b170127.1453 -> javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Failed to read artifact descriptor for javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: The following artifacts could not be resolved: javax.xml.bind:jaxb-api:pom:2.3.0-b161121.1438 (absent): Could not transfer artifact javax.xml.bind:jaxb-api:pom:2.3.0-b161121.1438 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [releases.java.net (http://maven.java.net/content/repositories/releases/, default, releases+snapshots), shapshots.java.net (http://maven.java.net/content/repositories/snapshots/, default, releases+snapshots), jvnet-nexus-staging (http://maven.java.net/content/repositories/staging/, default, releases+snapshots), netbeans (http://bits.netbeans.org/nexus/content/groups/netbeans, default, releases)] -> [Help 1]

### Steps to reproduce

create pom.xml with dependency and execute mvn

**Comment by rathnapandi** [comment]
Hi @emmanuel-galindo, 

Change the maven settings.xml to all http connection. Please reference - https://gist.github.com/vegaasen/1d545aafeda867fcb48ae3f6cd8fd7c7

**Comment by emmanuel-galindo** [comment]
@rathnapandi  thanks for the tip!! I've spent a lot of time trying to find a solution

but now mvn complains 401 ... it says
[ERROR] Failed to execute goal on project changelist: Could not resolve dependencies for project com.boehringer.apim:changelist:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.github.axway-api-management-plus.apim-cli:apimcli-apis:jar:1.14.2 -> com.github.axway-api-management-plus.apim-cli:apimcli-apim-adapter:jar:1.14.2 -> org.ehcache:ehcache:jar:3.10.8 -> org.glassfish.jaxb:jaxb-runtime:jar:2.3.0-b170127.1453 -> org.glassfish.jaxb:jaxb-core:jar:2.3.0-b170127.1453 -> javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Failed to read artifact descriptor for javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: The following artifacts could not be resolved: javax.xml.bind:jaxb-api:pom:2.3.0-b161121.1438 (absent): Could not transfer artifact javax.xml.bind:jaxb-api:pom:2.3.0-b161121.1438 from/to netbeans (http://bits.netbeans.org/nexus/content/groups/netbeans): status code: 401, reason phrase: Repository decommissioned. Please refer to https://netbeans.apache.org/about/oracle-transition.html for more information. (401) -> [Help 1]

I tried in another box but same issue.. any idea?
