### ISSUE TITLE
Missing error code when " Backend API Definition is not available for the API "

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#465]
### APIM-CLI version

1.14.2

### API-Management version

7.7.20231130

### Bug description

When exporting to json,for error:
2024-03-11 20:08:22,804 [JsonAPIExporter] ERROR: Backend API Definition is not available for the API : (TEST) BusinessPartner Data API, hence use the option -useFEAPIDefinition to export API

Exit code is 0

**Comment by rathnapandi** [comment]
Hi @emmanuel-galindo, 
The api get operation can retrieve more than one APIs (except fetching based on id) and CLI tries to export everything. If one the api does not have backend api definition, it prints an error message and continues processing the next api.  

We can throw an error if we are getting api based on ids. do let me know what you think?

**Comment by emmanuel-galindo** [comment]
yup, for id it makes sense, or when the selection of apis is just 1 api ? 

if not parsing stdout, i wouldn't know how to detect this issue
