### ISSUE TITLE
API deployment does not set new auth basic password 

### ISSUE THREAD

**Issue by dinesh-ax** [Axway-API-Management-Plus/apim-cli#481]
### APIM-CLI version

1.13.6

### API-Management version

7.7.20221130

### Bug description

APIM-CLI API import does not deploy new password on outbound http basic authentication.
"No change" detected by APIM-CLI on API Import.

As you can see on the trace :
[APIChangeState] DEBUG: No change for property: authenticationProfiles
[Desired: [AuthenticationProfile
[name=_default, isDefault=true, parameters={password='XXX', username='xxx'}, type=http_basic]]
vs Actual: [AuthenticationProfile
[name=_default, isDefault=true, parameters={password='YYY'test, username='xxx'}, type=http_basic]]]

Command used to import:
/scripts/apim.sh api import -timeout 200000 -force -retryDelay 15000 -u apiadmin -p 'XXXXXX' -h 'XXX' -port 443 -c xxx.json

It seems during the comparison of the property, password is not checked while username is checked.
System property <VMArg name="-Dcom.axway.apimanager.api.model.disable.confidential.fields=false"/> was also modify to check if the issue is related to the fact that password is masked but still the same issue.

How can we fix this to update passwords in outbound basic authentication?
Is it possible to re-check if this behavior is not also in outbound SSL with client certificate change?

**Comment by rathnapandi** [comment]
@dinesh-ax  fixed in 1.14.5
