### ISSUE TITLE
Parameter queryStringPassThrough

### ISSUE THREAD

**Issue by ghost** [Axway-API-Management-Plus/apim-cli#482]
### APIM-CLI version

1.13

### API-Management version

2022

### Question

I get this settings when using the CLI to get the api-config file.
It looks like parameters are not forwarded to the backend API, but actually, they are forwarded.
I'm not sure how it works. Is this parameter obsolete or not taken into account  ?

    "inboundProfiles" : {
      "_default" : {
        "monitorAPI" : true,
        "queryStringPassThrough" : false, ...

Thanks,

Olivier

**Comment by rathnapandi** [comment]
Hi, 
queryStringPassThrough is  a internal variable used by APIM, the variable introduced from version May 2022, default value is false. 

The same one can be set via system properties, if we do that, it will applicable for all APIs

```html

7.7 November 2020 | com.coreapireg.apimethod.querystring.passthrough | API Manager | If set to true, query parameters are sent unmodified to the backend service. This flag also removes any undefined query parameters from the resulting backend request, unlike the 7.5.3 JVM property api.manager.querystring.passthrough, which passes all parameters to the backend. Defaults to false.
```

Ref - https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_reference/system_props/index.html

Thanks
Rathna
