### ISSUE TITLE
Issue on Windows where exporting all Applications

### ISSUE THREAD

**Issue by aaron-axway** [Axway-API-Management-Plus/apim-cli#483]
### APIM-CLI version

1.14.4

### API-Management version

7.7.20220830

### Bug description

Issue on Windows where exporting all Applications will have an error creating a folder if the name of the Application has ":" character. s

### Steps to reproduce

Create Application and for the `Name` add a `:` character and

**Comment by rathnapandi** [comment]
@aaron-axway  Fixed in 1.14.5
