### ISSUE TITLE
Possible Java version error with APIM CLI 1.14.4

### ISSUE THREAD

**Issue by nvidgren** [Axway-API-Management-Plus/apim-cli#484]
### APIM-CLI version

1.14.4

### API-Management version

7.7.0.20230830

### Bug description

Entered on behalf of a customer.
Using APIM CLI 1.14.4, there is an error running the command:

java.lang.UnsupportedClassVersionError: graphql/schema/idl/errors/SchemaProblem has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Could it be that the most recent version was compiled with Java 11? 

Thanks

### Steps to reproduce

Use latest version of CLI with Java 8.

### Relevant log output

```shell
java.lang.UnsupportedClassVersionError: graphql/schema/idl/errors/SchemaProblem has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by rathnapandi** [comment]
@nvidgren,  CLI needs Java 11 and above.
