### ISSUE TITLE
Error when importing application in APIM pod using Jenkins pipeline

### ISSUE THREAD

**Issue by Yamini1808** [Axway-API-Management-Plus/apim-cli#485]
### APIM-CLI version

1.14.3

### API-Management version

7.7.20231130

### Bug description

Customer is getting API not found error while trying to import an API into Axway using the CLI. We didn't have this issue before the upgrade. The Axway Version we are using is 7.7.20231130, and the CLi version we are using is 1.14.3. We are using a Cassandra Cluster with 3 Nodes, with Replication Factor as 3 and consistency_level LOCAL_QUORUM

The command being used is: 
apim api import -s qa -h apimgr-qa.cacucloud.com -u REMOVED -port 80 -p REMOVED -c api-config.json -overrideSpecBasePath -clearCache 'ALL' -clientOrgsMode replace -force -forceUpdate -zeroDowntimeUpdate true

Error in debug mode: 
[m[m2024-05-31 07:24:37,455 [APIManagerAPIAccessAdapter] DEBUG: Load API-Access with type: applications from API-Manager with ID: 43bb8246-5bfc-41d0-a6fc-141fd798cd0c
[m[m2024-05-31 07:24:37,455 [RestAPICall] DEBUG: Http verb:GET and URI: https://apimgr-qa.cacucloud.com:80/api/portal/v1.4/applications/43bb8246-5bfc-41d0-a6fc-141fd798cd0c/apis
[m[m2024-05-31 07:24:37,486 [APIManagerAPIAdapter] DEBUG: Found: 1 exposed API(s):
[m[m2024-05-31 07:24:37,487 [APIManagerAPIAdapter] DEBUG: Found: 1 exposed API(s):
[m[m2024-05-31 07:24:37,487 [APIManagerAPIAdapter] DEBUG: Found: 1 exposed API(s):
[m[m2024-05-31 07:24:37,487 [RestAPICall] DEBUG: Http verb:GET and URI: https://apimgr-qa.cacucloud.com:80/api/portal/v1.4/proxies/011f8fe0-f26d-4c9a-985a-4fe2ddb7f932
[m[1;31m2024-05-31 07:24:37,511 [APIManagerAPIAdapter] ERROR: Unable to find API with ID: 011f8fe0-f26d-4c9a-985a-4fe2ddb7f932 Please have in mind during API-Update the ID is re-created or add -ignoreCache !
[m[m2024-05-31 07:24:37,512 [APIManagerAPIAdapter] DEBUG: No existing API found based on filter: []
[m[34m2024-05-31 07:24:37,514 [RollbackAPIProxy] INFO : Rollback FE-API: EIP-BUS-PERSONS (ID: ea8b2210-958e-49ec-b55b-068c19cf1b4a / State: unpublished)
[m[m2024-05-31 07:24:37,515 [APIManagerAPIAdapter] DEBUG: Found: 1 exposed API(s):
[m[m2024-05-31 07:24:37,515 [APIStatusManager] DEBUG: Updating API-Status from: published to unpublished
[m[m2024-05-31 07:24:37,515 [APIManagerAPIAdapter] DEBUG: Update API-Proxy status to: unpublished
[m[m2024-05-31 07:24:37,515 [RestAPICall] DEBUG: Http verb:POST and URI: https://apimgr-qa.cacucloud.com:80/api/portal/v1.4/proxies/ea8b2210-958e-49ec-b55b-068c19cf1b4a/unpublish
[m[m2024-05-31 07:24:37,890 [APIManagerAPIAdapter] DEBUG: Deleting API-Proxy with Name : EIP-BUS-PERSONS and Id: ea8b2210-958e-49ec-b55b-068c19cf1b4a
[m[m2024-05-31 07:24:37,890 [RestAPICall] DEBUG: Http verb:DELETE and URI: https://apimgr-qa.cacucloud.com:80/api/portal/v1.4/proxies/ea8b2210-958e-49ec-b55b-068c19cf1b4a
[m[34m2024-05-31 07:24:37,990 [APIManagerAPIAdapter] INFO : API: EIP-BUS-PERSONS 1.0 ( ea8b2210-958e-49ec-b55b-068c19cf1b4a ) successfully deleted
[m[m2024-05-31 07:24:37,990 [APIManagerAPIAdapter] DEBUG: Deleting Backend API : e577aed0-f954-478a-874e-504e79acd643
[m[m2024-05-31 07:24:37,990 [RestAPICall] DEBUG: Http verb:DELETE and URI: https://apimgr-qa.cacucloud.com:80/api/portal/v1.4/apirepo/e577aed0-f954-478a-874e-504e79acd643
[m[m2024-05-31 07:24:39,159 [RestAPICall] DEBUG: Http verb:GET and URI: https://apimgr-qa.cacucloud.com:80/api/portal/v1.4/apirepo?field=name&op=eq&value=EIP-BUS-PERSONS&field=createdOn&op=gt&value=1717140271675
[m[m2024-05-31 07:24:39,878 [APIManagerAPIAdapter] DEBUG: No existing API found based on filter: []
[m[34m2024-05-31 07:24:39,879 [RollbackHandler] INFO : Rolled back: [Frontend-API: false, Backend-API: true]
[m[1;31m2024-05-31 07:24:39,879 [APIImportApp] ERROR: Failure creating API-Access for application: 'StatementManager'. Error loading API-Access for applications from API-Manager
| Error loading API-Access for applications from API-Manager
| Unable to find API with ID: 011f8fe0-f26d-4c9a-985a-4fe2ddb7f932 referenced by Application: StatementManager. You may try again with -clearCache
com.axway.apim.lib.error.AppException: Failure creating API-Access for application: 'StatementManager'. Error loading API-Access for applications from API-Manager
at com.axway.apim.apiimport.actions.ManageClientApps.createAppSubscription(ManageClientApps.java:124)
at com.axway.apim.apiimport.actions.ManageClientApps.execute(ManageClientApps.java:73)
at com.axway.apim.apiimport.actions.CreateNewAPI.execute(CreateNewAPI.java:102)
at com.axway.apim.apiimport.actions.RecreateToUpdateAPI.execute(RecreateToUpdateAPI.java:34)
at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:52)
at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:93)
at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:131)
at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:74)
Caused by: com.axway.apim.lib.error.AppException: Error loading API-Access for applications from API-Manager
at com.axway.apim.adapter.apis.APIManagerAPIAccessAdapter.getAPIAccess(APIManagerAPIAccessAdapter.java:126)
at com.axway.apim.adapter.apis.APIManagerAPIAccessAdapter.createAPIAccess(APIManagerAPIAccessAdapter.java:197)
at com.axway.apim.apiimport.actions.ManageClientApps.createAppSubscription(ManageClientApps.java:122)
... 12 more
Caused by: com.axway.apim.lib.error.AppException: Unable to find API with ID: 011f8fe0-f26d-4c9a-985a-4fe2ddb7f932 referenced by Application: StatementManager. You may try again with -clearCache
at com.axway.apim.adapter.apis.APIManagerAPIAccessAdapter.getAPIAccess(APIManagerAPIAccessAdapter.java:118)
... 14 more
[m[m2024-05-31 07:24:39,881 [APIManagerAdapter] DEBUG: Closing cache ...
[m[m2024-05-31 07:24:39,881 [RestAPICall] DEBUG: Http verb:DELETE and URI: https://apimgr-qa.cacucloud.com:80/api/portal/v1.4/login
[m

About Customer environment:
-> This error is only present in our QA environment, and it has no issues importing into our dev environment. 
-> The only difference between Dev and QA APIMGR Instances is that in dev we have a single node cassandra db and in QA we have 3 node cassandra cluster.
-> Running the CLI in a Jenkins Pipeline and using API Manager Pod.
->  the api-config.json being used to import has been uploaded as MemberService.json

[cli-logs.txt](https://github.com/user-attachments/files/15827772/cli-logs.txt)
[Kubernetes_pod_logs.txt](https://github.com/user-attachments/files/15827775/Kubernetes_pod_logs.txt)
[MemberService (1).json](https://github.com/user-attachments/files/15827779/MemberService.1.json)
[cli-with-jvmarg.txt](https://github.com/user-attachments/files/15827798/cli-with-jvmarg.txt)
[cli-logs-with-delay.txt](https://github.com/user-attachments/files/15827800/cli-logs-with-delay.txt)

### Steps to reproduce

import API in  API Manager Pod using Jenkins pipeline.

Troubleshooting methods we used :
1. added the -ignoreCache option to the cli command and it is still failing
2. tried running the command without -forceUpdate and --zeroDowntimeUpdate true, we are seeing that the stage in the pipeline is failing (you can see the logs for the same in the file cli-debug.txt).
3. tried adding the -retryDelay option with 3000 milliseconds and it is still failing with the same error and after increasing the delay to 10000 and the issue still occurs. (see logs in "pod-logs-with-delay.txt") 
(seem similar to -> https://github.com/Axway-API-Management-Plus/apim-cli/issues/212, -> https://github.com/Axway-API-Management-Plus/apim-cli/issues/213)
4. tried adding the <VMArg name="-Dcom.axway.apimanager.api.data.cache=true"/> jvm argument in the jvm.xml file and redeploy the API Manager and the issue is still persisting. (see logs in cli-with-jvmarg.txt)

It seems the CLI is not retrying the failing API call and just returns the failed status.

**Comment by rathnapandi** [comment]
Environment related issue.
