### ISSUE TITLE
Outside environment variables should not affect tests

### ISSUE THREAD

**Issue by saper** [Axway-API-Management-Plus/apim-cli#488]
### APIM-CLI version

1.14.4+

### API-Management version

none

### Bug description

Having `JAVA_HOME`, `CI` set in the environment causes the [test failure in EnvironmentPropertiesTest:testEnvironmentWithOSEnvVariables](https://github.com/Axway-API-Management-Plus/apim-cli/blob/e6d2e54d2932529d572b78649f16d38af231706b/modules/apim-adapter/src/test/java/com/axway/lib/EnvironmentPropertiesTest.java#L65)

Having `AXWAY_APIM_CLI_HOME` set with some real environments defined in the `conf` directory there causes failures of the [testStage](https://github.com/Axway-API-Management-Plus/apim-cli/blob/e6d2e54d2932529d572b78649f16d38af231706b/modules/apim-adapter/src/test/java/com/axway/lib/EnvironmentPropertiesTest.java#L27) and [testNoStage](https://github.com/Axway-API-Management-Plus/apim-cli/blob/e6d2e54d2932529d572b78649f16d38af231706b/modules/apim-adapter/src/test/java/com/axway/lib/EnvironmentPropertiesTest.java#L21) tests.

This should not happen.

**Comment by rathnapandi** [comment]
@saper  Fixed in 1.14.5
