### ISSUE TITLE
API Import with published state doesn't work

### ISSUE THREAD

**Issue by HaritaMittal** [Axway-API-Management-Plus/apim-cli#493]
### APIM-CLI version

1.14.4

### API-Management version

7.7.0.20240228

### Bug description

1. New API Import with state published doesn't work. It imports the API and virtualize it but later deletes it followed by error message:
2024-08-22 09:47:05,695 [APIImportApp] ERROR: The status change from: 'published' to 'published' is not possible!
                                 | Cannot update API-Proxy status.
                                 | Unable to send HTTP-Request.
com.axway.apim.lib.error.AppException: The status change from: 'published' to 'published' is not possible!

2. API Import to publish a previously unpublished API is also behaving the same way.

Attaching file with debug logs.
[UnpublishedToPublishedAPIImport.txt](https://github.com/user-attachments/files/16707330/UnpublishedToPublishedAPIImport.txt)
[NewPublsihedAPIImport.txt](https://github.com/user-attachments/files/16707331/NewPublsihedAPIImport.txt)

**Comment by rathnapandi** [comment]
Hi @HaritaMittal, 

When we create a front end API on API manger via REST API / UI, it tries to download the backend certificates based on  open api server section,  If server is not reachable, it gets timed out and throwing the exception.  We can use any one of the following options. 
-  we need to give a valid  URL in open api spec 
-  use  api cli param -overrideSpecBasePath true ( it will override the server section based on api-config.json backend base path) 
-  increase apim cli client timeout using param -timeout 60000.
