### ISSUE TITLE
Force APIM-cli to download the latest Trusted Certificates in a Frontend API

### ISSUE THREAD

**Issue by renankaic** [Axway-API-Management-Plus/apim-cli#494]
### Problem description

Hello!
As suggested by Rathna in this Axway's comunnity post [https://community.axway.com/s/question/0D7KC000000XakL0AS/detail?fromEmail=1&s1oid=00Dw0000000CxUA&s1nid=0DBw0000000fySH&s1uid=0053V000001tb45&s1ext=0&emkind=chatterCommentNotification&emtm=1724858302228](url) - I'm opening this topic in order to request a feature.

As I mentioned in the above community topic, I tried the following:
1. `apim api get -s prod -id 2eb568bc-81df-48fb-86c1-9e3d9c562ec9 -o yaml`
2. Inside the created folder, I opened the api-config.yaml file and **I deleted the "caCerts" section entirely**. 
3. Then I import back to our API Manager with the following: `apim api import -s dev -c .\api-config.yaml` 

But, when checking the modified frontend api at the "Trusted Certificates" tab, the certificates aren't being updated with the latest ones already provided by the backend service.

Please, is there another way to do it or this really needs to be a new feature?

Thank you!

### Feature request

For published frontend apis that communicates with a HTTPS Backend Service and already has Trusted Certificates set to it, it would be nice to have a function in the apim-cli to update these Trusted Certificates to the latest ones provided by the Backend Service.

**Comment by rathnapandi** [comment]
Hi @renankaic, 

Introduced new environment variable override_certificates to handle the enhancement. 

Before running CLI command run below command

```bash
export override_certificates=true
```
Use attached APIM CLI binary  for testing
[axway-apimcli-1.14.6-SNAPSHOT.tar.gz](https://github.com/user-attachments/files/17284067/axway-apimcli-1.14.6-SNAPSHOT.tar.gz)

Thanks
Rathna

**Comment by rathnapandi** [comment]
Fixed in 1.14.6

**Comment by renankaic** [comment]
Thank you very much Great Rathna!!! I'll aim to implement this new version until next week as soon I have some spare time
