### ISSUE TITLE
Run APIM Cli without requesting access to sonatype

### ISSUE THREAD

**Issue by blcktqq** [Axway-API-Management-Plus/apim-cli#497]
### APIM-CLI version

1.14.5

### API-Management version

May 2024

### Question

Hello, is there an option to debug APIM CLI locally without requesting an access to your sonatype?
We are facing issue with import new APIs , some of the subscribed applications have access to over 500+ APIs an importing process take 5-10 minutes, which is not acceptable for us. 
So I would like to run it locally and find the rootcause before create a bug report here.

**Comment by rathnapandi** [comment]
Hi @blcktqq, 

Please clone the project locally and run mvn clean package -Dmaven.test.skip=true to build it locally.
