### ISSUE TITLE
Get functionnal deployment result with i18n

### ISSUE THREAD

**Issue by dinesh-ax** [Axway-API-Management-Plus/apim-cli#498]
### APIM-CLI version

1.13.2

### API-Management version

7.7.20221130

### Question

Can we have more functionnal error messages with maven com.github.axway-api-management-plus.apim-cli/apimcli-apis tool ?
Can we have translated error messages ?
Do you have a list of error messages that can be translated ?

**Comment by rathnapandi** [comment]
List of error codes and description available on https://github.com/Axway-API-Management-Plus/apim-cli/wiki/9.6-Error-Codes
And no plans to add i18n. 

Thanks
Rathna
