### ISSUE TITLE
Update API with Assigned Quota

### ISSUE THREAD

**Issue by ramonpenteado** [Axway-API-Management-Plus/apim-cli#499]
### APIM-CLI version

1.14.2

### API-Management version

7.7.0.20230830

### Question

**NOTE: Same thing happens with 1.14.4 and 1.14.5.**
We are trying to manage API Manager quotas thru apimcli. But, for starters, we can not get this information by running apim settings get command. 
The issue we are running into is mainly that when we update an API with a quota plan, that quota plan looses the reference to that API and stops working.
Is that something we are operating wrong? Is there a known issue about it? 
Let me know if this should be turned into a bug.

**Comment by rathnapandi** [comment]
Hi @ramonpenteado, Can you share the api-config file?

**Comment by thiagonogueira-edilabs** [comment]
attached file 
[api-config.json](https://github.com/user-attachments/files/17048119/api-config.json)

**Comment by rathnapandi** [comment]
Fixed in 1.14.6
