### ISSUE TITLE
Enable caching for `API Import` action.

### ISSUE THREAD

**Issue by blcktqq** [Axway-API-Management-Plus/apim-cli#500]
### Problem description

Hello, 
We are experiencing issues when importing APIs via `apim api import` action, due to complexity of our system. 
For APIs with a lot of subscribed application it takes over 3 minutes to import it. 

### Feature request

Could you please enable `beta` cache mechanism for the following caches as well?

![image](https://github.com/user-attachments/assets/d4a5f83b-0bd5-40a2-a53e-89058e8b04e0)

**Comment by rathnapandi** [comment]
Hi @blcktqq, 

Is it possible for you to change the code and test?

**Comment by rathnapandi** [comment]
Hi @blcktqq,
Optimized the code  for import operation. please test with 
[axway-apimcli-1.14.7-SNAPSHOT.tar.gz](https://github.com/user-attachments/files/17404429/axway-apimcli-1.14.7-SNAPSHOT.tar.gz) and let me know the outcome.

**Comment by rathnapandi** [comment]
Fixed in 1.14.7
