### ISSUE TITLE
Importing SOAP API with different endpoints (for import and for runtime calls)

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apim-cli#501]
### APIM-CLI version

1.14.2

### API-Management version

7.7.20211130

### Question

is it possible to import a soap frontend API and differentiate:
* the URL provided for wsdl import
* the URL to reach at API calls
?

I've tried using:

{
  "organization": "MyOrg",
  "apiDefinition": "http://myHost1:8105/import/myservice?wsdl",
  "backendBasepath": "http://myHost2:7349/runtime/myservice",
   ....

But in API Manager I saw that Backend service URL is always equals to "apiDefinition" field and backendBasePath is ignored.

Is there a way to achieve my goal?

**Comment by gcornacchia** [comment]
I attach the json api configuration file if you want to reproduce the issue:

[mySoapService.json](https://github.com/user-attachments/files/17257058/mySoapService.json)

with this command: 

` apim-cli.sh api import -c mySoapService.json -s myEnv`

this is a screenshot of API Manager backend service URL after the import:

![image](https://github.com/user-attachments/assets/043a5dc8-8247-46d4-83ca-b9f0cc6cb814)

My goal is to configure a different backend endpoint (as specified in backendBasePath field in the json = http://mybackend/calculator)

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

As overridebasepath flag is set it is not allowing to change the host name.  Added a fix to handle it.  In the meantime, remove the flag, it will work.

Thanks
Rathna

**Comment by gcornacchia** [comment]
Hi @rathnapandi,
so as a workaround I removed the flag overridebasepath and the import succeeded with the desired behavior.

If I understand well you have added a fix to reach the same goal but with overridebasepath = true option? is this already available in the develop branch?

**Comment by rathnapandi** [comment]
Hi @gcornacchia,
Yes, the changes are available in development brach. 

Thanks
Rathna

**Comment by gcornacchia** [comment]
Hi @rathnapandi,
I've tried the code in development branch.

the behaviour is not exactly the expected, I've tested with the same provided above:

In the imported frontend API I see the backend URL is partially correct: a suffix not specified in json config file is added (maybe read from the wsdl itself??)

![image](https://github.com/user-attachments/assets/4ffe68ce-4ad0-40fa-88cd-28346da6755f)

do you think it's a apim-cli issue or API manager issue?

**Comment by rathnapandi** [comment]
Hi @gcornacchia, 

The  URL suffice / basepath calculator.asmx  is coming from WSDL. We can update the backend Service URL host  via backendBasePath ( it should be host only). 

![image](https://github.com/user-attachments/assets/1ee1ee83-06ea-4f2b-bd03-a4c07055c93a)

Unfortunately, API manager does not allow to edit the basepath by updating backend API or WSDL.  
![image](https://github.com/user-attachments/assets/4f4d0791-356e-44ec-8217-9d804fe75c01)

**Comment by gcornacchia** [comment]
hi @rathnapandi ,
I can handle in some way this API Manager limitation, when will the next apim-cli release be available?

**Comment by rathnapandi** [comment]
Hi @gcornacchia 
Mid of next week.

**Comment by rathnapandi** [comment]
Fixed in 1.14.6
