### ISSUE TITLE
allow APIM cli to connect to API Manager protected by Cloudflare

### ISSUE THREAD

**Issue by KripeshJha** [Axway-API-Management-Plus/apim-cli#505]
### Problem description

API Manager that is protected behind cloudflare need cf-access-token in request header when calling API Manager API to allow successful call.

![Screenshot 2024-10-11 at 6 18 49 PM](https://github.com/user-attachments/assets/f72b8ff9-ad37-4748-b37d-63c2dd4d88a9)
![Screenshot 2024-10-11 at 6 21 57 PM](https://github.com/user-attachments/assets/3e6ece04-edea-4b36-9094-72adaa94245d)

As apimcli doesn't support sending additional header while calling API Manager rest API, we are unable to send cf-access-token and hence unable to connect API Manager via APIM CLI

### Feature request

Please allow APIM CLI to send cf-access-token to allow apim cli to consume API Manager APIs protected by cloudflare

**Comment by rathnapandi** [comment]
Fixed in 1.14.7
