### ISSUE TITLE
Allow APIM Cli to retire old API when importing apis using zeroDowntimeUpdate

### ISSUE THREAD

**Issue by KripeshJha** [Axway-API-Management-Plus/apim-cli#511]
### Problem description

APIM Cli deletes old APIs when we execute api import using zeroDowntimeUpdate=true flag

![image](https://github.com/user-attachments/assets/41cef4b8-5761-44e3-a254-429ea242379a)

### Feature request

Allow APIM Cli to retire old API when importing apis using zeroDowntimeUpdate

**Comment by rathnapandi** [comment]
Added in 1.14.8
