### ISSUE TITLE
Axway apimcli: Format and version discrepancies - read-only (Swagger 2.0, single-line) vs editable APIs (Swagger 1.1, formatted)

### ISSUE THREAD

**Issue by baustin612** [Axway-API-Management-Plus/apim-cli#516]
### APIM-CLI version

1.14.4

### API-Management version

7.7.20240228

### Question

I've noticed inconsistent JSON formatting behavior when using the apimcli tool from Axway-API-Management-Plus to download APIs from the gateway:

For read-only APIs:

The get command produces a single-line JSON file with no formatting
Exports in Swagger version 2.0 format
For editable APIs:

The get command produces a properly formatted, readable JSON file with standard indentation
Exports in Swagger version 1.1 format
This inconsistency in both formatting and Swagger versions makes code reviews challenging. Is there a reason for the single-line output and different Swagger versions with read-only APIs? Is there a way to force consistent formatting and versioning regardless of the API's read-only status?

 

This is on version 1.14.4 of apim-cli tool but we've used many different versions

**Comment by rathnapandi** [comment]
Hi @baustin612, 

We are doing api operations filtering ( https://github.com/Axway-API-Management-Plus/apim-cli/wiki/2.1.10-API-Specification#filter-api-specifications) for swagger 2.0 and 3.x not for 1.1.  

I agree with you on having same formatting.  I have added formatting fix for swagger 2.0 and 3.x.  Please test with below binary. 
[axway-apimcli-1.14.8-SNAPSHOT.tar.gz](https://github.com/user-attachments/files/17592646/axway-apimcli-1.14.8-SNAPSHOT.tar.gz)

**Comment by baustin612** [comment]
Hello,
Im getting this error 
gzip: axway-apimcli-1.14.8-SNAPSHOT.tar.gz: unexpected end of file
Can't extract completely.

**Comment by rathnapandi** [comment]
[axway-apimcli-1.14.8-SNAPSHOT.zip](https://github.com/user-attachments/files/17594246/axway-apimcli-1.14.8-SNAPSHOT.zip)

**Comment by baustin612** [comment]
Hi Ratha,

That doesn’t seem to be complete either, it has no script in the scripts folder. I tried moving mine over from the 1.14.4 version but get an error when attempting to run it.

Error: Could not find or load main class com.axway.apim.cli.APIManagerCLI
Caused by: java.lang.ClassNotFoundException: com.axway.apim.cli.APIManagerCLI


Ben Austin
Developer, Data Integration
Sutter Health System Office

Sutter Health

O 916-801-1764
***@***.******@***.***>
sutterhealth.org

***@***.******@***.******@***.******@***.***<https://twitter.com/SutterHealth>
Confidentiality notice: This email is for the sole use of the intended recipient and may contain material that is confidential and protected by state and federal regulations. If you are not the intended recipient, please immediately delete it and contact the sender. Thank you.

From: Rathna ***@***.***>
Sent: Thursday, October 31, 2024 4:46 PM
To: Axway-API-Management-Plus/apim-cli ***@***.***>
Cc: Austin, Benjamin ***@***.***>; Mention ***@***.***>
Subject: [**External**] Re: [Axway-API-Management-Plus/apim-cli] Axway apimcli: Format and version discrepancies - read-only (Swagger 2.0, single-line) vs editable APIs (Swagger 1.1, formatted) (Issue #516)

✉
EXTERNAL EMAIL ALERT: This email originated from outside Sutter Health.
DO NOT CLICK LINKS or OPEN ATTACHMENTS unless you recognize the sender and are expecting the content. Be vigilant against phishing attempts!


axway-apimcli-1.14.8-SNAPSHOT.zip<https://github.com/user-attachments/files/17594246/axway-apimcli-1.14.8-SNAPSHOT.zip>

**Comment by rathnapandi** [comment]
Hi @baustin612, 
I can download and view all the files from above github link.  can you check  whether your anti-virus is blocking *.jar, .sh and .bat files?

**Comment by baustin612** [comment]
@rathnapandi  that does appear to be case, i cant even get official release anymore, will investigate on my end and come back when i have it worked out.

**Comment by baustin612** [comment]
@rathnapandi We were able to get the files downloaded but it seems we are still experiencing the format of the json on one line when we use the get command to pull it down. It came as Swagger 2.0.

**Comment by baustin612** [comment]
@rathnapandi that worked thank you!

**Comment by rathnapandi** [comment]
Fixed in 1.14.8
