### ISSUE TITLE
Cli swagger upload failing when cli upgraded to 1.14.5: Error code 56

### ISSUE THREAD

**Issue by gurpreetbhatoa** [Axway-API-Management-Plus/apim-cli#519]
### APIM-CLI version

apim-cli-1.14.5

### API-Management version

7.7.20240530

### Question

We have the application configured in the api-manager but since the upgrade to the version 1.14.5, we are getting this error.
Error code seems to suggest api not found but it does exist
`
[APIManagerCLI] INFO : API-Manager CLI: 1.14.5
[APIManagerCLI] INFO : Module: API - I M P O R T  (1.14.5)
[APIManagerOrganizationAdapter] WARN : Using OrgAdmin only to load all organizations.
[APIManagerAdapter] INFO : Organization Administrator Self Service Enabled : false
[APIManagerAdapter] INFO : Successfully connected to API-Manager (7.7.20240530) on: https://axway-api-manager
[APIManagerOrganizationAdapter] WARN : Using OrgAdmin only to load all organizations.
[APISpecificationFactory] INFO : Reading API-Definition (Swagger/WSDL) from file: api.json (absolute path)
[APISpecificationFactory] INFO : Detected: Swagger 2.0 specification. 
[Swagger2xSpecification] INFO : Used the backendBasePath: https://backend.url:443 to adjust host the API-Specification.
[APIImportConfigAdapter] INFO : Handling configured client-applications.
[APIImportConfigAdapter] INFO : Found existing application: EQR API (null) based on given name EQR API
[APIImportApp] INFO : Lookup actual API based on Path: /api 
[APISpecification] INFO : Detected API-Definition-File sizes: API-Manager: 149557 vs Import: 151574
[APIImportManager] INFO : Recognized the following changes. Potentially Breaking: [apiDefinition, serviceProfiles] plus Non-Breaking: [version]
[APIImportManager] INFO : Is Breaking changes : false Enforce Breaking changes : false
[APIImportManager] INFO : Update API Strategy: Re-Create API as changes can't be applied to existing API.
[RecreateToUpdateAPI] INFO : Create new API to update existing: api (ID: 3d110ae9-a16c-42d0-afa3-fd59c42c0e86)
[CreateNewAPI] INFO : Create unpublished API: api 1.1.0  based on Swagger 2.0 specification.
[CreateNewAPI] INFO : Updating API backendBasePath with value : https://backend.url:443
[ManageClientOrganization] INFO : reCreation : true
[ManageClientApps] INFO : Application name : API
[ManageClientApps] INFO : Organization  : 'IT'
[ManageClientApps] INFO : Application name : API
[ManageClientApps] INFO : Organization  : 'API'
Failing task since return code of [/bin/sh /data/11427158015481826228.sh] was 56 while expected 0
Failure creating API-Access for application: 'API'. Error loading API-Access for applications from API-Manager | Error loading API-Access for applications from API-Manager
`

**Comment by gurpreetbhatoa** [comment]
`Failure creating API-Access for application: 'API'. Error loading API-Access for applications from API-Manager
| Error loading API-Access for applications from API-Manager`

**Comment by rathnapandi** [comment]
Hi @gurpreetbhatoa, 

Users with organization administrator role have limited access, you can enable self-service for org admin.  refer - https://github.com/Axway-API-Management-Plus/apim-cli/wiki/8.3.-OrgAdmin-support
