### ISSUE TITLE
How to update authenticationProfile http_basic password ?

### ISSUE THREAD

**Issue by gwandwingor** [Axway-API-Management-Plus/apim-cli#55]
**API-Manager CLI Version**
1.2.1

**API-Manager and Service-Pack Version**
7.7.20200530

**Question**
In the documentation, it is stated :

> Please note: Starting from API-Manager Version 7.7 SP1 & 7.6.2 SP5 the password is not exposed anymore by the REST-API. Therefore Swagger-Promote can't use it anymore to compare the Desired with the Actual state. In order to change the password another field of the Desired state must be changed as well.

If the password used in an http_basic type authenticationProfile has changed and needs to be updated in API Manager, what do you recommend doing to trigger such an update ? There's not many possibilities in terms of "non-impacting" fields to trigger such an update.

**What I've tried so far**
I tried to change the "name" field of the authenticationProfile but it didn't trigger a change.
`"name": "_default",` into `"name":"_newname"`

**Additional information**
Since API Manager REST API behavious seems to have changed in 7.7 and there doesn't seem to be a way to determine whether a password has changed or not, wouldn't it be safer to assume by default that it changed and trigger the authenticationProfile update anyway ? maybe using some kind of "force" flag ?

**Comment by gwandwingor** [comment]
Ok, so doing further tests, I believe I found a way to workaround this, by creating a second authenticationProfile with the updated password and set it as default, as follows : 
`

	"authenticationProfiles": [{
		"isDefault": false,
		"name": "old",
		"parameters": {
			"password": "mypassword",
			"username": "myuser"
		},
		"type": "http_basic"
	},
	{
		"isDefault": true,
		"name": "new",
		"parameters": {
			"password": "mynewpassword",
			"username": "myuser"
		},
		"type": "http_basic"
	}],
`
I'm still worried about customers that were already using apimanger-swagger-promote and are/will be migrating from 7.5.3 to 7.7. Maybe it should be higlihted in the doc that if they do not pay attention to this, it could potentially break their APIs.

**Comment by cwiechmann** [comment]
@gwandwingor, you can basically change anything you want, that is forcing the API to be re-created.
In other words: The change must must not be related to the Profile itself.
However, I do agree some kind of a forceUpdate flag would be helpful in some situations anyway. Could you perhaps create an issue for that request?

**Comment by gwandwingor** [comment]
Yes, sure, will do.
FYI, I just found out that in v7.7 there seems to be a jvm.xml property that could revert the API Manager REST API behavioural change. Here it is :
`<VMArg name="-Dcom.axway.apimanager.api.model.disable.confidential.fields=true"/>`
I can provide the associated Jira ticket if you're interested.

**Comment by cwiechmann** [comment]
I don’t need the JIRA-Ticket. I’ll add this option/toggle to the documentation. And many thanks for providing that information.

**Comment by gwandwingor** [comment]
There's more info in the 7.7. January release note https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_relnotes/20200130_apimgr_relnotes/index.html

**Comment by cwiechmann** [comment]
I thought about it and decided not to support this toggle. I mean, the CLI will not take the password into consideration, even if the toggle is set. 
One of the reasons is, that the toggle value is not known to the CLI. Furthermore, to me it's an edge-case that only the password is changed and nothing else. Also, the `-forceUpdate` is another way to workaround this limitation.

**Comment by gwandwingor** [comment]
@cwiechmann  I agree that -forceUpdate would be a workaround this limitation. However, long story short, for my customer, that would mean ending up with the forceUpdate flag always activated, which is not optimal.

I believe there is a simple way to take advantage of API Manager option com.axway.apimanager.api.model.disable.confidential.fields.

Basically, what this toggle does is just making the password field reappear. What apim-cli could do, is simply taking password parameter into account and doing the comparison only when provided. 
The rest of the time, current behaviour would remain the same.

If you don't mind taking a look at #71 , I think that's all it takes to solve my problem. Ran some tests locally, didn't have any problems.
