### ISSUE TITLE
Add a 'forceUpdate' flag to force the update of an API

### ISSUE THREAD

**Issue by gwandwingor** [Axway-API-Management-Plus/apim-cli#56]
Following question #55 ,

In some cases, it is required to force the apim-cli to update an already existing API. For instance, to update the password of an http_basic authenticationProfile.
Currently, in v7.7 some elements (such as passwords) are no longer returned by API Manager REST API, meaning that apim-cli is unable to determine whether or not they need to be updated in API Manager.

It would be helpful to have a "forceUpdate" flag either in the commandLine to indicate apim-cli that the whole content of the api contract file needs to be reapplied.

**Comment by cwiechmann** [comment]
A new `forceUpdate` flag will be available in the next release. 
`"forceUpdate" ....  "If set, the API is Re-Created even if the Desired- and Actual-State are equal."`
