### ISSUE TITLE
[Feature] Add Per-Method-Override support for different backend API and method

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#59]
**User story**
In API Manager UI -> Frontend API -> Outbound you can create a PER-METHOD-OVERRIDE which points however to another Backend API and method as the initial registered one.

Are the any plans to support this feature as well in APIM CLI to export and import such scenarios?

**Additional context**

**Comment by emmanuel-galindo** [comment]
Hi, I am having the same request.. to use "Edit API Proxy" to do url rewrite and maintain it with this tool. The export flag seems to not dump this part of the config.

**Comment by cwiechmann** [comment]
Thanks for the feedback @emmanuel-galindo. I'll implement this feature with one of the following version, but I have not yet decided when I have time to start with it.

> The export flag seems to not dump this part of the config.

Yes, you are right and this is expected. The CLI is creating an internal model of API and this model actually doesn't support this part of the configuration. Hence you don't see it in the export.

**Comment by emmanuel-galindo** [comment]
not stale
