### ISSUE TITLE
api api import error

### ISSUE THREAD

**Issue by RodrigoMachadoSilva** [Axway-API-Management-Plus/apim-cli#60]
**API-Manager CLI Version**
1.2.1

**API-Manager and Service-Pack Version**
7.7.0

**Question**
When running the apim api import command on Linux, i'm getting the error message:

Using java given in JAVA_HOME
```
----------------------------------------------------------------------------------------
API-Manager CLI: 1.2.1

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - I M P O R T (1.2.1)
----------------------------------------------------------------------------------------
0      INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.0) on: https://apimanager-hml.autoglass.com.br:443
7      ERROR         APIImportApp| Cant parse JSON-Config file(s)
8      ERROR         APIImportApp| Cant parse JSON-Config file(s)
com.axway.apim.lib.errorHandling.AppException: Cant parse JSON-Config file(s)
        at com.axway.apim.apiimport.APIImportConfigAdapter.<init>(APIImportConfigAdapter.java:163)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:66)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Unable to find given Config-File: './import.config-hml.json'
        at com.axway.apim.apiimport.APIImportConfigAdapter.locateAPIConfigFile(APIImportConfigAdapter.java:178)
        at com.axway.apim.apiimport.APIImportConfigAdapter.<init>(APIImportConfigAdapter.java:147)
```

**What I've tried so far**
Configured correctly the JAVA_HOME environment variable
Tried to execute the script from various locations
Verified the config file permissions

**Additional information**

**Comment by cwiechmann** [comment]
Can you please provide the complete usage?
The error you get, basically means, that the API-Configuration file cannot be found.
You need to provide the config file with the parameter -c

**Comment by RodrigoMachadoSilva** [comment]
Sure!

The command i'm using is:
apim.sh api import -c ./import.config-hml.json -h apimanager-hml -u apiadmin -p ********

The configuration file is located in current directory

**Comment by cwiechmann** [comment]
Are you sure, the file: import.config-hml.json really exists?

**Comment by RodrigoMachadoSilva** [comment]
Yes! It does exists and is located in current directory. :)

![Screenshot_1](https://user-images.githubusercontent.com/8029845/89206692-0559ce80-d590-11ea-9289-b95bfa15468d.png)

**Comment by cwiechmann** [comment]
Can you please rename that file like so:
import-config-hml.json
Perhaps the code gets “confused”, as the DOT is also used to find stage-files.

**Comment by RodrigoMachadoSilva** [comment]
Got it

Done, but, with same result.

![Screenshot_2](https://user-images.githubusercontent.com/8029845/89207879-d7758980-d591-11ea-8e09-95678d5d6a19.png)

**Comment by cwiechmann** [comment]
Hmm, let me check and I come back to you here.

**Comment by RodrigoMachadoSilva** [comment]
The Java version haves some interference in this case?

I'm using the Open JDK 14.0.1.7-2

**Comment by cwiechmann** [comment]
Hi @RodrigoMachadoSilva, I don't think it is related to the Java-Version you are using. I have realized, that I don't throw the causing exception, which I have improved now. Can you please re-run with the version attached here, as it will trace the real cause, why the file can't be loaded/located. 

[axway-apimcli-1.3.0-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/5021397/axway-apimcli-1.3.0-SNAPSHOT.zip)

**Comment by RodrigoMachadoSilva** [comment]
Ok @cwiechmann , i will do that right away
Thanks

**Comment by RodrigoMachadoSilva** [comment]
@cwiechmann, i tried with the given version of CLI:
![Screenshot_3](https://user-images.githubusercontent.com/8029845/89330822-2f31f480-d667-11ea-8ffa-4310c0e1b6ca.png)

**Comment by RodrigoMachadoSilva** [comment]
I must add that on windows everything works properly.

**Comment by cwiechmann** [comment]
Okay. I found the issue and it's caused by having an undiscovered difference between the Windows `apim.bat` and the `apim.sh`. The Windows-Version is saving & restoring the current path, which the Shell-Script doesn't. Interesting, that nobody came across this issue before.

It really helped to know, that it works on Windows!

**Comment by RodrigoMachadoSilva** [comment]
I feel really glad to contribute with the tool, do you suggest moving forward with the windows version?

**Comment by cwiechmann** [comment]
Hi @RodrigoMachadoSilva, I improved the `apim.sh` script to work in the same way, as `apim.bat`. Could you please try on your side as well to validate it is now working as expected?

You can download the latest version from here: https://github.com/Axway-API-Management-Plus/apim-cli/blob/develop/modules/apim-cli/assembly/scripts/apim.sh

Thanks!

**Comment by cwiechmann** [comment]
Concerning your question: No, the Linux Version must work as well.
I'm really thankful for your help discovering the problem.

**Comment by RodrigoMachadoSilva** [comment]
Worked perfectly @cwiechmann, thank you!

**Comment by cabhilash-axway** [comment]
Hi @cwiechmann 
I had the similar issue where it is working in windows and encountering the "Can't parse JSON Config file" in Linux.  I did updated the apim.sh with reference to [link ](https://github.com/Axway-API-Management-Plus/apim-cli/blob/develop/modules/apim-cli/assembly/scripts/apim.sh)mentioned above.  I am still getting the same error.

**Details:**

**API-Manager CLI Version**
1.2.1

**API-Manager**
7.7 July update

**Question**
When running the apim api import command on Linux, i'm getting the error message: "**Can't parse JSON Config file**"


![image](https://user-images.githubusercontent.com/51496736/91672459-abdbb580-eae3-11ea-8319-f67705b0704f.png)

**Comment by cwiechmann** [comment]
@cabhilash-axway, I'm confused by your `apimCLIHome` as it points to a relative path. And I'm asking myself: Relative to what? 

When you run an `ls` to the constructed filename given in the yellow line - Does this file then exists?

**Comment by cabhilash-axway** [comment]
@cwiechmann I am building a CICD pipeline in GitLab.  Yes file does exist, When i run an `ls` on apimCLIHome.

**Comment by cwiechmann** [comment]
What I meant is: `ls apim-cli-1.2.1/samples/basic..../minimal-api-definition-config.json` 

I think the apimCLIHome is wrong. I think it should be an absolute location and not something relative.

**Comment by cabhilash-axway** [comment]
I run `ls` on that path
![image](https://user-images.githubusercontent.com/51496736/91688136-2e7d6880-eb16-11ea-93d4-8bd84f4e3b95.png)

**Comment by cabhilash-axway** [comment]
Thanks @cwiechmann, It worked with absolute path
