### ISSUE TITLE
Inbound-Security policy is not part of the report generated by API -CLI.

### ISSUE THREAD

**Issue by Arunabandari** [Axway-API-Management-Plus/apim-cli#61]
**User story**

the Inbound-Security policy is not part of the report. Only Request-, Routing- and Response-Policies are available today.

Command :  apim api get -s api-env -o csv -wide

We need  Inbound-Security policy ("Frontend API -> Inbound -> Inbound Security -> *Policy to invoke") value as a column in my custom report for all the APIs.

Discussed the above issue with @cwiechmann . He suggested to create this enhancement issue so he would add this with next release.

**Additional context**

**Comment by Arunabandari** [comment]
Hi @cwiechmann, As we discussed in other issue. i have created this enhancement issue. Just wanted to check with you.. You are taking care this and put it into your next release right?

**Comment by Arunabandari** [comment]
Also, May i know when is your next release for API-CLI ?

**Comment by cwiechmann** [comment]
Hi @Arunabandari, instead of adding an additional column, I propose export the Security-Policy as part of the existing `Security` column like so:
```
+--------------------------------------+-----------------+-----------------------------+---------+--------+-------------+--------------------------+-----------------------+----------+-----------------+
| API-Id                               | Path            | Name                        | Version | V-Host | State       | Backend                  | Security              | Policies | Organization    |
+--------------------------------------+-----------------+-----------------------------+---------+--------+-------------+--------------------------+-----------------------+----------+-----------------+
| e19251d7-3fdc-4cef-bba7-b000b3c75190 | /api/v1/weather | Axway Imagine - Weather API |   1.0.0 |        | unpublished | http://192.168.65.1:8080 | My Security Policy    |          | API Development |
+--------------------------------------+-----------------+-----------------------------+---------+--------+-------------+--------------------------+-----------------------+----------+-----------------+
```
This will also be the case for the CSV-Export. Would that work for you?

**Comment by cwiechmann** [comment]
@Arunabandari, I have also added the capability to filter APIs using a specific Inbound-Security policy. You just add the option: `-policy "My security Pol*"`
You may test the implementation yourself with the following SNAPSHOT version:
 [axway-apimcli-1.3.0-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/5050664/axway-apimcli-1.3.0-SNAPSHOT.zip)

**Comment by Arunabandari** [comment]
Hello @cwiechmann 
I have downloaded the given snapshot version and did run the below commands

apim api get -s api-env -o csv -wide
apim api get -s api-env -policy "Invoke Policy" -o csv -wide        

(here "Invoke Policy" is our custom policy name in the inbound security)

But i am not seeing any "Security" column in the generated CSV report. I am only seeing below columns.

API ID | API Organization | API Name | API Path | API Version | API V-Host | API State | Backend | Request Policy | Routing Policy | Response Policy | Fault-Handler Policy

You have shared one sample record of the generated report with "Security" column. May i know what command you used to generate that?

**Comment by cwiechmann** [comment]
Yeah, funny enough for any reason the CSV-Export requires the `-ultra` instead of the `-wide` option. Perhaps it should be synchronized.
