### ISSUE TITLE
Import beAPI only

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#62]
**API-Manager CLI Version**
API-Manager CLI: 1.2.1

**API-Manager and Service-Pack Version**
7.5.3 SP12

**Question**
Is it possible to import a beAPI only? 

**What I've tried so far**
apim api import, and a couple of configurations of config file

**Additional information**
N/A

**Comment by cwiechmann** [comment]
Hi @emmanuel-galindo, currently that is not supported. What is the use-case behind it to just import the Backend-API?

**Comment by emmanuel-galindo** [comment]
Hi @cwiechmann 
Thanks for the quick reply

In a particular case, a beApi definition is used from another feApi (that has its own beAPI contract) in the outbound method override "Edit API proxy"  section, to do url rewrite from API Manager, and removing the need to use policies. 
Main reason is to abstract the backend system API contract that might not align with design guidelines. We could also keep this system's contract updated and versioned from API Manager. 

Hope it helps

Thanks

**Comment by cwiechmann** [comment]
So, that means this requirement is related to issue: #59 - As you would like to route a request to a certain method from FE-API: "A" to BE-API: "B" and therefore BE-API: "B" needs to be imported first without creating a Frontend-API.
Is my understanding right?

**Comment by emmanuel-galindo** [comment]
@cwiechmann Exactly

**Comment by cwiechmann** [comment]
I'm closing this issue now and leave #59 open, as it's basically a duplicate. However, implementing this is a lot of effort as it's introduces a complete different concept, therefore I cannot give any estimation that is comes or when it comes.
