### ISSUE TITLE
apim-cli.bat not working when JAVA_HOME is not set, but there is java installed

### ISSUE THREAD

**Issue by lacg** [Axway-API-Management-Plus/apim-cli#63]
**API-Mgr. CLI version**
> Please make sure to use the latest available version before reporting a bug.
Version 1.2.1

**API-Manager and Service-Pack Version**
No need, I just trying to run the .\apim-cli.bat and it can't find java.

**Expected behavior**
The apim-cli.bat starts and returns the help.

**Actual behavior**
It returns:
'-Xms64m' is not recognized as an internal or external command,
operable program or batch file.

**Log-Output in Debug**

**Test case sample**
> Please describe the steps you have done to replicate the issue
What I noticed is that it does not find the JAVA_HOME, but it detects that there is a javaFound, so it tries to set the variable _java to java (I can run java on the command prompt, or on the PowerShell just fine), but the SET _java=java is not working (after that I put an echo for the %_java% and it is printing empty...

I tested this on the command prompt on the Windows Server 2008 R2 and on its PowerShell. John Wiese also looked into it with me on his Windows 10 machine and same behavior.

Thanks, Luiz (lgarcia@axway.com)

**Comment by cwiechmann** [comment]
Very likely the same reason as in #64. I have tested it successfully with the apim.bat
