### ISSUE TITLE
More than one api import in single command

### ISSUE THREAD

**Issue by venkatesulua1990** [Axway-API-Management-Plus/apim-cli#66]
**More than one API import in single api-cli command**

In current we can able to import one API with import command but can we try importing multiple API in single command

**Comment by cwiechmann** [comment]
Hi @venkatesulua1990, can you perhaps explain the business requirement behind this request?
I mean, why do you need this feature?

**Comment by venkatesulua1990** [comment]
we have 140 API as part of one project and as per current we need to create 140 projects to run pipeline which becomes 140 pipe lines, it becomes more complex when api count increases.
Business team want single pipeline to deploy all api of single project

**Comment by cwiechmann** [comment]
Hi @venkatesulua1990, to my understanding it's common today, for instance, when using microservices, to have a big number of pipelines as they are not managed/created manually anyway. With Jenkins for instance each teams/project controls on hits own, how the pipeline should like like. 

Additionally, even if the CLI would iterate over 140 APIs, it would take 20-30 minutes until it's finished. Assuming, this process would be required just to replicate a design change in one API sounds inefficient to me. 

Have you seen this documentation: https://docs.axway.com/bundle/axway-open-docs/page/docs/api_mgmt_overview/api_mgmt_components/pipeline/index.html

I'm going to close this issue now, as it's not planned short-/mid-term to implement this requirement.
