### ISSUE TITLE
CSRF token issue with HAProxy

### ISSUE THREAD

**Issue by cbrowet-axway** [Axway-API-Management-Plus/apim-cli#67]
**API-Mgr. CLI version**
1.2.1

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
CSRF token is recognized and handled

**Actual behavior**
CSRF token returned from APIM through HAProxy is ignored

The problem is that HAProxy returns headers in lowercase and https://github.com/Axway-API-Management-Plus/apim-cli/blob/develop/modules/apim-adapter/src/main/java/com/axway/apim/adapter/APIManagerAdapter.java#L312 do a case-sensitive look up for "CSRF-Token".

As http headers are case-insensitive (https://tools.ietf.org/html/rfc7230#section-3.2), the above should probably be
```java
			if(header.getName().equalsIgnoreCase("csrf-token")) {
```

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @cbrowet-axway! Very helpful.
