### ISSUE TITLE
Import/Export general API Manager settings

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apim-cli#68]
hi @cwiechmann, congrats for your great job for this tool!!! 

Have you ever thought about handling the general API manager settings in the same approach (desired vs. actual state)? I refer to all the settings that you can manually change in Api Manager web interface -> Settings menu

thanks

**Comment by cwiechmann** [comment]
Hi @gcornacchia, Yes, in general the CLI should support all entities of the API-Manager and even the API-Gateway. Settings would be one of them and relatively easy to implement as the model is simple. It's a matter of time and doing it.

**Comment by cwiechmann** [comment]
Hi @gcornacchia, I have worked a lot on adding support to manage API-Manager Configuration. Actually it looks like this:
![image](https://user-images.githubusercontent.com/16292002/96109658-28cdbd80-0edf-11eb-9677-f13d13d28e85.png)

Would you expect it in that way or having the complete API-Manager configuration in one file? Something like so:
```json
{
  "alerts": {
     (API-Manager Alerts)
  }, 
  "config": {
     (The base API-Manager configuration)  
  }, 
  "remotehosts": {
     (A list/array of RemoteHosts)
  }
}
```
That kind of file you would create/manage with the following commands:
`apim setup get -s api-env -o json`
Perhaps adding options to decide what to export:
`apim setup get -s api-env -o json -type config,alerts`

When importing the complete file would be used and parts not set will be ignored:
`apim setup import -s api-env -c setup/config_and_alerts.json`

What would you prefer @gcornacchia?

**Comment by cwiechmann** [comment]
I have decided to provide one central option to manage the complete configuration
- this option takes in the complete configuration
- or just one or two 

![image](https://user-images.githubusercontent.com/16292002/96152183-8debd800-0f0c-11eb-9697-e7542be3b014.png)

I think this way it's more convenient for users.
