### ISSUE TITLE
[Feature] REST-API - Swagger-Promote as a Service

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apim-cli#7]
**User story**
The requirement is to have Swagger-Promote running as a service in front of each API-Manager instead of running it individually for each API. With that, new options would be possible as basically every REST-Client can easily promote/replicate an API into the API-Manager.

With that the following issues will be solved:
- [ ] Axway-API-Management-Plus/apimanager-swagger-promote#144
- [ ] Axway-API-Management-Plus/apimanager-swagger-promote#143 

**Additional context**
Has been prototyped during the API-Management Hackathon in Paris. See here: 
https://github.com/axwayhackathon/apimanager-swagger-promote

**Comment by jschaefer77** [comment]
Hi @cwiechmann, are there any updates about the topic. Is Q2 this year still a valid date?
And do you plan to integrate APIM CLI as service into API Manager?

**Comment by cwiechmann** [comment]
@jschaefer77, the changes I made as part of the refactoring into the apim -cli had this feature in mind. I basically fully separated the code, that is reading the API-Config from the code, that is replicating the API-Config into the API-Manager. 
With that now in place, an HTTP Server instead of the JSONConfigLoader can read the data (from the InputStream) and hand it over to the same API replicating implementation. 

Nevertheless, I think end of Q2 is no longer realistic as the migration took longer. I aim for end of Q3.

**Comment by cwiechmann** [comment]
> And do you plan to integrate APIM CLI as service into API Manager?
The service would run in front of the API-Manager (e.g. as a Docker-Container)

**Comment by jschaefer77** [comment]
hi @cwiechmann, great. thx for the info.

**Comment by jschaefer77** [comment]
Hi @cwiechmann , are there any updates/progress about that topic.

**Comment by cwiechmann** [comment]
Hi @jschaefer77, no progress sorry and I cannot say, when this becomes available. Please don't count on it for now.

**Comment by cwiechmann** [comment]
Finally no bandwidth to implement this.
