### ISSUE TITLE
[New feature] Support for Yaml files when replacing host in API definition file

### ISSUE THREAD

**Issue by ua-sopra-steria** [Axway-API-Management-Plus/apim-cli#8]
The API definition file (parameter apiDefinition) can be both Json and Yaml as API Manager 7.7 supports both formats. However, when the parameter backendBasepath is specified, then the promote tool tries to change the corresponding parameters in the Swagger file - and this fails because the promote tool is only capable of parsing the Json format.

With this change the promote tool will be able to support the Yaml format when the backendBasepath parameter is specified.

**Comment by cwiechmann** [comment]
The feature to load YAML based Swagger-/OpenAPI-Definitions has been added and will be released with version 1.1.0
