### ISSUE TITLE
Get a list of APIs based on Tags

### ISSUE THREAD

**Issue by mpentzek** [Axway-API-Management-Plus/apim-cli#82]
**User story**
Tags are widely used to group APIs based on different criteria and helps searching them in API Manager or API Portal.
It would be great if APIs could be identified by Tags as well in the APIM CLI (API GET command) for display or export purpose, similar to the handling described in the Axway docs: 
https://docs.axway.com/bundle/axway-open-docs/page/docs/central/connect-api-manager/filtering-apis-to-be-discovered/index.html

**Comment by cwiechmann** [comment]
Thanks for adding this enhancement. Implement this as an additional filter option. Part of the next release 1.2.3
