### ISSUE TITLE
Add filter for inbound and outbound security settings

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#86]
**User story**
As API admin, I want to filter for specific inbound and outbound security settings if I use the "apim api get" command.
E.g. which APIs are using inbound "Pass Through" or which APIs are using outbound OAuth and which provider profile.

**Additional context**

**Comment by cwiechmann** [comment]
I have added support to filter for inbound and outbound security with the following new filters:
`-inboundsecurity` which supports simple filtering on the standard security devices or a given custom-policy name.
`-outboundauthn` filter for standard AuthN devices. If you filter for instance like so: `*My OAuth Client*`all APIs are returned having OAuth configured with the given client application name.

To filter for standard security devices the following alias names can be used and everything is converted to lowercase.
__inboundsecurity__:
| Device-Type       | Alias| 
| :---          | :---                 |
|API Key| "api-key", "apikey"|
|HTTP Basic| "httpbasic", "http-basic"|
|OAuth| "oauth"|
|OAuth (External)| "oauthext", "oauth-ext", "oauth-external"|
|Policy |"policy" (And the Policy-Name itself)|
|Pass Through| "passthrough", "none", "pass-through"|
|AWS Sign Header| "aws", "aws-header", "aws-sign-header" 
|AWS Sign Query| "aws", "aws-query", "aws-sign-query"|
|Two-Way SSL| "ssl", "two-way-ssl", "mutual"|

__outboundauthn__:
| Device-Type       | Alias| 
| :---          | :---                 |
|None| none"|
|HTTP Basic| "httpbasic", "http-basic", "basic"|
|HTTP Digest| "http-digest", "httpdigest", "basic", "digest"|
|API-Key|"apikey", "api-key", "key"|
|OAuth| "oauth", "o-auth"|
|SSL| "ssl", "mutual", "mutualssl", "mutualssl"|

@jschaefer77, let me know if you miss anything?

**Comment by cwiechmann** [comment]
If you miss anything, feel free to-reopen this issue.

**Comment by jschaefer77** [comment]
Hi @cwiechmann , wow looks really good. There is one thing missing IMO. In _API Manager UI -> Outbound -> Outbound authentication profile_ you can select OAuth and then you need to select an Provider profile. It would be really helpful for us to filter for that provider profile as well, not only for outbound OAuth in general.

**Comment by cwiechmann** [comment]
To add - These would be then the new options:
```
 -inboundsecurity <oauth-ext|api-key|*my-security-pol*|...>   Filter APIs with specific Inbound-Security. Wildcards are supported when
                                                              filtering for policies.
 -outboundauthn <oauth|api-key|*Provider Profile*|...>        Filter APIs with specific Outbound-Authentication. Wildcards are supported
                                                              when filtering for Provider Profile name
```

**Comment by jschaefer77** [comment]
Hi @cwiechmann , maybe you can do a small tweak in the documentation to make clear that the profile name is used only in the case of OAuth.
E.g. Filter APIs with specific Outbound-Authentication. Wildcards are supported when filtering for an OAuth Provider Profile name.
