### ISSUE TITLE
How could we handle organization and additional attributes for Applications configuration?

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apim-cli#87]
**API-Manager CLI Version**
1.2.3

**API-Manager and Service-Pack Version**
7.7.20200730

**Question**
We are trying to create applications with apim-cli but we don't know how to handle : 
1- organization
2 - additional attributes
in the json configuration file for applications

**What I've tried so far**

**Additional information**

**Comment by Rennaud** [comment]
For organization the solution is using : "organizationId" 
But for additional attribute, we cannot find out how to set them up.

**Comment by cwiechmann** [comment]
Custom-Properties for organizations and applications are not yet supported. The organization should be just the field: `organization` containing the name of the application.

**Comment by cwiechmann** [comment]
@Rennaud, can you perhaps confirm, that the organization part is working as expected? I'm going to create an issue to add support for custom-properties for Apps & Orgs.

**Comment by Rennaud** [comment]
yes, for organization it works fine. You can use either "organizationId" = id of the orga or "organization" = name of the orga.

**Comment by cwiechmann** [comment]
Thanks! New issue #93 created. Going to close this one.
