### ISSUE TITLE
Parameter "enabled" for application is not taking in account

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apim-cli#89]
**API-Mgr. CLI version**
1.2.3

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
When the parameter is set to false = having in API Manager the parameter "enabled" to "off/disable"

**Actual behavior**
Setting the parameter to false doesn't change the value in API Manager

**Log-Output in Debug**

**Test case sample**
config file for Application : 
{
  "name" : "Appli1",
  "description" : "test",
  "state" : "approved",
  "image" : "",
  "enabled" : false,
  "email" : "",
  "phone" : ""
}

**Comment by cwiechmann** [comment]
That is really interesting. The call to create the application is correct as it contains the enabled false flag, but this ignored by the API-Manager when creating the application: 
```json
{
  "name": "Disabled-App-6261",
  "description": "test",
  "enabled": false,
  "state": "approved",
  "organizationId": "75b81ead-18fa-4147-94d7-46ec6cd1b9df",
  "apis": []
}
```
So, very likely another PUT request is required to update the application to disabled. :unamused:

**Comment by cwiechmann** [comment]
Good spot @Rennaud. Will be fixed with next release.
