### ISSUE TITLE
Why is adding a Routing Policy considered a breaking change ?

### ISSUE THREAD

**Issue by gwandwingor** [Axway-API-Management-Plus/apim-cli#94]
**API-Manager CLI Version**
1.2.3

**API-Manager and Service-Pack Version**
7.7 May 2020

**Question**
I have a use case where I need to add a routing policy to an API already published on production. This API has lots of client applications using quotas.
When I add an outbound profile with a "routePolicy", I can see in the logs that apim-cli chooses to delete & recreate the API instead of unpublishing, modifying & republishing it.
This has the consequence of resetting all current app quota values to 0, which I'd like to avoid.

Hence my question, how come adding a routing policy, and probably any kind of request/response policy is considered a breaking change, as it can be done without recreating the FE API in the UI ?

Here's an example trace file : 

```
17381  INFO      APIImportManager| Recognized the following changes. Potentially Breaking: [outboundProfiles] plus Non-Breaking: []
17381  INFO      APIImportManager| Update API Strategy: Re-Create API as changes can't be applied to existing API.
17382  INFO   RecreateToUpdateAPI| Create new API to update existing: 'Test API' (ID: 0ae8d6d5-0644-4d21-a81d-5782a60ee1e7)
17589  INFO          CreateNewAPI| Create published API: 'Test API' 1.0.0 based on Swagger 2.0 specification.
23899  INFO  APIManagerAPIAdapter| Upgrade access & subscriptions to newly created API.
25817  INFO          CreateNewAPI| Successfully created published API: 'Test API' 1.0.0 (ID: 28d18a6b-b6f6-4514-821e-02cbc77a9526)
25818  INFO   RecreateToUpdateAPI| New API successfuly created. Going to delete old API: 'Test API' 1.0.0 (ID: 0ae8d6d5-0644-4d21-a81d-5782a60ee1e7)
27861  INFO  APIManagerAPIAdapter| API: Test API successfully deleted
```

**Comment by cwiechmann** [comment]
You are right, all kind of policies are considered as potential breaking changes, as you could do basically anything with them.
The decision to re-create the API is not based on breaking or non-breaking. 
Each property of an API has configured in which states its changeable or not.
Policies are not changeable when published, hence the API is re-created to apply the change. The CLI is re-creating the APU for internal simplification.
Even if the API is only unpublished, as you asked, you lose all client-subscriptions along with their current runtime quota. Hence, that would not solve your problem.

As you know, the CLI re-creates the current quota configuration, but not the runtime quota as their is no API for that.

Perhaps re-importing the backend API is not required, but is this really a beneficial not to do that?

**Comment by gwandwingor** [comment]
Thanks for this explanation @cwiechmann.

I need to double check to make sure I didn't make any mistake, but I did a simple test where I : 
- set a 5msg/hour quota to an app
- made 6 calls -> got 5 '200' and 1 '429'
- unpublished the API
- made 1 call -> got '429'
- modified the routing policy
- published the API -> still got '429'
Client App org had no "API Development" credentials.

**Comment by gwandwingor** [comment]
Thanks, @cwiechmann.
The test I made was with a quota specific for an application. I didn't test with App-default.

**Comment by cwiechmann** [comment]
Interesting result. Looks like the quota survives the unpublish process. Good to know.
I’m going to close this issue now, as the question has been answered and the CLI will be improved with the issue #95.
Thanks!
